### ISSUE TITLE
Support for building docker images offline.

### ISSUE THREAD

**Issue by jesuslinares** [wazuh/wazuh-docker#100]
Hello team,
we should allow the creation of Wazuh docker images (specially the Wazuh manager one) offline.

For this we need:
- List of dependencies, including the base image we are based on (currently phusion:latest)
- Instructions.

Main caveat being dependencies size.

Regards.

**Comment by LuisGi93** [comment]
It is possible to build the docker Wazuh-manager offline using the following branch [wazuh-manager-local](https://github.com/wazuh/wazuh-docker/tree/wazuh-manager-local). The main caveats are the dependencies. To build the image the following prerequisites are needed:
- The base image phusion/baseimage need to be available in the offline environment. Right now the following tags are supported 0.10.0, 0.10.1, 0.10.2 and the latest tag.
- The packages that the Wazuh-manager image needs and its dependencies should reside in the "dependencies" folder.

When the above prerequisites have been met   ```docker-compose build``` command need to be executed in the folder of the docker-compose.yml file.

The packages and its dependencies need to be downloaded **from the same image** (phusion/baseimage) that we are going to use to build the Wazuh-manager. A list of the packages needed can be found at wazuh/dependencies/files and also a helpful script named download.sh that will download all the needed files. To use this script to download the dependencies:
- Enter into  phusion/baseimage at the online environment.
- Copy the script and wazuh/dependencies/files into phusion/baseimage.
- Execute the script.
- Compress all the packages that it downloads and move it to the the offline environment.
- Decompress at the wazuh/dependencies folder.
- Then execute   ```docker-compose build```.

There  is also a more handy alternative is to build the image:
-  Use our [current version repository](https://github.com/wazuh/wazuh-docker/tree/3.8.0_6.5.4) to build the image, 
- Export it to a tar.gz using ```docker save id_image -o file.ta.gz wazuh-docker_wazuh:latest```
- Move it to the offline environment.
- Import it using ```docker load  file.tar.gz```

**Comment by jm404** [comment]
I'm closing the issue due to inactivity.
