### ISSUE TITLE
client.keys file/symlink

### ISSUE THREAD

**Issue by rhysxevans** [wazuh/wazuh-docker#103]
Hi

I am using Wazuh in a docker container, with a docker file based off of [https://hub.docker.com/r/wazuh/wazuh/dockerfile](). I have added a few things to if apache2-utils and a basic main.cf to get around a few issues. However I am having an issue with the /var/ossec/etc/client.keys file.

Prior to registering a client the file is a symlink to ../data/etc/client.keys

`
root@wazuh:/#  ls -lh /var/ossec/etc/
total 72K
-rw-r--r--. 1 root  root     6 Jan 24 11:48 authd.pass
lrwxrwxrwx. 1 root  root    23 Jan 24 11:47 client.keys -> ../data/etc/client.keys
`

As soon as I register an agent (I am using `wazuh-agent-3.8.0-1.msi /q ADDRESS="192.168.56.35" AUTHD_SERVER="192.168.56.35" PASSWORD="wazuh"` ) the symlink is "broken" and the file now liike like this

`
root@wazuh:/# ls -lh /var/ossec/etc/
total 76K
-rw-r--r--. 1 root root     6 Jan 24 14:05 authd.pass
-rw-rw----. 1 root ossec   78 Jan 24 14:06 client.keys
`

What this means is the client.keys file is not persisted across redeploy's as the file is not store in the /var/ossec/data folder

Any ideas 

Thanks

**Comment by SitoRBJ** [comment]
Hello @rhysxevans,

We just created an environment using our docker-compose with Wazuh version 3.8.0 and 3.8.1. We have enabled a volume to store `/var/ossec/data` content. When you register an agent, our `client.keys` file is filled correctly and stored correctly in the volume. At the time of destroying the container and creating it again, the agent was still registered thanks to the volume.

Could you try with an agent 3.8.1?

What version of the manager are you using?

It is possible that some of your changes influence when registering the agent, you could tell us. 

We have tested versions 3.8.0 and 3.8.1 and have not been able to replicate your case. 

Note that the management of volumes and directories is being carried out in the entrypoint. 

https://github.com/wazuh/wazuh-docker/blob/master/wazuh/config/entrypoint.sh

Kind regards,

Alfonso Ruiz-Bravo

**Comment by rhysxevans** [comment]
Hi

I was testing with Manager 3.8.0  and agent 3.8.0

the part of my docker-compose calling wazuh is below
`
  wazuh:
    build:
      context: build/wazuh/
      args:
        FILEBEAT_VERSION: $ELASTIC_VERSION
        WAZUH_SERVER_VERSION: $WAZUH_SERVER_VERSION
    container_name: wazuh
    hostname: wazuh
    restart: unless-stopped
    environment:
      - "LS_PUBLIC=${LS_PUBLIC}"
      - "WAZUH_API_USERNAME=${WAZUH_API_USERNAME}"
      - "WAZUH_API_USER_PASSWORD=${WAZUH_API_USER_PASSWORD}"
      - "WAZUH_AUTO_ENROLLMENT_ENABLED=${WAZUH_AUTO_ENROLLMENT_ENABLED}"
      - "WAZUH_ENABLE_INTEGRATOR=${WAZUH_ENABLE_INTEGRATOR}"
      - "WAZUH_AGENT_PASSWORD=${WAZUH_AGENT_PASSWORD}"
    secrets:
      - source: wazuh-filebeat.yml
        target: /etc/filebeat/filebeat.yml
      - source: wazuh-postfix-main.cf
        target: /etc/postfix/main.cf
      - source: wazuh-searchguard-es-sg-root-ca.pem
        target: /etc/filebeat/root-ca.pem
      - source: wazuh-elastic6-template-alerts.json
        target: /var/ossec/etc/wazuh-elastic6-template-alerts.json
      - source: wazuh-api-config
        target: /var/ossec/api/configuration/config.js
      - source: wazuh-api-ssl-cert
        target: /var/ossec/api/configuration/ssl/server.crt
      - source: wazuh-api-ssl-key
        target: /var/ossec/api/configuration/ssl/server.key
      - source: searchguard-es-sg-root-ca.pem
        target: /var/ossec/api/configuration/ssl/ca.crt
      - source: wazuh-ssl-cert
        target: /var/ossec/etc/sslmanager.cert
      - source: wazuh-ssl-key
        target: /var/ossec/etc/sslmanager.key
      - source: wazuh-ossec.conf
        target: /var/ossec/etc/ossec.conf
      - source: wazuh-0452-pfsense-new-Decoders.xml
        target: /var/ossec/etc/decoders/0452-pfsense-new-Decoders.xml
      - source: wazuh-local_rules.xml
        target: /var/ossec/etc/rules/wazuh-local_rules.xml
    networks: ['stack']
    ports: ['1514:1514/udp','514:514/udp','514:514','1514-1516:1514-1516']
    expose:
      - "55000"  #Only expose API internally
    depends_on: ['logstash01', 'kibana']
    volumes:
      - 'wazuh_ossec_data:/var/ossec/data'
      - 'wazuh_filebeat:/etc/filebeat'
      - 'wazuh_postfix:/etc/postfix'
    healthcheck:
      test: curl -k -u "${WAZUH_API_USERNAME}":"${WAZUH_API_USER_PASSWORD}" -s  https://localhost:55000 >/dev/null; if [[ $$? == 0 ]]; then echo 0; else echo 1; fi
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  wazuh_ossec_data:
  wazuh_filebeat:
  wazuh_postfix:

secrets:
  wazuh-searchguard-es-sg-root-ca.pem:
    file: ./config/elasticsearch/sg/certs/root-ca.pem
  wazuh-filebeat.yml:
    file: ./config/wazuh/filebeat.yml
  wazuh-postfix-main.cf:
    file: ./config/wazuh/main.cf
  wazuh-elastic6-template-alerts.json:
    file: ./config/wazuh/wazuh-elastic6-template-alerts.json
  wazuh-kibana-api:
    file: ./config/wazuh/wazuh-kibana-api
  wazuh-api-config:
    file: ./config/wazuh/config/api/config.js
  wazuh-api-ssl-cert:
    file: ./config/elasticsearch/sg/certs/wazuh_http.pem
  wazuh-api-ssl-key:
    file: ./config/elasticsearch/sg/certs/wazuh_http.key
  wazuh-ssl-cert:
    file: ./config/elasticsearch/sg/certs/wazuh_http.pem
  wazuh-ssl-key:
    file: ./config/elasticsearch/sg/certs/wazuh_http.key
  wazuh-ossec.conf:
    file: ./config/wazuh/config/etc/ossec.conf
  wazuh-0452-pfsense-new-Decoders.xml:
    file: ./config/wazuh/config/etc/decoders/0452-pfsense-new-Decoders.xml
  wazuh-local_rules.xml:
    file: ./config/wazuh/config/etc/rules/local_rules.xml
`

Docker File

`
# Wazuh App Copyright (C) 2018 Wazuh Inc. (License GPLv2)
FROM phusion/baseimage:latest
ARG FILEBEAT_VERSION
ARG WAZUH_SERVER_VERSION
ARG LS_PUBLIC

# Updating image
RUN apt-get update && apt-get upgrade -y -o Dpkg::Options::="--force-confold"

# Set Wazuh repository.
RUN echo "deb https://packages.wazuh.com/3.x/apt/ stable main" | tee /etc/apt/sources.list.d/wazuh.list
RUN curl -s https://packages.wazuh.com/key/GPG-KEY-WAZUH | apt-key add -

# Set nodejs repository.
RUN curl --silent --location https://deb.nodesource.com/setup_8.x | bash -

# Creating ossec user as uid:gid 1000:1000
RUN groupadd -g 1000 ossec
RUN useradd -u 1000 -g 1000 -d /var/ossec ossec

# Configure postfix
RUN echo "postfix postfix/mailname string wazuh-manager" | debconf-set-selections
RUN echo "postfix postfix/main_mailer_type string 'Internet Site'" | debconf-set-selections

# Add universe repository
RUN add-apt-repository universe

# Install packages
# Gets around postix ..local build issues
COPY config/main.cf /etc/postfix/
RUN apt-get update && apt-get install postfix bsd-mailx mailutils -y

RUN apt-get -y install openssl python-boto python-pip  \
    apt-transport-https vim expect nodejs python-cryptography wazuh-manager=${WAZUH_SERVER_VERSION} \
    wazuh-api=${WAZUH_SERVER_VERSION} libsasl2-modules apache2-utils

# Adding first run script.
ADD config/data_dirs.env /data_dirs.env
ADD config/init.bash /init.bash

# Sync calls are due to https://github.com/docker/docker/issues/9547
RUN chmod 755 /init.bash
RUN sync && /init.bash &&\
    sync && rm /init.bash

# Installing and configuring filebeat
RUN curl -L -O https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-${FILEBEAT_VERSION}-amd64.deb &&\
    dpkg -i filebeat-${FILEBEAT_VERSION}-amd64.deb && rm -f filebeat-${FILEBEAT_VERSION}-amd64.deb
COPY config/filebeat.yml /etc/filebeat/
RUN chmod go-w /etc/filebeat/filebeat.yml

# Adding entrypoint
ADD config/entrypoint.sh /entrypoint.sh
RUN chmod 755 /entrypoint.sh

# Clean up
RUN apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

# Adding services
RUN mkdir /etc/service/wazuh
COPY config/wazuh.runit.service /etc/service/wazuh/run
RUN chmod +x /etc/service/wazuh/run

RUN mkdir /etc/service/wazuh-api
COPY config/wazuh-api.runit.service /etc/service/wazuh-api/run
RUN chmod +x /etc/service/wazuh-api/run

RUN mkdir /etc/service/postfix
COPY config/postfix.runit.service /etc/service/postfix/run
RUN chmod +x /etc/service/postfix/run

RUN mkdir /etc/service/filebeat
COPY config/filebeat.runit.service /etc/service/filebeat/run
RUN chmod +x /etc/service/filebeat/run

# Temporary fix for AWS integration - Need to review whether this can go
RUN sed -i 's/.*with open*/#wiht open/' /var/ossec/wodles/aws/aws-s3
RUN sed -i 's/.*max_queue_buffer = int(kernel_param.read().strip())*/#max_queue_buffer/' /var/ossec/wodles/aws/aws-s3
RUN sed -i '784imax_queue_buffer = 0' /var/ossec/wodles/aws/aws-s3
RUN sed -i '784s/^/    /' /var/ossec/wodles/aws/aws-s3

# Run all services
ENTRYPOINT ["/entrypoint.sh"]
`

my entrypoint.sh - I have added a few things - mainly whether to enable the intergrator and set the api password

`
#!/bin/bash
# Wazuh App Copyright (C) 2018 Wazuh Inc. (License GPLv2)

#
# OSSEC container bootstrap. See the README for information of the environment
# variables expected by this script.
#

#

#
# Startup the services
#

source /data_dirs.env

FIRST_TIME_INSTALLATION=false

WAZUH_INSTALL_PATH=/var/ossec
DATA_PATH=${WAZUH_INSTALL_PATH}/data

WAZUH_CONFIG_MOUNT=/wazuh-config-mount

print() {
    echo -e $1
}

error_and_exit() {
    echo "Error executing command: '$1'."
    echo 'Exiting.'
    exit 1
}

exec_cmd() {
    eval $1 > /dev/null 2>&1 || error_and_exit "$1"
}

exec_cmd_stdout() {
    eval $1 2>&1 || error_and_exit "$1"
}

edit_configuration() { # $1 -> setting,  $2 -> value
    sed -i "s/^config.$1\s=.*/config.$1 = \"$2\";/g" "${DATA_PATH}/api/configuration/config.js" || error_and_exit "sed (editing configuration)"
}

for ossecdir in "${DATA_DIRS[@]}"; do
  if [ ! -e "${DATA_PATH}/${ossecdir}" ]
  then
    print "Installing ${ossecdir}"
    exec_cmd "mkdir -p $(dirname ${DATA_PATH}/${ossecdir})"
    exec_cmd "cp -pr /var/ossec/${ossecdir}-template ${DATA_PATH}/${ossecdir}"
    FIRST_TIME_INSTALLATION=true
  fi
done

touch ${DATA_PATH}/process_list
chgrp ossec ${DATA_PATH}/process_list
chmod g+rw ${DATA_PATH}/process_list

AUTO_ENROLLMENT_ENABLED=${WAZUH_AUTO_ENROLLMENT_ENABLED:-true}
API_GENERATE_CERTS=${API_GENERATE_CERTS:-true}

if [ $FIRST_TIME_INSTALLATION == true ]
then
  if [ $AUTO_ENROLLMENT_ENABLED == true ]
  then
    if [ ! -e ${DATA_PATH}/etc/sslmanager.key ]
    then
      print "Creating ossec-authd key and cert"
      exec_cmd "openssl genrsa -out ${DATA_PATH}/etc/sslmanager.key 4096"
      exec_cmd "openssl req -new -x509 -key ${DATA_PATH}/etc/sslmanager.key -out ${DATA_PATH}/etc/sslmanager.cert -days 3650 -subj /CN=${HOSTNAME}/"
    fi
  fi
  if [ $API_GENERATE_CERTS == true ]
  then
    if [ ! -e ${DATA_PATH}/api/configuration/ssl/server.crt ]
    then
      print "Enabling Wazuh API HTTPS"
      edit_configuration "https" "yes"
      print "Create Wazuh API key and cert"
      exec_cmd "openssl genrsa -out ${DATA_PATH}/api/configuration/ssl/server.key 4096"
      exec_cmd "openssl req -new -x509 -key ${DATA_PATH}/api/configuration/ssl/server.key -out ${DATA_PATH}/api/configuration/ssl/server.crt -days 3650 -subj /CN=${HOSTNAME}/"
    fi
  fi
fi

##############################################################################
# Copy all files from $WAZUH_CONFIG_MOUNT to $DATA_PATH and respect
# destination files permissions
#
# For example, to mount the file /var/ossec/data/etc/ossec.conf, mount it at
# $WAZUH_CONFIG_MOUNT/etc/ossec.conf in your container and this code will
# replace the ossec.conf file in /var/ossec/data/etc with yours.
##############################################################################
if [ -e "$WAZUH_CONFIG_MOUNT" ]
then
  print "Identified Wazuh configuration files to mount..."

  exec_cmd_stdout "cp --verbose -r $WAZUH_CONFIG_MOUNT/* $DATA_PATH"
else
  print "No Wazuh configuration files to mount..."
fi

# Enabling ossec-authd.
exec_cmd "/var/ossec/bin/ossec-control enable auth"

# Enable integrator
WAZUH_ENABLE_INTEGRATOR=${WAZUH_ENABLE_INTEGRATOR}

if [ $WAZUH_ENABLE_INTEGRATOR == true ]
then
   exec_cmd "/var/ossec/bin/ossec-control enable integrator"
fi

# Set wazuh agent Password
WAZUH_AGENT_PASSWORD=${WAZUH_AGENT_PASSWORD}
exec_cmd "echo "${WAZUH_AGENT_PASSWORD}" > /var/ossec/etc/authd.pass"


function ossec_shutdown(){
  ${WAZUH_INSTALL_PATH}/bin/ossec-control stop;
}

# Trap exit signals and do a proper shutdown
trap "ossec_shutdown; exit" SIGINT SIGTERM

chmod -R g+rw ${DATA_PATH}

# Fix for logs issue - in wazuh.runit.service and wazuh-api.runit.service files
if [ ! -e ${DATA_PATH}/logs ]
then
  print "Symlink fix..."
  exec_cmd_stdout  "ln -s /var/ossec/logs /var/ossec/data/logs"
else
  print "Symlink previoulsy created fix..."
fi

# Set API Username and password
print "Setting Wazuh API Username and Password..."
exec_cmd_stdout "mkdir -p /var/ossec/api/configuration/auth"
exec_cmd_stdout "htpasswd -b -c /var/ossec/api/configuration/auth/user ${WAZUH_API_USERNAME} ${WAZUH_API_USER_PASSWORD}"

#exec_cmd_stdout "cd /var/ossec/api/configuration/auth && node htpasswd -b -c user ${WAZUH_API_USERNAME} ${WAZUH_API_USER_PASSWORD}"

##############################################################################
# Interpret any passed arguments (via docker command to this entrypoint) as
# paths or commands, and execute them.
#
# This can be useful for actions that need to be run before the services are
# started, such as "/var/ossec/bin/ossec-control enable agentless".
##############################################################################
for CUSTOM_COMMAND in "$@"
do
  echo "Executing command \`${CUSTOM_COMMAND}\`"
  exec_cmd_stdout "${CUSTOM_COMMAND}"
done

/sbin/my_init 
`

I will rebuild with 3.8.1 and come back to you

Thanks

**Comment by SitoRBJ** [comment]
Hello @rhysxevans,

In version 3.8.0 of Wazuh **authd** is enabled by default. This command in your `entrypoint `would have no effect. 

```
$ /var/ossec/bin/ossec-control enable auth
This option is deprecated because Authd is now enabled by default. If you want to change it, modify the ossec.conf file.

```

Have you registered the agent? in order to use the password stored in `authd.pass` it is necessary to change the configuration in `ossec.conf` and change the entry `<use_password>`:


```
  <auth>
    <disabled>no</disabled>
    <port>1515</port>
    <use_source_ip>yes</use_source_ip>
    <force_insert>yes</force_insert>
    <force_time>0</force_time>
    <purge>yes</purge>
    <use_password>yes</use_password>
     .  .  .
  </auth>
```

Best regards,

Alfonso Ruiz-Bravo

**Comment by rhysxevans** [comment]
ok, just run a quick test. both agent and manager 3.8.1. same issue

```
[adminuser@el02 elk-master]$ docker exec -it wazuh /bin/bash
root@wazuh:/# ls -lh /var/ossec/etc/
total 72K
-rw-r--r--. 1 root  root     6 Jan 25 11:45 authd.pass
lrwxrwxrwx. 1 root  root    23 Jan 25 11:40 client.keys -> ../data/etc/client.keys
-rw-r-----. 1 root  ossec    0 Jan 25 11:40 client.keys-template
lrwxrwxrwx. 1 root  root    20 Jan 25 11:40 decoders -> ../data/etc/decoders
drwxrwx---. 2 root  ossec   31 Jan 25 11:39 decoders-template
-rw-r-----. 1 root  ossec  12K Jan 24 18:09 internal_options.conf
lrwxrwxrwx. 1 root  root    17 Jan 25 11:40 lists -> ../data/etc/lists
drwxrwx---. 3 root  ossec  122 Jan 25 11:39 lists-template
lrwxrwxrwx. 1 root  root    39 Jan 25 11:40 local_internal_options.conf -> ../data/etc/local_internal_options.conf
-rw-r-----. 1 root  ossec  320 Jan 24 18:09 local_internal_options.conf-template
lrwxrwxrwx. 1 root  root    21 Jan 25 11:40 localtime -> ../data/etc/localtime
-rw-r-----. 1 root  ossec  127 Jan  1 05:22 localtime-template
lrwxrwxrwx. 1 root  root    22 Jan 25 11:40 ossec.conf -> ../data/etc/ossec.conf
-rw-r-----. 1 root  ossec 9.2K Jan 25 11:40 ossec.conf-template
lrwxrwxrwx. 1 root  root    20 Jan 24 18:09 ossec-init.conf -> /etc/ossec-init.conf
lrwxrwxrwx. 1 root  root    21 Jan 25 11:40 rootcheck -> ../data/etc/rootcheck
drwxrwx---. 2 root  ossec 4.0K Jan 25 11:39 rootcheck-template
lrwxrwxrwx. 1 root  root    17 Jan 25 11:40 rules -> ../data/etc/rules
drwxrwx---. 2 root  ossec   29 Jan 25 11:39 rules-template
lrwxrwxrwx. 1 root  root    18 Jan 25 11:40 shared -> ../data/etc/shared
drwxrwx---. 3 root  ossec   63 Jan 25 11:40 shared-template
lrwxrwxrwx. 1 root  root    27 Jan 25 11:40 sslmanager.cert -> ../data/etc/sslmanager.cert
-rw-r-----. 1 root  root  1.2K Jan 25 11:40 sslmanager.cert-template
lrwxrwxrwx. 1 root  root    26 Jan 25 11:40 sslmanager.key -> ../data/etc/sslmanager.key
-rw-r-----. 1 root  root  1.7K Jan 25 11:40 sslmanager.key-template
-rw-rw-r--. 1 ossec root   22K Jan 25 11:12 wazuh-elastic6-template-alerts.json
root@wazuh:/# ls -lh /var/ossec/etc/
total 76K
-rw-r--r--. 1 root  root     6 Jan 25 11:45 authd.pass
-rw-rw----. 1 root  ossec   78 Jan 25 11:47 client.keys
-rw-r-----. 1 root  ossec    0 Jan 25 11:40 client.keys-template
lrwxrwxrwx. 1 root  root    20 Jan 25 11:40 decoders -> ../data/etc/decoders
drwxrwx---. 2 root  ossec   31 Jan 25 11:39 decoders-template
-rw-r-----. 1 root  ossec  12K Jan 24 18:09 internal_options.conf
lrwxrwxrwx. 1 root  root    17 Jan 25 11:40 lists -> ../data/etc/lists
drwxrwx---. 3 root  ossec  122 Jan 25 11:39 lists-template
lrwxrwxrwx. 1 root  root    39 Jan 25 11:40 local_internal_options.conf -> ../data/etc/local_internal_options.conf
-rw-r-----. 1 root  ossec  320 Jan 24 18:09 local_internal_options.conf-template
lrwxrwxrwx. 1 root  root    21 Jan 25 11:40 localtime -> ../data/etc/localtime
-rw-r-----. 1 root  ossec  127 Jan  1 05:22 localtime-template
lrwxrwxrwx. 1 root  root    22 Jan 25 11:40 ossec.conf -> ../data/etc/ossec.conf
-rw-r-----. 1 root  ossec 9.2K Jan 25 11:40 ossec.conf-template
lrwxrwxrwx. 1 root  root    20 Jan 24 18:09 ossec-init.conf -> /etc/ossec-init.conf
lrwxrwxrwx. 1 root  root    21 Jan 25 11:40 rootcheck -> ../data/etc/rootcheck
drwxrwx---. 2 root  ossec 4.0K Jan 25 11:39 rootcheck-template
lrwxrwxrwx. 1 root  root    17 Jan 25 11:40 rules -> ../data/etc/rules
drwxrwx---. 2 root  ossec   29 Jan 25 11:39 rules-template
lrwxrwxrwx. 1 root  root    18 Jan 25 11:40 shared -> ../data/etc/shared
drwxrwx---. 3 root  ossec   63 Jan 25 11:40 shared-template
lrwxrwxrwx. 1 root  root    27 Jan 25 11:40 sslmanager.cert -> ../data/etc/sslmanager.cert
-rw-r-----. 1 root  root  1.2K Jan 25 11:40 sslmanager.cert-template
lrwxrwxrwx. 1 root  root    26 Jan 25 11:40 sslmanager.key -> ../data/etc/sslmanager.key
-rw-r-----. 1 root  root  1.7K Jan 25 11:40 sslmanager.key-template
-rw-rw-r--. 1 ossec root   22K Jan 25 11:12 wazuh-elastic6-template-alerts.json
root@wazuh:/# cat /var/ossec/etc/client.keys
001 TEMP any 064da5731e93b62f6a91480cd5a59b90bc605344ce7ccb5fd853e6dfeeac7c91

root@wazuh:/# exit
exit
[adminuser@el02 elk-master]$ docker stop wazuh
wazuh
[adminuser@el02 elk-master]$ docker rm wazuh
wazuh
[adminuser@el02 elk-master]$  docker-compose -f docker-compose-base.yml -f docker-compose-full.yml up -d
smtp-relay is up-to-date
minemeld is up-to-date
threatintelligence is up-to-date
geoip is up-to-date
es-data01 is up-to-date
logstash01 is up-to-date
kibana is up-to-date
curator is up-to-date
auditbeat is up-to-date
filebeat is up-to-date
elastalert is up-to-date
metricbeat is up-to-date
Creating wazuh ...
packetbeat is up-to-date
reporting is up-to-date
Creating wazuh ... done
[adminuser@el02 elk-master]$ docker exec -it wazuh /bin/bash
root@wazuh:/# cat /var/ossec/etc/client.keys
root@wazuh:/#
root@wazuh:/# ls -lh /var/ossec/etc/client.keys
lrwxrwxrwx. 1 root root 23 Jan 25 11:40 /var/ossec/etc/client.keys -> ../data/etc/client.keys
root@wazuh:/#
```

**Comment by rhysxevans** [comment]
My ossec.conf - related to auth looks like

```
  <auth>
    <disabled>no</disabled>
    <port>1515</port>
    <use_source_ip>no</use_source_ip>
    <force_insert>yes</force_insert>
    <force_time>28800</force_time>
    <purge>yes</purge>
    <use_password>yes</use_password>
    <limit_maxagents>yes</limit_maxagents>
    <ciphers>HIGH:!ADH:!EXP:!MD5:!RC4:!3DES:!CAMELLIA:@STRENGTH</ciphers>
    <!-- <ssl_agent_ca></ssl_agent_ca> -->
    <ssl_verify_host>no</ssl_verify_host>
    <ssl_manager_cert>/var/ossec/etc/sslmanager.cert</ssl_manager_cert>
    <ssl_manager_key>/var/ossec/etc/sslmanager.key</ssl_manager_key>
    <ssl_auto_negotiate>no</ssl_auto_negotiate>
  </auth>
```

I will update the dockerfile

**Comment by rhysxevans** [comment]
Ok, I haven't been able to solve this. I have put in a "work around" for now

I have added the following into my entrypoint.sh

```
exec_cmd_stdout "crontab /var/ossec/data/etc/crontab.txt"
```

the crontab.txt file looks like

```
*/5 * * * * /bin/bash /wazuh-backup.sh
10 4 * * 1 cd /var/ossec/bin && ./update_ruleset -r -d
```

So at least I will get a copy of the file that shouldn't be older than 5 mins

Thanks

**Comment by SitoRBJ** [comment]
Hello @rhysxevans,

We are glad you could find an alternative solution. Whenever possible we will investigate what may be happening. 

Thank you very much for your interest and collaboration. 

Best regards,

Alfonso Ruiz-Bravo
