### ISSUE TITLE
Docker Security scan (week 45)

### ISSUE THREAD

**Issue by vcerenu** [wazuh/wazuh-docker#1096]
### Description

The vulnerabilities list for Wazuh Docker images must be updated.

**Comment by gecube** [comment]
Hello!

Guys, could you give please any ideas on https://github.com/wazuh/wazuh-docker/issues/1084#issuecomment-1806182359 
Still no reply or reaction from your side and it begins to worry me

fyi @pytoshka

**Comment by vcerenu** [comment]
Hello @gecube

These issues reflect the weekly vulnerability control that we perform on the artifacts created for the installation of Wazuh, but they do not reflect the other tasks that we perform on them.

We appreciate the information and have added it to our reports to verify the vulnerabilities that we can manage for correction.

If you have any improvements that you want to implement, we encourage you to create an issue or PR with these changes, so that we can add them to our repositories.
