### ISSUE TITLE
Adapt process to install multiple Wazuh Dashboards plugins

### ISSUE THREAD

**Issue by asteriscos** [wazuh/wazuh-docker#1099]
# Description

In Wazuh Dashboards 4.8.0, the app needs to install 3 plugins to work, as they depend on each other:

- wazuh
- wazuh-check-updates
- wazuh-core

We need to analyze each step of the Wazuh Dashboard building/installation process in each of the repositories involved.

**Comment by davidcr01** [comment]
# Update Report

The packages are available in:
- https://packages-dev.wazuh.com/staging/ui/dashboard/wazuh-4.8.0-40800.zip
- https://packages-dev.wazuh.com/staging/ui/dashboard/wazuhCheckUpdates-4.8.0-40800.zip
- https://packages-dev.wazuh.com/staging/ui/dashboard/wazuhCore-4.8.0-40800.zip
