### ISSUE TITLE
Add de ability to use environment variables in Dockerfile

### ISSUE THREAD

**Issue by manuasir** [wazuh/wazuh-docker#114]
Hi team, it'd be needed to use environment variables within the Dockerfile, so we can build two different images from the same Dockerfile.

- [x] Research the functionality from the Docker side.
- [x] Test the solution by building different images from the same Dockerfile.

Cheers

**Comment by SitoRBJ** [comment]
Hello team,

The PR #117 solves this issue.

Best regards,

Alfonso Ruiz-Bravo
