### ISSUE TITLE
Update Configuration to New Vulnerability Detector and Indexer

### ISSUE THREAD

**Issue by Dwordcito** [wazuh/wazuh-docker#1150]
**Description:**

This issue focuses on updating the configuration settings for the vulnerability detector and indexer modules to align with the new templates. The old configuration for vulnerability detection will be removed, and the settings will be replaced with those described in the following templates:

- [Vulnerability Detector Configuration](https://github.com/wazuh/wazuh/blob/dev-14153-vulndet-refactor/etc/templates/config/generic/wodle-vulnerability-detection.manager.template)
- [Indexer Configuration](https://github.com/wazuh/wazuh/blob/dev-14153-vulndet-refactor/etc/templates/config/generic/wodle-indexer.manager.template)

**User Stories:**

- As a system administrator, I want the configuration to be up-to-date with the new vulnerability detection and indexing templates to ensure optimal functionality.
- As a developer, I want to remove the old configuration settings and replace them with the new templates to maintain consistency and improve maintainability.

**Tasks:**

1. Review New Configuration Templates:
   - Examine the provided vulnerability detector and indexer configuration templates thoroughly.

2. Identify Old Configuration Settings:
   - Identify the old configuration settings that need to be removed.

3. Replace Old Settings with New Templates:
   - Implement the new configuration settings from the provided templates.

**Definition of Done:**

- The old configuration settings have been removed.
- The new configuration settings from the provided templates have been implemented.

**Comment by teddytpc1** [comment]
## Analysis

The `vulnerability-detector` tag should be removed from:

https://github.com/wazuh/wazuh-docker/blob/86dd284368019490e8c00f19baabbf0c53eff286/multi-node/config/wazuh_cluster/wazuh_manager.conf#L98

https://github.com/wazuh/wazuh-docker/blob/86dd284368019490e8c00f19baabbf0c53eff286/multi-node/config/wazuh_cluster/wazuh_worker.conf#L98

https://github.com/wazuh/wazuh-docker/blob/86dd284368019490e8c00f19baabbf0c53eff286/single-node/config/wazuh_cluster/wazuh_manager.conf#L98

The new tags should be added to the same files replacing the old one.

**Comment by teddytpc1** [comment]
Changes were added to branch [540-vd-update](https://github.com/wazuh/wazuh-docker/tree/540-vd-update)
.

**Comment by vcerenu** [comment]
A test was carried out on updating the password of the admin user in the docker-compose.yml file

Status before update

```
# docker exec -it single-node_wazuh.manager_1 cat /var/ossec/etc/ossec.conf | grep "<password>"
    <password>SecretPassword</password>
```

Status after updating and rebuilding the container

```
# docker exec -it single-node_wazuh.manager_1 cat /var/ossec/etc/ossec.conf | grep "<password>"
    <password>SecretPassword123</password>
```
