### ISSUE TITLE
Review Wazuh docker permanent data exceptions for the AWS wodle

### ISSUE THREAD

**Issue by GGP1** [wazuh/wazuh-docker#1216]
## Description

In https://github.com/wazuh/wazuh/pull/17623 we refactored the AWS module and now it's composed of many more files. 

```
root@wazuh:/var/ossec/wodles/aws# tree /var/ossec/wodles/aws/
/var/ossec/wodles/aws/
|-- __init__.py
|-- aws-s3
|-- aws-s3.py
|-- aws_tools.py
|-- buckets_s3
|   |-- __init__.py
|   |-- aws_bucket.py
|   |-- cloudtrail.py
|   |-- config.py
|   |-- guardduty.py
|   |-- load_balancers.py
|   |-- server_access.py
|   |-- umbrella.py
|   |-- vpcflow.py
|   `-- waf.py
|-- s3_cloudtrail.db
|-- services
|   |-- __init__.py
|   |-- aws_service.py
|   |-- cloudwatchlogs.py
|   `-- inspector.py
|-- subscribers
|   |-- __init__.py
|   |-- s3_log_handler.py
|   |-- sqs_message_processor.py
|   `-- sqs_queue.py
`-- wazuh_integration.py
```

We have tried using a single-node wazuh-docker deployment in `4.8.0-beta1` and it seems that all files are present and that it works as expected.

However, the majority of these files are not present in the permanent data exceptions list, which contains the files from the previous architecture only.

https://github.com/wazuh/wazuh-docker/blob/db7596ca0308abeaab7cfb5bcbc088c9ca4071bb/build-docker-images/wazuh-manager/config/permanent_data.env#L54-L55

> It is likely that the only permanent file is `s3_cloudtrail.db`. 

We should review the data exceptions for the AWS module and apply the changes necessary to keep its functionality unchanged.

**Comment by vcerenu** [comment]
Can you confirm which files will need a persistence exception for the upgrade?

**Comment by GGP1** [comment]
@vcerenu Just `s3_cloudtrail.db` should to be persisted, all the other files should be included in the exception list.

**Comment by vcerenu** [comment]
The following files will be added, confirm @GGP1  please
``` console
/var/ossec/wodles/aws/__init__.py
/var/ossec/wodles/aws/aws_tools.py
/var/ossec/wodles/aws/wazuh_integration.py
/var/ossec/wodles/aws/buckets_s3/__init__.py
/var/ossec/wodles/aws/buckets_s3/aws_bucket.py
/var/ossec/wodles/aws/buckets_s3/cloudtrail.py
/var/ossec/wodles/aws/buckets_s3/config.py
/var/ossec/wodles/aws/buckets_s3/guardduty.py
/var/ossec/wodles/aws/buckets_s3/load_balancers.py
/var/ossec/wodles/aws/buckets_s3/server_access.py
/var/ossec/wodles/aws/buckets_s3/umbrella.py
/var/ossec/wodles/aws/buckets_s3/vpcflow.py
/var/ossec/wodles/aws/buckets_s3/waf.py
/var/ossec/wodles/aws/services/__init__.py
/var/ossec/wodles/aws/services/aws_service.py
/var/ossec/wodles/aws/services/cloudwatchlogs.py
/var/ossec/wodles/aws/services/inspector.py
/var/ossec/wodles/aws/subscribers/__init__.py
/var/ossec/wodles/aws/subscribers/s3_log_handler.py
/var/ossec/wodles/aws/subscribers/sqs_message_processor.py
/var/ossec/wodles/aws/subscribers/sqs_queue.py
```

**Comment by GGP1** [comment]
@vcerenu Looks good!
