### ISSUE TITLE
 Bind for 0.0.0.0:443 failed: port is already allocated

### ISSUE THREAD

**Issue by Neuropsihopuppu** [wazuh/wazuh-docker#1263]
is it possible to use any other ports then 443 because that port for me is alocated for something else that i need?

**Comment by davidcr01** [comment]
Hello.

To change the port of our Wazuh-docker you just have to modify the "docker-compose.yml" file that you will find in `wazuh-docker/single-node` or `wazuh-docker/multi-node`, depending on which one you want to use. Locate the configuration for "wazuh.dashboard" in that file and there you will find the "ports" section. Just replace port 443 with the port of your choice. Don't forget to restart the Docker deployment to apply the changes in case it was already running.
