### ISSUE TITLE
Double equality used within single square brackets in build script

### ISSUE THREAD

**Issue by bervel** [wazuh/wazuh-docker#1273]
I had to update the build script, replace double equality with single on line 57 to get it to run. Otherwise comparison of equal string variables containing the version "5.0.0" fails.

`if [ "${FILEBEAT_TEMPLATE_BRANCH}" == "${WAZUH_MASTER_VERSION}" ]; then'
changed to
'if [ "${FILEBEAT_TEMPLATE_BRANCH}" = "${WAZUH_MASTER_VERSION}" ]; then'

**Comment by davidcr01** [comment]
Hello.

In bash, `=` and `==` are synonyms. However, the `=` operator should be used with the `test` commando for POSIX compliance. Which shell are you using?

I tested this behavior in my machine and no difference was found:

The test, `test.sh` file:
```bash
set -x
FILEBEAT_TEMPLATE_BRANCH=5.0.0

WAZUH_MASTER_VERSION="$(curl -s https://raw.githubusercontent.com/wazuh/wazuh/master/src/VERSION | sed -e 's/v//g')"

echo "${WAZUH_MASTER_VERSION}"


if [ "${FILEBEAT_TEMPLATE_BRANCH}" = "${WAZUH_MASTER_VERSION}" ]; then
  echo "They're equal"
else
  echo "They're not equal"
fi
```

First execution, with `==` operator:
```console
$ bash test.sh
+ FILEBEAT_TEMPLATE_BRANCH=5.0.0
++ curl -s https://raw.githubusercontent.com/wazuh/wazuh/master/src/VERSION
++ sed -e s/v//g
+ WAZUH_MASTER_VERSION=5.0.0
+ echo 5.0.0
5.0.0
+ '[' 5.0.0 == 5.0.0 ']'
+ echo 'They'\''re equal'
They're equal
```

Second execution, with `=` operator:
```console
$ bash test.sh
+ FILEBEAT_TEMPLATE_BRANCH=5.0.0
++ curl -s https://raw.githubusercontent.com/wazuh/wazuh/master/src/VERSION
++ sed -e s/v//g
+ WAZUH_MASTER_VERSION=5.0.0
+ echo 5.0.0
5.0.0
+ '[' 5.0.0 = 5.0.0 ']'
+ echo 'They'\''re equal'
They're equal
```

Anyway, we will discuss this with the team and see if we need to change the operator or not.
Reference: https://www.gnu.org/software/bash/manual/html_node/Bash-Conditional-Expressions.html
