### ISSUE TITLE
Change Wazuh passwords processes

### ISSUE THREAD

**Issue by vcerenu** [wazuh/wazuh-docker#1313]
## Context

Several changes have been made to the Wazuh deployment process in Docker, among them is the elimination of mounting the `internal_users.yml` file, which was used in the process of changing the password of the admin and kibanaserver users.

It is necessary to rethink the process of changing the password in Wazuh indexer mainly, since the editing of the `internal_users.yml` file must be done at the beginning of the container because the file will not be mounted anymore and it should become part of a volume of Docker like data.

**Comment by davidjiglesias** [comment]
Based on upcoming changes for 5.0.0 we decide to close this for now
