### ISSUE TITLE
Docker deployment should work with Docker Compose 2.x

### ISSUE THREAD

**Issue by vcerenu** [wazuh/wazuh-docker#1314]
## Context

We have received issues from the community on many occasions with errors in the deployment of Wazuh in Docker using version 2.x of Docker Compose.

It is necessary to investigate what changes are necessary to adapt the current deployment process, compatible with `Docker Compose 1.x,` to be able to deploy without problems with `Docker Compose 2.x`.

**Comment by schneich** [comment]
Please allow me to jump in here. In the current version of the docker specification, there is no need to provide a version number at all - but you have to use `docker compose up`. (without the dash)

Reference:
- https://docs.docker.com/compose/compose-file/legacy-versions/
- https://docs.docker.com/compose/compose-file/04-version-and-name/

All your containers seem to start up properly with `docker compose up` - except the SSL-certificate-creation-container.

**Comment by schneich** [comment]
#https://github.com/wazuh/wazuh-docker/issues/1406

**Comment by davidjiglesias** [comment]
We are redesigning our Docker deployment in 5.0.0
