### ISSUE TITLE
Can't use netflow module

### ISSUE THREAD

**Issue by joseaguardia** [wazuh/wazuh-docker#1323]
Hi

I have mounted the single-node version of the 4.7.3 branch and everything is working fine, but when trying to get filebeat to receive data through netflow, it seems that the module is not in filebeat:

Exiting: Error getting filesets for module netflow: open /usr/share/filebeat/module/netflow: no such file or directory

filebeat.yml
![imagen](https://github.com/wazuh/wazuh-docker/assets/16305835/c655668e-0344-49ec-9693-7bd9dce3aaea)

Regards

**Comment by vcerenu** [comment]
Hello @joseaguardia

Netflow is not a module that is available in the version of Filebeat that we have installed in our Wazuh server image:
```
root@wazuh:/# filebeat modules list
Enabled:

Disabled:
Apache
auditd
elasticsearch
haproxy
icinga
iis
kafka
kibana
logstash
mongodb
mysql
nats
nginx
osquery
postgresql
redis
holy
system
bringfik
root@wazuh:/# 
```

What do you need to do? To see if we can help you with any other products we have.
