### ISSUE TITLE
Include top level name in docker-compose.yml

### ISSUE THREAD

**Issue by schneich** [wazuh/wazuh-docker#1406]
Dear wazuh docker team,

as adivsed by @rauldpm, I open up _feature request_ here. (-> https://github.com/wazuh/wazuh-documentation/issues/7444#issuecomment-2192219101)

I have recently created a custom compose.yml to run wazuh. I have had some difficulties with the naming, as some of the containers, networks and volumes had been named after the root folder, the compose.yml was sitting in. It would be nice, if you could include a [top level name](https://docs.docker.com/compose/compose-file/04-version-and-name/) in your yml example, so that _containers_, _volumes_ and _networks_ get a proper name.

Please find my example here: https://github.com/wazuh/wazuh-docker/discussions/1394#discussioncomment-9852100

**Result in Ubuntu CLI**
![grafik](https://github.com/wazuh/wazuh-docker/assets/84641760/251f8d5c-b8b0-42b0-adc4-2c938f357ca1)

**Result in Portainer**
![grafik](https://github.com/wazuh/wazuh-docker/assets/84641760/fd623f31-8feb-4717-9c22-73b47d348f0b)

![grafik](https://github.com/wazuh/wazuh-docker/assets/84641760/6a31d800-4a63-4313-89b7-c29745e42a89)

![grafik](https://github.com/wazuh/wazuh-docker/assets/84641760/71626072-7a83-48df-aff2-bab85985965e)

![grafik](https://github.com/wazuh/wazuh-docker/assets/84641760/3de5acd1-aaf0-4326-b244-e788568dc274)

Thank you for taking this into consideration,
Chris

**Comment by davidjiglesias** [comment]
We are going to execute big changes to our deployments (including docker) in 5.0.0 and therefore we won't be working on further enhancements here.
