### ISSUE TITLE
"Increase max_map_count on your host (Linux)" in readme

### ISSUE THREAD

**Issue by alberpilot** [wazuh/wazuh-docker#142]
Hello team

  It could be a good idea if we include the requirement described here: https://documentation.wazuh.com/current/docker/wazuh-container.html#increase-max-map-count-on-your-host-linux in README of this repository. 

Best regards, 
Alberto R.

**Comment by manuasir** [comment]
This change was incorporated into the `README.md` along with the latest `3.8.2_6.7.0` release. Thanks @alberpilot
