### ISSUE TITLE
Changing Indexer password failure in Docker Wazuh Multi-node Deployment

### ISSUE THREAD

**Issue by mjcr99** [wazuh/wazuh-docker#1477]
## Description

Hi team, while performing the E2E docker deployment test in https://github.com/wazuh/wazuh/issues/25017

I have found that changing only the indexer password let the dashboard inaccessible reporting the following error in the interface:

```
{
  "statusCode": 500,
  "error": "Internal Server Error",
  "message": "An internal server error occurred."
}
```

The exact followed steps to find this situation are reported in this comment https://github.com/wazuh/wazuh/issues/25017#issuecomment-2271491342

**Comment by c-bordon** [comment]
I performed a first test and was unable to reproduce the error. I will use the same passwords that the user used in the test.

Tests:

```console

**Comment by c-bordon** [comment]
## Update report

I was unable to reproduce the error. I tried a few variants to force the error but could not do it in the same way as in the test.

Following the steps indicated in the documentation, the password change worked correctly. What caught my attention in what was indicated in the test is that the password for the kibanaserver user was left at the default `kibanaserver`. I don't know if there was an error when configuring the passwords that generated the error indicated by the user.
