### ISSUE TITLE
Anomaly detection plugin enable in Wazuh docker installation

### ISSUE THREAD

**Issue by mvasuraja** [wazuh/wazuh-docker#1478]
Hello,

I have installed Wazuh Manager & Indexer on a server using Docker containers. My project requirement is to have Anomaly detection done on ingested data/ events. I need to enable the plugin for that. 
Can someone guide as to how this can be achieved? 

I have tried to go into the Wazuh Dashboard docker by using 
``
#sudo docker run -it <container ID> bash 
``
Here, I get this error ``getaddrinfo ENOTFOUND wazuh.indexer`` repeatedly, but Wazuh Indexer container is run separately as well.

Kindly help

Thanks & Regards,

**Comment by davidcr01** [comment]
Hello. I tried to reproduce you error with no success. A few things to consider here:
1. If you are trying to access a container, the command you specified is not correct. To access a container, use the `docker exec -it <CONTAINER_ID|CONTAINER_NAME> bash` command as reported in [this](https://documentation.wazuh.com/current/deployment-options/docker/wazuh-container.html#applying-the-changes) documentation.
2. If you want to install the Anomaly Detection plugin, I recommend you to follow [this](https://wazuh.com/blog/exploring-security-alerting-options-for-improved-threat-detection-in-wazuh-part-1/) documentation, specifically the `Anomaly Detection plugin installation` part. I assume that you are installing the latest Wazuh version (currently 4.8.1). If not, make sure that you are installing the correct OpenSearch version (the one that Wazuh dashboard is based on)
3. Do not use the `sudo` commands inside the container. Omit the `sudo -u wazuh-dashboard` part of the commands and follow the installation as explained.
4. You should be able to install the Anomaly Detection plugin:

![image](https://github.com/user-attachments/assets/fe4b30a6-ea51-44f5-a74b-b167befbc787)

Hope it helps.

**Comment by mvasuraja** [comment]
Dear @davidcr01

I am not sure what is the problem, maybe the container was restarted, or the server itself may have been restarted. 

I am getting the container up by running `docker compose up`, get the container number using `docker ps`. 
I am trying to redo the steps as indicated in your link, but unable to get the plugin. 

I have tried to bring the container down, and restart. Once the docker composer is brought down, I know the changes made inside the container are lost. But redoing the steps from scratch also achieves no results. 

Thanks & Regards,

**Comment by elwali10** [comment]
Hello @mvasuraja, 

I am just shimming in to share a Wazuh dashboard custom image that offers the anomaly detector https://hub.docker.com/r/elwali/wazuh-dashboard-anomaly-detector 

I hope it helps

**Comment by mvasuraja** [comment]
Hi @elwali10 

I have downloaded the docker image. I need some help integrating it with the current setup, since I am new to docker installations. 

Thanks, 

> Hello @mvasuraja,
> 
> I am just shimming in to share a Wazuh dashboard custom image that offers the anomaly detector https://hub.docker.com/r/elwali/wazuh-dashboard-anomaly-detector
> 
> I hope it helps

**Comment by mvasuraja** [comment]
Dear All, 

It was my mistake.. I had been bringing down the docker container instead of restarting it, and hence it was losing all the changes I had made (enabling the Anomaly Detection Plugin). 

Got the plugin listed. Apologies for the inconvenience caused due to my brain freeze. 

Thanks & Regards,

> Dear @davidcr01
> 
> I am not sure what is the problem, maybe the container was restarted, or the server itself may have been restarted.
> 
> I am getting the container up by running `docker compose up`, get the container number using `docker ps`. I am trying to redo the steps as indicated in your link, but unable to get the plugin.
> 
> I have tried to bring the container down, and restart. Once the docker composer is brought down, I know the changes made inside the container are lost. But redoing the steps from scratch also achieves no results.
> 
> Screenshot of running the command to list the plugins is given:
> 
> 
> But the plugin does not appear on the dashboard:
> 
>
> Need help please. Thanks & Regards,
