### ISSUE TITLE
Make port numbers and URL for Elasticsearch configurable in logstash container

### ISSUE THREAD

**Issue by megastef** [wazuh/wazuh-docker#154]
Hi, it looks there is no way to change Elasticsearch URL. The port number is fixed to 9200. 
See: https://github.com/wazuh/wazuh-docker/blob/master/logstash/config/entrypoint.sh#L53-L54

I would like to use -e LOGSTASH_OUTPUT=https://logsene-reciver.sematext.com:443 as Elasticsearch server for the logstash output to see the data in Sematext Cloud.

**Comment by manuasir** [comment]
Hello @megastef ,

I think this would be a good idea. We will evaluate if we should add a new variable for the port, or just having one for the full string. Please, share your thoughts on this.

Thanks

**Comment by manuasir** [comment]
Done here #164 . Thanks @megastef
