### ISSUE TITLE
Unable to Pull Wazuh Images and Run Wazuh in Single Node using Docker-Compose

### ISSUE THREAD

**Issue by ajutamangdev** [wazuh/wazuh-docker#1553]
I was attempting to deploy Wazuh in a single-node setup using Docker Compose locally in my machine but encountered errors while trying to pull and run the images.

```
[+] Running 3/3
 ✘ wazuh.manager Error   context canceled                                                                                     6.3s 
 ✘ wazuh.indexer Error   manifest for wazuh/wazuh-indexer:5.0.0 not found: manifest unknown: manifest...                      6.3s 
 ✘ wazuh.dashboard Error context canceled                                                                                     6.3s 
Error response from daemon: manifest for wazuh/wazuh-indexer:5.0.0 not found: manifest unknown: manifest unknown
```
> My Expectation was The Wazuh Manager, Indexer, and Dashboard should start successfully.

Additionally, when I tried to manually pull the Wazuh image using the following command.
```
docker pull wazuh/wazuh
```
I got the following errors
```
> docker pull wazuh/wazuh
Using default tag: latest
Error response from daemon: manifest for wazuh/wazuh:latest not found: manifest unknown: manifest unknown
```

I have verified that my internet connection is stable, and I can pull other images successfully. Is the wazuh/wazuh image tag deprecated or unavailable?

**Comment by seyfu-t** [comment]
I can pull, so your issue is probably unrelated, maybe a proxy issue?

**Comment by ajutamangdev** [comment]
I have tried from my github codespace as well. I couldn't able to run there as well. @seyfu-t

**Comment by PrideIsLife** [comment]
I also have the same issue @seyfu-t

**Comment by seyfu-t** [comment]
I think wazuh/wazuh doesn't exist. 
The project consists of multiple parts and if you take a look at the [compose file](https://github.com/wazuh/wazuh-docker/blob/master/single-node/docker-compose.yml) for single node containers, the images would be wazuh/wazuh-manager, wazuh/wazuh-dashboard and wazuh/wazuh-indexer respectively

**Comment by PrideIsLife** [comment]
I personally try to pull the correct images @seyfu-t : 
```
services:
  wazuh.manager:
    image: wazuh/wazuh-manager:5.0.0
...
  wazuh.indexer:
    image: wazuh/wazuh-indexer:5.0.0
...
  wazuh.dashboard:
    image: wazuh/wazuh-dashboard:5.0.0
```

```
WARN[0000] /home/paul/wazuh-docker/single-node/docker-compose.yml: `version` is obsolete
[+] Pulling 3/3
 ✘ wazuh.dashboard Error                                                                                                                                                                                                                               1.1s
 ✘ wazuh.indexer Error                                                                                                                                                                                                                                 1.1s
 ✘ wazuh.manager Error                                                                                                                                                                                                                                 1.1s
Error response from daemon: manifest for wazuh/wazuh-indexer:5.0.0 not found: manifest unknown: manifest unknown
```

**Comment by seyfu-t** [comment]
Hm...
try replacing version 5.0.0 with 4.9.0, this should work

**Comment by ajutamangdev** [comment]
```
[+] Running 3/3
 ✘ wazuh.manager Error   manifest for wazuh/wazuh-manager:5.0.0 not fo...                      3.9s 
 ✘ wazuh.indexer Error   context canceled                                                      3.9s 
 ✘ wazuh.dashboard Error context canceled                                                      3.9s 
Error response from daemon: manifest for wazuh/wazuh-manager:5.0.0 not found: manifest unknown: manifest unknown
```

Its already being defined out there. @seyfu-t

**Comment by seyfu-t** [comment]
Sorry I don't understand what you are trying to tell me
I meant you should try
```bash
docker pull wazuh/wazuh-manager:4.9.0
docker pull wazuh/wazuh-indexer:4.9.0
docker pull wazuh/wazuh-dashboard:4.9.0
```
Images with version 4.9.0, it seems like version 5.0.0 does not exist

**Comment by ajutamangdev** [comment]
This is true. I was able to pull up 4.9.0 Thanks a lot @seyfu-t 

Strange part is we can't able to pull oldest tag as well eg: 4.8.0

Its working for me on 4.9.0. 5.0.0 hasn't been released I confirmed this from the slack of wazuh, community subchannel.

**Comment by seyfu-t** [comment]
No Problem, maybe rename the issue title so that others will find this one easier?
