### ISSUE TITLE
Improving elasticsearch image: S3 configuration process

### ISSUE THREAD

**Issue by Phandora** [wazuh/wazuh-docker#156]
Hi team!

There is some environment variables we can remove without affecting the process of creating the repository in a S3 bucket.
```
ELASTICSEARCH_IP
ELASTICSEARCH_PORT
```
Also, the repository is configured as long as `ENABLE_CONFIGURE_S3` variable is not empty. That can be a problem because S3 repository would be created even if ENABLE_CONFIGURE_S3 = 'false'.

Best regards,
Mayte Ariza

**Comment by manuasir** [comment]
Closing since this doesn't apply to our new Docker version (v4.0)
