### ISSUE TITLE
Latest docker image 2.1.0_5.5.1 is broken

### ISSUE THREAD

**Issue by frots** [wazuh/wazuh-docker#16]
Probably upstream changes (the container is built from centos:latest) broke the wazuh-manager container. The _which_ binary which is a requirement for the wazuh-manager package installation is missing. Fixed in https://github.com/wazuh/wazuh-docker/pull/15. 

It is probably best to not build against centos:latest but use a specific version tag instead to avoid future breakage.

**Comment by jlruizmlg** [comment]
hi @frots i just tested with the last version and works nice for me, do you have screenshot with the error?

Anyway i will update today the containers to the last version from Elastic 5.5.2.

**Comment by jlruizmlg** [comment]
Hi @frots i just pushed the last kibana version 5.5.2 and seems works nice.

![screen shot 2017-08-24 at 2 57 38 pm](https://user-images.githubusercontent.com/13950509/29683581-df124110-88dc-11e7-9827-21e6817d659a.png)

**Comment by frots** [comment]
Hi @jlruizmlg, 

I see indeed the container with both 2.1.0_5.5.1 and 2.1.0_5.5.2 are working as expected. The installation error 
```
Installing : wazuh-manager-2.1.0-1.el7.x86_64                             1/2
 
./src/init/shared.sh: line 15: which: command not found
```
does not break the build. Customization on my side (mounting the auth folder as volume) probably does.

This can be closed, thanks.

**Comment by jlruizmlg** [comment]
@frots thanks a lot for your feedback!
