### ISSUE TITLE
Logs files left after building Wazuh image

### ISSUE THREAD

**Issue by Phandora** [wazuh/wazuh-docker#168]
Hi team!

It seems there are still some logs files left when Wazuh image is created:
```
root@wazuh:/var/ossec/logs/cluster/2019/May# ll 
total 12 
drwxr-x--- 2 ossec ossec 4096 May 10 13:52 ./
drwxr-x--- 3 ossec ossec 4096 May 10 13:52 ../
-rw-r----- 1 ossec ossec   35 May 10 13:52 cluster-06.log.gz
root@wazuh:/var/ossec/logs/cluster/2019/May# zcat cluster-06.log.gz 
root@wazuh:/var/ossec/logs/cluster/2019/May# 
```
The empty file `cluster-06.log.gz` should not exist. The environment was created after _May 6th_.

Best regards,
Mayte Ariza

**Comment by manuasir** [comment]
Hello @Phandora , as this is done here #169, I think we can close this issue.

Thanks!
