### ISSUE TITLE
Error reading cluster configuration after volume mount

### ISSUE THREAD

**Issue by 0x18katyan** [wazuh/wazuh-docker#173]
Hey, 
I posted an issue yesterday about persisting Wazuh data after container recreation. After having a brief reading of the documentation, I added a volume for location /var/ossec/data but after doing so I am getting another error :

> Settings. 3005 - Error reading cluster configuration

This is happeing when I try to navigate to the Wazuh App from Kibana which is listing my already configured API but is giving me the above error. Also, adding another API does not work as it also gives the error, while deleting the files in the mounted directory solves the problem but it quite defeats the purpose.
 
Here is my docker-compose configuration: 

` wazuh:
      image: wazuh:3.8.2-6.6.2
      hostname: wazuh-manager
      container_name: wazuh
      network_mode: "host"
      ports:
         - "1514:1514/udp"
         - "1515:1515"
         - "514:514/udp"
         - "55000:55000"
      volumes:
          - /var/log/backend/wazuh:/var/ossec/data
          - ./config/wazuh/config/filebeat.yml:/etc/filebeat/filebeat.yml
     depends_on:
        - logstash
        - elasticsearch
`

I am not using the whole docker-compose file as provided in this repo but only the Wazuh Dockerfile as it is. Also, while I am using ELK Stack 6.6.2, the filebeat inside the Wazuh image is using 6.5.4 version, can that be the possible culprit? 

Thanks in advance.
Regards,
Katyansun

**Comment by manuasir** [comment]
Hello @0x18katyan ,

I'll try to help here. Could you please attach here more information about this problem?
- docker-compose file that you used.
- steps that you followed for reproducing the same behavior.

Also I've checked the v3.8.2_6.6.2 tag and I noticed that the Filebeat version is correctly set as `6.6.2`

https://github.com/wazuh/wazuh-docker/blob/b47f723285086bb3e64de033c72ee7cdc70bf3aa/wazuh/Dockerfile#L3

I'll wait for your feedback.

Regards

**Comment by 0x18katyan** [comment]
Hey @manuasir, 

I solved the problem. I had used the same directory on the host machine for a volume mount in Logstash and a subdirectory of that for Wazuh like `/var/log/backend/` for Logstash and `/var/log/backend/wazuh/` for Wazuh. Undoing so solved the issue so I am closing this. I don't know why it happened but as far as I am concerned the issue has been solved. Thank you for your help.

Best Regards,
Katyansun

**Comment by 0x18katyan** [comment]
Also, for the clarification the Wazuh DockerFile in the repo is fine. I had been using the same DockerFile from versions ago so I had forgotten/neglected to update the Filebeat inside the DockerFile.

**Comment by manuasir** [comment]
@0x18katyan 

I'm glad the problem was solved! I've also noticed that you're an active user of our community, a fact that we appreciate a lot, so feel free to join our Slack community channel in order to learn more about Wazuh and keep the contact with the development team and other members of the community in a faster way.

Regards
