### ISSUE TITLE
Adjust the scan agent time

### ISSUE THREAD

**Issue by vncloudsco** [wazuh/wazuh-docker#174]
I see wazuh check the scan sequence every 1 hour. How can I adjust this time faster than I want it to take a few minutes to check once how can I do it?

![Screenshot_1](https://user-images.githubusercontent.com/41409442/57821396-904b7f00-77ba-11e9-92be-7381341c9764.png)

**Comment by manuasir** [comment]
Hello @vncloudsco ,

That behavior is due to the `interval` option of the `syscollector` wodle, it was set as its default value (1h). If you want the scans to be run, let's say, each minute, you have to edit to the following configuration:

```
  <!-- System inventory -->
  <wodle name="syscollector">
    <disabled>no</disabled>
    <interval>1m</interval>
    <scan_on_start>yes</scan_on_start>
    <hardware>yes</hardware>
    <os>yes</os>
    <network>yes</network>
    <packages>yes</packages>
    <ports all="no">yes</ports>
    <processes>yes</processes>
  </wodle>
```
Note that we have to include the unit: `<interval>`1**m**`</interval>`
After that, restart your manager:

```
/var/ossec/bin/ossec-control restart
```

You can see the logs in order to check if the scans are launched on the proper interval:

```
cat /var/ossec/logs/ossec.log | grep syscollector
```

```
2019/05/16 08:57:18 wazuh-modulesd:syscollector: INFO: Module finished.
2019/05/16 08:57:22 wazuh-modulesd:syscollector: INFO: Module started.
2019/05/16 08:57:23 wazuh-modulesd:syscollector: INFO: Starting evaluation.
2019/05/16 08:57:26 wazuh-modulesd:syscollector: INFO: Evaluation finished.
2019/05/16 08:58:23 wazuh-modulesd:syscollector: INFO: Starting evaluation.
2019/05/16 08:58:26 wazuh-modulesd:syscollector: INFO: Evaluation finished.
2019/05/16 08:59:23 wazuh-modulesd:syscollector: INFO: Starting evaluation.
2019/05/16 08:59:26 wazuh-modulesd:syscollector: INFO: Evaluation finished.
2019/05/16 09:00:23 wazuh-modulesd:syscollector: INFO: Starting evaluation.
2019/05/16 09:00:26 wazuh-modulesd:syscollector: INFO: Evaluation finished.
2019/05/16 09:01:23 wazuh-modulesd:syscollector: INFO: Starting evaluation.
```

If you look at the timestamps, you can check that the scans are effectively run each minute.

I hope that helps.

Regards

**Comment by vncloudsco** [comment]
I have adjusted the configuration however it did not run as expected

`cat /var/ossec/logs/ossec.log | grep syscollector`

`2019/05/17 03:18:52 wazuh-modulesd:syscollector: INFO: Evaluation finished.
2019/05/17 03:28:49 wazuh-modulesd:syscollector: INFO: Starting evaluation.
2019/05/17 03:28:52 wazuh-modulesd:syscollector: INFO: Evaluation finished.
2019/05/17 03:38:49 wazuh-modulesd:syscollector: INFO: Starting evaluation.
2019/05/17 03:38:52 wazuh-modulesd:syscollector: INFO: Evaluation finished.
2019/05/17 03:48:50 wazuh-modulesd:syscollector: INFO: Starting evaluation.
2019/05/17 03:48:52 wazuh-modulesd:syscollector: INFO: Evaluation finished.
2019/05/17 03:58:51 wazuh-modulesd:syscollector: INFO: Starting evaluation.
2019/05/17 03:58:53 wazuh-modulesd:syscollector: INFO: Evaluation finished.
2019/05/17 04:08:52 wazuh-modulesd:syscollector: INFO: Starting evaluation.
2019/05/17 04:08:54 wazuh-modulesd:syscollector: INFO: Evaluation finished.
2019/05/17 04:18:53 wazuh-modulesd:syscollector: INFO: Starting evaluation.
2019/05/17 04:18:56 wazuh-modulesd:syscollector: INFO: Evaluation finished.
2019/05/17 04:20:41 wazuh-modulesd:syscollector: INFO: Module finished.
2019/05/17 04:20:45 wazuh-modulesd:syscollector: INFO: Module started.
2019/05/17 04:20:46 wazuh-modulesd:syscollector: INFO: Starting evaluation.
2019/05/17 04:20:49 wazuh-modulesd:syscollector: INFO: Evaluation finished.
`


I found the cause by @Juan Carlos Tello
Just to make sure: You are editing this in the agent side, right?
If you are editing this on the manager's `/var/ossec/etc/ossec.conf` it will only affect the behavior of the manager's syscollector (the manager is itself an agent). However if you're interested in this information being collected more frequently on a specific agent you must edit that agent's `ossec.conf`, or you may use the Centralized Configuration capability to push this configuration to all agents within groups, including the default group by editing the `/var/ossec/etc/shared/[groupname]/agent.conf` file 



After re-adjusting the software agent has run my intention.  Thank you for helping me

**Comment by manuasir** [comment]
Hello @vncloudsco ,

I'm glad you were able to resolve this issue. Don't hesitate to open a new issue if you need it.

Regards
