### ISSUE TITLE
如何替换Wazuh-Elasticsearch ?

### ISSUE THREAD

**Issue by baoroushi** [wazuh/wazuh-docker#182]
您好，请问如何替换Wazuh-Elasticsearch 为现有的elasticsearch集群，可以实现吗？

非常感谢您！

**Comment by manuasir** [comment]
Hello @baoroushi,

If the translator made its work correctly and I understand you well, what you want is to not to use the Wazuh Elasticsearch/Logstash/Kibana images and use your own Elastic stack instance instead.
If so, it should be enough to add the following environment variable to the Wazuh image so Filebeat can reach your custom Logstash instance. This is an example could be an example for that:

```
    environment:
      - LOGSTASH_OUTPUT=https://yourlogstashurl.domain
```

Let me know if that helps,

Regards

**Comment by baoroushi** [comment]
what I mean is I want use your 'docker-compose.yaml' to deploy but using my Elasticsearch cluster to replace yours

**Comment by baoroushi** [comment]
@manuasir   what I mean is I want use your 'docker-compose.yaml' to deploy but using my Elasticsearch cluster to replace yours

**Comment by manuasir** [comment]
Hi @baoroushi ,

Alright, so you should follow these steps:

1. Remove the Elasticsearch and Logstash blocks from the `docker-compose.yml`
2. Set the following environment variables to the Wazuh block:

```
environment:
   - FILEBEAT_OUTPUT=https://yourlogstashurl.domain
```
_Where the URL is your complete Logstash  URL_

3. Set the following environment variables to the Kibana block:

```
environment:
   - ELASTICSEARCH_KIBANA_IP=https://yourelasticsearchurl.domain
   - ELASTICSEARCH_KIBANA_IP=https://yourelasticsearchurl.domain
```
_Where the URL is your complete Elasticsearch  URL_

Then, just start the environment up:

```
docker-compose up -d
```

Let me know if that helps. 

Regards

**Comment by manuasir** [comment]
Hi @baoroushi ,

Was that helpful for your case? Let me know if you still face issues.

Regards

**Comment by manuasir** [comment]
Hello @baoroushi ,

This issue is going to be closed due to inactivity. Don't hesitate to open a new one if you need it.

Regards
