### ISSUE TITLE
3.9.x_7.x Docker compose still include Logstash dependencies

### ISSUE THREAD

**Issue by migruiz4** [wazuh/wazuh-docker#191]
Hi team, 

Docker_compose.yml for versions 3.9.x_7.x still include dependencies to Logstash container, even has a reference to an image `wazuh-logstash-3.9.2_7.1.1` that doesn't exist.

https://github.com/wazuh/wazuh-docker/blob/ad4084a8dab98165cddf4250e770dadae3e9edcd/docker-compose.yml#L14-L27

Best regards,
Miguel

**Comment by manuasir** [comment]
Thanks @migruiz4 for reporting this, I'll commit and merge the fix ASAP.

Cheers

**Comment by manuasir** [comment]
Done here #192
