### ISSUE TITLE
Wazuh-docker reinserts cluster settings after resuming containers.

### ISSUE THREAD

**Issue by jm404** [wazuh/wazuh-docker#195]
Hi team,

On Elasticsearch >= 7.0, when resuming Docker containers, Elasticsearch service restarts and  triggers the execution of `config_cluster.sh`:

https://github.com/wazuh/wazuh-docker/blob/3aff6de0d08460d5015325e8322bca28751be39f/elasticsearch/config/config_cluster.sh#L8-L37

Which reinserts the configuration parameters generating a wrong `elasticsearch.yml` file that leads to errors due to duplicated fields like: 

`JsonParseException[Duplicate field 'cluster.initial_master_nodes'`]

Best regards,

Jose

**Comment by manuasir** [comment]
Done here #213
