### ISSUE TITLE
Release 3.9.3_7.1.1-opendistro

### ISSUE THREAD

**Issue by manuasir** [wazuh/wazuh-docker#199]
Wazuh version: 3.9.3
Elastic version: 7.1.1

Opendistro images

- [x] Adapt to new versions (3.9.3 - 7.1.1)
- [x] Update changelog
- [x] Tests
- [x] Tag: v3.9.3_7.1.1
- [x] Draft release
- [x] Update Documentation

**Comment by jm404** [comment]
Done! Check [v3.9.3_7.1.1-opendistro](https://github.com/wazuh/wazuh-docker/tree/v3.9.3_7.1.1-opendistro)

Best regards!

Jose
