### ISSUE TITLE
Kibana image won't build since 7.2.0

### ISSUE THREAD

**Issue by manuasir** [wazuh/wazuh-docker#217]
Hello team,

We've noticed that the Kibana Docker image won't build since several changes were introduced along with the `7.2.0` version,as it's being discussed [in this Elastic thread](https://discuss.elastic.co/t/7-2-0-kubernetes-why-trying-to-start-as-root/190457).
Now, if our current Kibana images are built using `7.2.0`, the following error will appear:
```
---> Running in ee7913505763
Kibana should not be run as root. Use --allow-root to continue.
Removing intermediate container ee7913505763
```
So the built breaks at that point. The tasks to avoid this would be:

- [x] Add the `--allow-root` flag to the plugin installation.
- [x] Rebuild the image.

Regards

**Comment by manuasir** [comment]
Done here #218

**Comment by betogls1** [comment]
adding --allow-root flag to the dockerfile base and rebuilding the image worked excellent. Thanks.
