### ISSUE TITLE
Create Wazuh container suite for Elastic Stack OSS

### ISSUE THREAD

**Issue by havidarou** [wazuh/wazuh-docker#219]
Hello team,

this task will involve creating/modifying the different Wazuh containers to use OSS versions of the Elastic Stack.
We already have a Kibana OSS container; the remaining ones would be:

- Elasticsearch OSS.
- Wazuh manager (because of Filebeat OSS).

Regards.

**Comment by manuasir** [comment]
Hello Wazuhers,

I just wanted to follow up on this after starting the work. The first thing that I approached was simply to change the official Elastic Docker images to the `oss`:

```
FROM docker.elastic.co/kibana/kibana-oss:7.2.0
```
This procedure applies to the `Filebeat`, `Kibana` and `Elasticsearch` Docker images.
Also, it was necessary to completely remove every `xpack` occurrence. So after this, we have to test these new images and once the tests pass, we will start to maintain a new `oss` branch.

Don't hesitate to share your thoughts on here, any feedback is much appreciated.

Cheers

**Comment by manuasir** [comment]
Done here #220
