### ISSUE TITLE
Integration files should not have write permissions for group and other

### ISSUE THREAD

**Issue by Phandora** [wazuh/wazuh-docker#225]
Hi team!

After performing some updates in an environment using `custom-jira-integration` and `virustotal` integrations, I've realized that files inside `/var/ossec/integrations` **should not have write permissions** for _groups and other_.

These are the errors I got:

```
2019/08/20 07:50:16 ossec-integratord: ERROR: At wpopenv(): file '/var/ossec/integrations/custom-jira' has write permissions.
```
```
2019/08/20 07:50:16 ossec-integratord: ERROR: At wpopenv(): file '/var/ossec/integrations/virustotal' has write permissions.
```
We should **remove write permissions** in `/var/ossec/integrations` for group and other after granting `g+rw` permissions for `/var/ossec/" path.

Best regards,
Mayte Ariza

**Comment by jesuslinares** [comment]
Thanks!
