### ISSUE TITLE
Consider implementing the functionality to allow users backup their configuration files.

### ISSUE THREAD

**Issue by jm404** [wazuh/wazuh-docker#228]
Hi team,

It might be a good idea to develop the required Docker files and scripts to allow users to backup their configuration files:

- [ ] Elasticsearch.yml

- [ ] Kibana.yml

- [ ] Filebeat.yml

- [ ] Any other data (like ES alerts, Wazuh logs, etc...)

This way if the container dies, no data and configuration are lost. Starting a new docker container and mounting the volume would restore everything. This implementation presents many challenges but a basic backup could be useful for users.

Best regards,

Jose

**Comment by arunasp** [comment]
The experimental commit is on my fork with separating configuration and data - https://github.com/arunasp/wazuh-docker/commit/7311521f1ad2d508aa39bfcc45230a3d7dab7293
