### ISSUE TITLE
Wazuh manager: is chmod -R g+rw ${DATA_PATH} necessary?

### ISSUE THREAD

**Issue by JPLachance** [wazuh/wazuh-docker#230]
Hello,

The Wazuh manager container has been running for a couple of months in my environment and now, if I kill the container and try to start it again, it hangs at the line `chmod -R g+rw ${DATA_PATH}`.

See https://github.com/wazuh/wazuh-docker/blob/master/wazuh/config/00-wazuh.sh#L110.

That line is changing every file ever created in `/var/ossec/data/` and it takes for ever.

How can we improve the entrypoint script to avoid that command? 🙂 

Thanks for the help!

**Comment by JPLachance** [comment]
Hello again,

I did a test, and it appears we could avoid calling `chmod -R g+rw ${DATA_PATH}` when it's not the first installation by adding a simple `if`:
```
if [[ ${FIRST_TIME_INSTALLATION} == true ]]
then
  chmod -R g+rw ${DATA_PATH}
fi
```

I tested it, it seems fine.

Can someone confirm? 😄 

Thanks!

**Comment by patakijv** [comment]
If that won't work for some reason it need to be each time, you may also be able to speed it up by using `find` and a condition test for when the files/folders are not in the permissions state you want, then execute the `chmod` only on those that pass the negative test.

**Comment by jm404** [comment]
Hi @JPLachance, @patakijv,

I see your point, that `chmod` could take long time if the `/var/ossec/data` contains info for a significant period of time.

We have significant improvements for volumes that we hope to release soon. Also, we'll test the solution you provided @JPLachance and update here as soon as posible

Thanks for contributing!

Best regards

Jose

**Comment by xr09** [comment]
Closing this issue since no longer applies to the current rework of the image.

The former (anonymous) volume `/var/ossec/data` is not used anymore on the new image, now we'll mount several named volumes and there's no need to copy (and chmod) files.

```
    volumes:
      - ossec_api_configuration:/var/ossec/api/configuration
      - ossec_etc:/var/ossec/etc
      - ossec_logs:/var/ossec/logs
      - ossec_queue:/var/ossec/queue
      - ossec_var_multigroups:/var/ossec/var/multigroups
      - ossec_integrations:/var/ossec/integrations
      - ossec_active_response:/var/ossec/active-response/bin
      - ossec_wodles:/var/ossec/wodles
      - filebeat_etc:/etc/filebeat_etc
      - filebeat_var:/var/lib/filebeat
```

The change to this new persistence method was made here:  https://github.com/wazuh/wazuh-docker/commit/a41da9d6ea1ae74c826f7f180491f49c6b2ad678
