### ISSUE TITLE
New volume '/var/ossec/wodles' for Wazuh image

### ISSUE THREAD

**Issue by Phandora** [wazuh/wazuh-docker#234]
Hi team!!

 It would be really convenient to declare a **new volume: /var/ossec/wodles** in the `Wazuh Dockerfile` in order to preserve users data. 

We must take into account that some of the files contained in that folder, such as `binaries`, **should not be permanent**:

- /var/ossec/wodles/aws/aws-s3
- /var/ossec/wodles/aws/aws-s3.py
- /var/ossec/wodles/azure/azure-logs
- /var/ossec/wodles/azure/azure-logs.py
- /var/ossec/wodles/docker/DockerListener
- /var/ossec/wodles/docker/DockerListener.py
- /var/ossec/wodles/oscap/oscap
- /var/ossec/wodles/oscap/oscap.py
- /var/ossec/wodles/oscap/template_oval.xsl
- /var/ossec/wodles/oscap/template_xccdf.xsl
- /var/ossec/wodles/oscap/content/cve-debian-8-oval.xml
- /var/ossec/wodles/oscap/content/cve-debian-9-oval.xml
- /var/ossec/wodles/oscap/content/cve-ubuntu-xenial-oval.xml
- /var/ossec/wodles/oscap/content/ssg-debian-8-ds.xml
- /var/ossec/wodles/oscap/content/ssg-ubuntu-1404-ds.xml
- /var/ossec/wodles/oscap/content/ssg-ubuntu-1604-ds.xml

However, we must find out if users can modify the base contents of the path `/var/ossec/wodles/oscap/content` in order not to lose the user's data.

Best regards,
Mayte Ariza

**Comment by arunasp** [comment]
@Phandora it is not only specific directory need persistance. In my configutation I have:
  wazuh:
    volumes:
      - /data/wazuh/backup/:/var/ossec/backup
      - /data/wazuh/data/:/var/ossec/data
      - /data/wazuh/queue/:/var/ossec/queue
      - /data/wazuh/ruleset/:/var/ossec/ruleset
      - /data/wazuh/stats/:/var/ossec/stats
      - /data/wazuh/var/db:/var/ossec/var/db
      - /data/wazuh/var/download:/var/ossec/var/download
      - /data/wazuh/var/upgrade:/var/ossec/var/upgrade
      - /data/wazuh/filebeat/modules/wazuh:/usr/share/filebeat/module/wazuh

  elasticsearch:
    volumes:
      - /data/elasticsearch/config:/usr/share/elasticsearch/config
      - /data/elasticsearch/data:/usr/share/elasticsearch/data
      - /data/elasticsearch/logs:/usr/share/elasticsearch/logs

Where /data is mounted external storage device with uid=1000,gid=1000.
Hopefully that helps.
