### ISSUE TITLE
Wazuh 3.9.5 / Agent shows both registration and lastkeepalive dates in the future.

### ISSUE THREAD

**Issue by narayaar** [wazuh/wazuh-docker#235]
Hello Team:  In my org, we are currently evaluating Wazuh, as a HIDS solution, and have accordingly, rolled out the Wazuh subsystem.  Please find the specs below;

Wazuh Mgr/API Server (containerized):  3.9.5
ElasticSearch:  7.3.0 (external / Rancher 2.2 with Kubernetes / default image from elastic.co)
Wazuh-Kibana:  3.9.5_7.3.0 (external / Rancher 2.2 with Kubernetes / image created from branch 3.9.5_7.3.0)
OS/Version:  CentOS/7.6

When integrating the agents, it has been identified that both the registration and lastkeepalive dates are in the future (around 6 hours), when viewed by the Wazuh-Kibana App.  The agents run on systems that are not locked to a particular TZ, but this should affect how both fields mentioned above.

It looks like https://github.com/wazuh/wazuh/issues/3511 had addressed this issue, but I did not see mention of a fix (my apologies I missed it).

Could you please let me know what is needed from my side, to help resolve this?

Thanks,
Arun

**Comment by jm404** [comment]
Hi @narayarar,

As you stated, there is a problem related to timestamp and timezones when showing the registration time and the last keep alive time, you can find detailed info on https://github.com/wazuh/wazuh/issues/3784.

There are several changes to fix this https://github.com/wazuh/wazuh/pull/3851/files so my recommendation is to wait for `3.10` version which will come out with bunch of features and fixes.

Let me mention our [Slack channel](https://wazuh.com/community/join-us-on-slack/)  where you can get the last updates and sharing your thoughs / questions will be really appreciated!

Best regards

Jose

**Comment by narayaar** [comment]
Hello Jose:  Thank you for getting back so quickly.

I do see that branch "3.10_7.3.0" is out there, but from your reply, the inference is that the issue is still ongoing.  Would you be in a position to let me know when 3.10 is proposed to be GA?

Also, my apologies for bringing another issue up under this one, but there are ES-related errors cropping up when drilling down the charts in the Wazuh-Kibana dashboard, especially when the absolute timeframe range is the same, or at best, differs by one second.

**_Error: Request to Elasticsearch failed: {"error":{"root_cause":[{"type":"parse_exception","reason":"failed to parse date field [-764144999980] with format [epoch_millis]: [failed to parse date field [-764144999980] with format [epoch_millis]]"}],"type":"search_phase_execution_exception","reason":"all shards failed","phase":"query","grouped":true,"failed_shards":[{"shard":0,"index":"wazuh-alerts-3.x-2019.08.29","node":"yBz6_FPfQWG-4JJx8ODFiQ","reason":{"type":"parse_exception","reason":"failed to parse date field [-764144999980] with format [epoch_millis]: [failed to parse date field [-764144999980] with format [epoch_millis]]","caused_by":{"type":"illegal_argument_exception","reason":"failed to parse date field [-764144999980] with format [epoch_millis]","caused_by":{"type":"date_time_parse_exception","reason":"Failed to parse with all enclosed parsers"}}}}]},"status":400}
    at https://waz-kib-db-url/bundles/commons.bundle.js:3:2897959
    at Function.Promise.try (https://waz-kib-db-url/bundles/commons.bundle.js:3:1979527)
    at https://waz-kib-db-url/bundles/commons.bundle.js:3:1978888
    at Array.map (<anonymous>)
    at Function.Promise.map (https://waz-kib-db-url/bundles/commons.bundle.js:3:1978843)
    at callResponseHandlers (https://waz-kib-db-url/bundles/commons.bundle.js:3:2896971)
    at https://waz-kib-db-url/bundles/commons.bundle.js:3:2879740
    at processQueue (https://waz-kib-db-url/built_assets/dlls/vendors.bundle.dll.js:499:199747)
    at https://waz-kib-db-url/built_assets/dlls/vendors.bundle.dll.js:499:200710
    at Scope.$digest (https://waz-kib-db-url/built_assets/dlls/vendors.bundle.dll.js:499:210518)_** 

Is this another issue that needs to be tagged to the 3.10 release, or would you be able to help me here?

Also, if you would like, we can continue to conversation on the slack channel.

Thanks,
Arun

**Comment by jm404** [comment]
Hi @narayaar,

As discussed in Slack, it seems to be an error related to https://github.com/elastic/elasticsearch/issues/42071

We will investigate if there is something from our side which cause this and if there is a solution we can apply

Best regards,

Jose

**Comment by narayaar** [comment]
Hello @jm404:  I wanted to let you know that I rolled out 3.10.0_7.3.1, and find that the registration/keepalive date/time of the agents has been fixed.

There is still the issue of the ES not being able to translate negative scientific date/time formats, but I can work around it, for now.

Thanks for all your time/help.

Thanks,
Arun

**Comment by jm404** [comment]
Hi @narayaar , 

Glad to hear it's working! Hope ES fixes the date/time formats translation soon...

Best regards,

Jose
