### ISSUE TITLE
Does not work on Windows 10 pro with Docker Desktop 2.1.0.3

### ISSUE THREAD

**Issue by MachLearnPort** [wazuh/wazuh-docker#242]
I have tested it on my Mac and its running like a pro, but I would also like to dev with it on my desktop (Windows 10 Pro). However, I am running into 403 errors (Docker Desktop - 2.1.0.3). 

Can someone verify that they are able to get it to run on a similar setup?

**Comment by manuasir** [comment]
Hello @MachLearnPort ,

Can you please paste the output so we can see those error messages? We will try to replicate this and will get back to you. Sorry for the inconvenience.

Regards

**Comment by manuasir** [comment]
Hey @MachLearnPort ,

This issue will be closed due to inactivity. Please don't hesitate to open a new ticket if you need it.

Regards
