### ISSUE TITLE
Installation fails behind Proxy

### ISSUE THREAD

**Issue by FloThinksPi** [wazuh/wazuh-docker#25]
When installing behind a Cooperate Proxy, Kibana cant download the Webapp even with http_proxy set via:

```
environment:
    - http_proxy= ...
    - https_proxy= ...
```

It produces following Error
```
Elastic is up - executing command
Attempting to transfer from https://packages.wazuh.com/wazuhapp/wazuhapp-2.1.0_5.5.2.zip
Error: Client request error: connect ETIMEDOUT 13.32.14.7:443
Plugin installation was unsuccessful due to error "Client request error: connect
```
How am i suppost to get past this ? 
Does the http_proxy env variable get honored ?

Best Regards
Florian

**Comment by jlruizmlg** [comment]
Hi @FloThinksPi are you using directly docker-compose up? or are you building the image?

Quote the following article:
https://docs.docker.com/compose/env-file/


> Note: If your service specifies a build option, variables defined in environment will not be automatically visible during the build. Use the args sub-option of build to define build-time environment variables.

Did you try to download the app and install locally?

https://github.com/wazuh/wazuh-docker/blob/master/docker-compose.yml#L66

Also can you try to export externally, following the next link?

https://crondev.com/running-docker-behind-proxy/

**Comment by FloThinksPi** [comment]
Hey thanks for the quick response :) . I am using straight `docker-compose up`.
I will try your recomendations , thank you.

**Comment by FloThinksPi** [comment]
@jlruizmlg  Tank you for your response. The tip with the local installation worked perfectly.
I made a simple Webserver on the Docker Host via ``python -m SimpleHTTPServer 9090 &`` and put that URL in the docker-compose.yml
