### ISSUE TITLE
Wazuh 3.10.0 / On Manager Stop/Start, ossec-remoted (local to the manager) spews multiple warnings

### ISSUE THREAD

**Issue by narayaar** [wazuh/wazuh-docker#254]
|Wazuh version|Component|Install type|Install method|Platform|
| 3.10.0 | Wazuh Manager | N/A | Docker | CentOS 7.6 |

Hello Team:  Whenever the Wazuh Manager container is stopped/started, the ossec-remoted process (on the manager) spuriously spews the following warnings (with differing "from" IPs);

ossec-remoted: WARNING: (1213): Message from '172.20.0.1' not allowed. Cannot find the ID of the agent. Source agent ID is unknown.

It is understandable considering the 172.17/16 subnet is managed by interface docker0 and then assigned to the containers that are spawned off of it, so have a fixed IP per container is not suggested/manageable. 

Please confirm if there is a way to get eliminate these warnings.

Thanks,
Arun

**Comment by jm404** [comment]
Hi @narayaar,

As discussed in Slack, this error happens because the IP of the Agent changed after restarting the Docker that contains it.

By default, Wazuh Manager when an Agent registers, the Manager saves info about it, including the source IP. Every time the Agent connects to the Manager, it validates the IP which, if changed, will trigger the Warning you posted.

To avoid this, either configure the network in Docker to set static IP for your Docker container in the docker-compose or disable the `use_source_ip` setting in the `ossec.conf` file.

**Security note:** Disabling the `use_source_ip` will make the Manager not check the source IP from the Agent, this will make the connection more vulnerable.

Best regards,

Jose

**Comment by apigban** [comment]
I've followed this from the slack channel.

I have the `<use_source_ip>no</use_source_ip>' config in my configuration but I also get the `message not allowed` log.

Initially (use_source_ip=**yes**), wazuh-manager wouldt trust the docker-proxy (_172.18.0.1_), when I changed to (use_source_ip=**no**) it doesn't trust the loadbalancer (_172.18.0.8_) now, I am using an nginx loadbalancer in front of the wazuh workers.

**Comment by narayaar** [comment]
Hello @apigban:  Have you made any progress on your predicament?

Hello @jm404:  ossec-remoted still continues to spew the messages, irrespective of the option provided.

I found that IPs can be denied when specified under stanza <remote></remote>, but they do not seem to be picked up by ossec-remoted.

https://documentation.wazuh.com/3.10/user-manual/reference/ossec-conf/remote.html

Thanks,
Arun

**Comment by apigban** [comment]
@narayaar arun, no progress at the moment, I've decided to manually re deploy all agents next week, so I'm hoping to see some solution to this before that :D. Also I think I need to get the IT dept some config management to avoid this in the future.

**Comment by jm404** [comment]
Hi @narayaar, @apigban,

In the remote link stated in https://github.com/wazuh/wazuh-docker/issues/254#issuecomment-536957304 you can see there's a filed named `allowed-ips`, you can configure  `remote` like:
```
<remote>
  <connection>secure</connection>
  <port>1514</port>
  <protocol>tcp</protocol>
  <allowed-ips>10.0.0.0/24</allowed-ips>
  <local_ip>10.0.0.1</local_ip>
</remote>
```

This way, the manager will accept logs from stated IP's and also define itself with the `local_ip`.

**Note:** I have not tested it yet, will update as soon as possible with the results but though you could find it useful.

Best regards,

Jose

**Comment by narayaar** [comment]
Hello @jm404:  It has been identified that these warnings can be excluded from being looked up by Wazuh by tweaking the docker configuration on the container host.

I am therefore closing this ticket.  Thanks for all your help thus far.

Thanks,
Arun

**Comment by jm404** [comment]
Hi @narayaar,

Glad to hear you managed to fix it. I'm curious about which configuration did you tweak to get it working, let me ask you for sharing this if you don't have any inconveniences. I think this could save other users from going into the same problem.

Thanks for your feedback, it's really appreciated!

Best regards,

Jose
