### ISSUE TITLE
Update to OSS v7.5.1

### ISSUE THREAD

**Issue by manuasir** [wazuh/wazuh-docker#258]
Hi team,

The `OSS` images should be updated to `v7.5.1`

- [x] Update `kibana-oss` image.
- [x] Update `elasticsearch-oss` image.
- [x] Update `filebeat-oss` image.

**Comment by xr09** [comment]
This is ready. It was created a branch with versions `3.11.2_7.5.1` using the oss variants of Elastic images and omitting XPack features.

https://github.com/wazuh/wazuh-docker/tree/3.11.2_7.5.1-oss
