### ISSUE TITLE
add "--insecure" option for curl in kibana entrypoint script

### ISSUE THREAD

**Issue by rmalchow** [wazuh/wazuh-docker#267]
in entrypoint.sh, all the curl calls expect (by default) elasticsearch as:

   http://elasticsearch:9200

this doesnt play nice with opendistro, which in many cases requires HTTPS by default (although in the wazuh-es image, this is not the case).

it would be nice to be able to add "--insecure" to the curl call used in the entrypoint. also, but this is just for added niceness, it might be great to somehow check for connectivity separate from the curl call, and possibly point out HTTP / HTTPS issues?

**Comment by jm404** [comment]
Hi @rmalchow,

Currently, we don't support HTTPS but as you stated it's a must for Opendistro and for users that need to enable that protocol.

We are working in a big refactor of our Docker images that will make users able to easily configure their Docker deploys, including X-Pack and HTTPS.

Thanks for your feedback, it's really appreciated.

Best regards,

Jose
