### ISSUE TITLE
Registering agents in a Wazuh manager deployed through Docker

### ISSUE THREAD

**Issue by delisyd** [wazuh/wazuh-docker#270]
Hello guys,

We have an enviroment in which we can't use port forwarding from host to the docker instances. 
Reading the official documentation i figured out that one requirement when setting up the instance is configure the ports forwarding because the agents needs to connect to the host IP which have the container.
Is there any way to avoid this configuration? I mean, may i configure the agents to directly point to  the manager IP instance (docker)?

Regards!

**Comment by jm404** [comment]
HI @delisyd,

If you need to avoid the traffic forwarding you can configure the containers to use the `host` mode (detailed info at [Docker Host networking](https://docs.docker.com/network/host/)) 

You can configure your containers to use host networking in your `docker-compose.yml` by adding the following at the end of the file:

```
 networks:
   host:
     driver: host
```

Hope it helps,

Best regards,

Jose

**Comment by manuasir** [comment]
This ticket will be closed due to inactivity. Please, open a new one if you need it.
