### ISSUE TITLE
Rework all Docker images

### ISSUE THREAD

**Issue by manuasir** [wazuh/wazuh-docker#272]
Hi team,

This task is for research purposes, also this will be used for tracking so this can be a huge task. This is about a full rework of every Docker image that we currently support.

### Motivation

Currently, the Wazuh image is a bunch of services with many dependencies, this results in a heavy image with services that are not always demanded. We have to investigate how we can get a clean image that satisfies the requirements of anyone. Maybe this will involve actions like splitting services into new images.
Additionally to that, regarding the `wazuh-kibana`, `wazuh-nginx` and `wazuh-elasticsearch` images, the main idea of this is to determine whether third party images we are forced to keep maintaining. 

### Actions

It will be needed to analyze, research and implement actions for getting the following tasks:

- [x] #273 Wazuh image
- [x] #295 NGINX image
- [x] #329 Elasticsearch
- [x] #330 Kibana

Notice that this issue will be actively updated. Also please, don't hesitate to share your thoughts/ideas on this.

Cheers

**Comment by ZEROF** [comment]
Hi,

We spoke on slack, and I would to give a few propositions:

1. Add more information to docker documentations like commands that most new user will need after installation, like updating rule sets and setting new agents:

```
docker exec -it wazuhcontainerid /var/ossec/bin/update_ruleset
docker exec -it wazuhcontainerid /var/ossec/bin/manage_agents
```
2. Add more information about docker-compose env variables, like using  

```
    environment:
      - WAZUH_MANAGER_IP=x.x.x.x
```

2. Add GeoIP and world map Kibana option, like that users can see source of attacks 

![image](https://user-images.githubusercontent.com/2687905/75882273-1eaff080-5e21-11ea-984f-d44424404088.png)

My 2 cents ;)

**Comment by manuasir** [comment]
Hey @ZEROF,

Thank you for your suggestion! For sure it will be taken into account.
Don't hesitate to share any ideas you might have with us, and of course, feel free to open a new Pull Request to our repository.

Cheers

**Comment by pchristos** [comment]
Hello,

I'd like to share some feedback after having installed and experimented with Wazuh on k8s for a week.

First of all, I'd love to hear your thoughts on https://github.com/wazuh/wazuh/issues/4870. 

Do you think it'd make sense for any of the points raised in the aforementioned issue to be tackled during this refactoring? 

Regarding the elastic stack - +1 for using the official images!

An exception to the above could be Kibana, which should probably still be re-built with the Wazuh plugin. 

However, a more minimalistic/simple approach could be taken IMHO. For instance:

- Is [this](https://github.com/wazuh/wazuh-docker/blob/master/kibana/config/xpack_config.sh) really necessary? Isn't x-pack enabled by default in latest ELK releases? 
- Is `sed`ing files a better approach than mounting custom configuration files or using env variables?

I think I've also noticed a bit of a duplication [here](https://github.com/wazuh/wazuh-docker/blob/master/kibana/config/kibana_settings.sh#L20) and [here](https://github.com/wazuh/wazuh-docker/blob/master/kibana/config/entrypoint.sh#L10), where two distinct environment variables are used to point to the ES URL in custom scripts. Can't a single variable be used?

Also, the way I see it the official elasticsearch image could be used without rebuilding it, no? What's the point of maintaining a separate image? ES settings can be overriden either by environment variables or bind/named volumes. Additionally [curator](https://github.com/elastic/curator) can be used for index retention, including snaphots, and possibly render [this](https://github.com/wazuh/wazuh-docker/blob/master/elasticsearch/config/configure_s3.sh) redundant (?).

Last but not least, any thoughts on https://github.com/wazuh/wazuh-docker/issues/328?

Cheers!
