### ISSUE TITLE
NGINX 502 bad gateway

### ISSUE THREAD

**Issue by RANGERBEE** [wazuh/wazuh-docker#30]
Hello,

  I am giving the cointainers a try and upon starting compose all containers start up and I see all listening ports 443/80. I am assuming NGINX is proxying the 443 traffic to :5601 - to Kibana.
  I cant seem to get to Kibana , although all is running and the browser does try and resolve - with a 502 reply.    I try my URL of https://10.0.1.199

> 502 Bad Gateway
nginx/1.13.8

I guessed at the password - foo/bar   (could this be the issue?)

> [cuckoo@wazuh1 ~]$ docker ps
CONTAINER ID        IMAGE                                                 COMMAND                  CREATED             STATUS              PORTS                                                                                            NAMES
93347887cf31        wazuh/wazuh-logstash                                  "/usr/local/bin/docke"   About an hour ago   Up 2 minutes        5044/tcp, 0.0.0.0:5000->5000/tcp, 9600/tcp                                                       wazuhdocker_logstash_1
6c77cb734116        wazuh/wazuh-nginx                                     "/run.sh"                About an hour ago   Up 2 minutes        0.0.0.0:80->80/tcp, 0.0.0.0:443->443/tcp                                                         wazuhdocker_nginx_1
6f1e46a43d76        wazuh/wazuh-kibana                                    "/wait-for-it.sh elas"   About an hour ago   Up 2 minutes        5601/tcp                                                                                         wazuhdocker_kibana_1
c0ac63e8544d        wazuh/wazuh                                           "/tmp/run.sh"            About an hour ago   Up 2 minutes        0.0.0.0:514->514/udp, 0.0.0.0:1515->1515/tcp, 0.0.0.0:1514->1514/udp, 0.0.0.0:55000->55000/tcp   wazuhdocker_wazuh_1
30915fcec08f        docker.elastic.co/elasticsearch/elasticsearch:6.1.1   "/usr/local/bin/docke"   About an hour ago   Up 5 seconds        0.0.0.0:9200->9200/tcp, 9300/tcp                                                                 wazuhdocker_elasticsearch_1
[cuckoo@wazuh1 ~]$ netstat -plntu
(Not all processes could be identified, non-owned process info
 will not be shown, you would have to be root to see it all.)
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      -
tcp        0      0 127.0.0.1:25            0.0.0.0:*               LISTEN      -
tcp6       0      0 :::1515                 :::*                    LISTEN      -
tcp6       0      0 :::9200                 :::*                    LISTEN      -
tcp6       0      0 :::80                   :::*                    LISTEN      -
tcp6       0      0 :::22                   :::*                    LISTEN      -
tcp6       0      0 :::55000                :::*                    LISTEN      -
tcp6       0      0 ::1:25                  :::*                    LISTEN      -
tcp6       0      0 :::443                  :::*                    LISTEN      -
tcp6       0      0 :::5000                 :::*                    LISTEN      -
udp        0      0 127.0.0.1:323           0.0.0.0:*                           -
udp6       0      0 ::1:323                 :::*                                -
udp6       0      0 :::514                  :::*                                -
udp6       0      0 :::1514                 :::*                                -

Thank you.

**Comment by mjflve** [comment]
Hi @RANGERBEE,

Yes, Nginx is proxying the Kibana traffic via TCP/443. Take into account that the wazuh-kibana container makes some [checks ](https://github.com/wazuh/wazuh-docker/blob/master/kibana/config/wait-for-it.sh#L10-L15)before starting the service. In summary, Kibana will start after the elasticsearch service is up and running, can you please double check the requirements listed [here ](https://documentation.wazuh.com/current/docker/wazuh-container.html#increase-max-map-count-on-your-host-linux)and re-run the composer, you should get an output like the following on the Kibana container::

```
docker-compose logs --tail=10 kibana
Attaching to root_kibana_1
kibana_1         | Transfer complete
kibana_1         | Retrieving metadata from plugin archive
kibana_1         | Extracting plugin archive
kibana_1         | Extraction complete
kibana_1         | Optimizing and caching browser bundles...
kibana_1         | Plugin installation complete
kibana_1         | Setting API credentials into Wazuh APP
kibana_1         | {"type":"log","@timestamp":"2018-01-18T02:21:54Z","tags":["listening","info"],"pid":1,"message":"Server running at http://0.0.0.0:5601"}
kibana_1         | Importing objects
kibana_1         | {"type":"log","@timestamp":"2018-01-18T02:21:57Z","tags":["\u001b[34mwazuh\u001b[39m","monitoring","error"],"pid":1,"message":"Didn't find old wazuh-monitoring pattern. Skipping deletion."}
```

I hope it helps.

Best Regards.

**Comment by RANGERBEE** [comment]
Hey @mjflve,

  Thanks for pointing me into the right direction!

Looks like my vm.max_map_count was not sticking..

I fixed it with a quick 

> sed -i -e "\\$avm.max_map_count=262144" /etc/sysctl.conf

under root.  After reboot, the map count persisted and Kibana opened right up in the browser.

Cheers.
