### ISSUE TITLE
Run as non-root user

### ISSUE THREAD

**Issue by pchristos** [wazuh/wazuh-docker#328]
Hello,

It appears that running wazuh as a non-root user is currently not feasible, even though an `ossec` user and `ossec` group do exist. The reason for that seems to be the usage of the `phusion-baseimage`, on which the container image is based, and the fact that it's invoking `/sbin/my_init` that attempts to access `/etc/container_environment/`.

Since wazuh is an HIDS, I'd expect it to guard against cases of privilege escalation at the same time.

Thanks in advance.

**Comment by xr09** [comment]
Hello @pchristos,

actually we're moving away from `phusion-baseimage` to `centos` with `s6-overlay` as init, you can read more about it on [this issue](https://github.com/wazuh/wazuh-docker/issues/296).

About the execution user it varies among the different processes, some of these require root privileges for correct functioning.

```bash
root       405  0.0  0.1 112552  6212 ?        Sl   17:48   0:00 /var/ossec/bin/ossec-authd
ossec      419  0.2  0.0 636780  5044 ?        Sl   17:48   0:00 /var/ossec/bin/wazuh-db
root       439  0.0  0.0  30492  2844 ?        Sl   17:48   0:00 /var/ossec/bin/ossec-execd
ossec      451  0.3  0.4 2877464 24080 ?       Sl   17:48   0:00 /var/ossec/bin/ossec-analysisd
root       461  1.7  0.0 178796  5192 ?        Sl   17:48   0:04 /var/ossec/bin/ossec-syscheckd
ossecr     474  0.1  0.0 442068  5072 ?        Sl   17:48   0:00 /var/ossec/bin/ossec-remoted
root       495  0.5  0.0 333592  3056 ?        Sl   17:48   0:01 /var/ossec/bin/ossec-logcollector
ossec      511  0.0  0.0  30464  2704 ?        Sl   17:48   0:00 /var/ossec/bin/ossec-monitord
root       521  0.1  0.1 638964  8452 ?        Sl   17:48   0:00 /var/ossec/bin/wazuh-modulesd
```
