### ISSUE TITLE
volume mapping permission denied

### ISSUE THREAD

**Issue by RANGERBEE** [wazuh/wazuh-docker#33]
Hello,

  Could you please tell me why when mounting a folder in my docker-compose.yml file - to the /var/ossec/data/ruleset folder , that all files are seen and upon reading - permission denied.?

Example:
```yml
    volumes:
      - ./wazuh/ruleset/.:/var/ossec/data/ruleset
```

Error:
```console
wazuh_1          | chmod: changing permissions of '/var/ossec/data/ruleset': Permission denied
wazuh_1          | chmod: changing permissions of '/var/ossec/data/ruleset/VERSION': Permission denied
wazuh_1          | chmod: changing permissions of '/var/ossec/data/ruleset/decoders': Permission denied
wazuh_1          | chmod: changing permissions of '/var/ossec/data/ruleset/decoders/0005-wazuh_decoders.xml': Permission denied
```

I have forced a container recreate with "docker-compose up --force-recreate"

I have also tried editing the /wazuh/Dockerfile with:

```yml
USER root
COPY ruleset/* /var/ossec/data/ruleset/
RUN chown 1000:1000 /var/ossec/data/ruleset
RUN chmod 755 /var/ossec/data/ruleset
```

I have no joy at these configs.  Could you all help - Ive been banging my head on the keyboard with this issue.

Thank you!

**Comment by jlruizmlg** [comment]
Hi @RANGERBEE which os are you using? Linux, OS x?

Please try the full data folder

>  volumes:
>       - ./wazuh/ruleset/.:/var/ossec/data

**Comment by RANGERBEE** [comment]
Hi @jlruizmlg

I am using Centos7..
To add: I have also just applied chown -R 1000:1000 of the ruleset folder on the host side.

I will give the path you supplied a try as well and report findings..

 Thanks!

**Comment by RANGERBEE** [comment]
Found that my settings above with the chown setting on the host side does indeed work. My one little rules file added to the complete - original collection is loaded and read.

I do see lots of erros upon load of the wazuh manager container - for each of the rules files contained within the folders - eg:

```console
Attaching to wazuhdocker_elasticsearch_1, wazuhdocker_wazuh_1, wazuhdocker_kibana_1, wazuhdocker_logstash_1, wazuhdocker_nginx_1
wazuh_1          | chmod: changing permissions of '/var/ossec/data/ruleset': Permission denied
wazuh_1          | chmod: changing permissions of '/var/ossec/data/ruleset/VERSION': Permission denied
wazuh_1          | chmod: changing permissions of '/var/ossec/data/ruleset/decoders': Permission denied
wazuh_1          | chmod: changing permissions of '/var/ossec/data/ruleset/decoders/0005-wazuh_decoders.xml': Permission denied
wazuh_1          | chmod: changing permissions of '/var/ossec/data/ruleset/decoders/0006-json_decoders.xml': Permission denied
wazuh_1          | chmod: changing permissions of '/var/ossec/data/ruleset/decoders/0010-active-response_decoders.xml': Permission denied
wazuh_1          | chmod: changing permissions of '/var/ossec/data/ruleset/decoders/0015-aix-ipsec_decoders.xml': Permission denied
wazuh_1          | chmod: changing permissions of '/var/ossec/data/ruleset/decoders/0025-apache_decoders.xml': Permission denied
wazuh_1          | chmod: changing permissions of '/var/ossec/data/ruleset/decoders/0030-arpwatch_decoders.xml': Permission denied
wazuh_1          | chmod: changing permissions of '/var/ossec/data/ruleset/decoders/0035-asterisk_decoders.xml': Permission denied
wazuh_1          | chmod: changing permissions of '/var/ossec/data/ruleset/decoders/0040-auditd_decoders.xml': Permission denied
wazuh_1          | chmod: changing permissions of '/var/ossec/data/ruleset/decoders/0045-barracuda_decoders.xml': Permission denied
wazuh_1          | chmod: changing permissions of '/var/ossec/data/ruleset/decoders/0050-checkpoint_decoders.xml': Permission denied
```
Upon waiting for the all containers to load and the "wait-for-it" script to complete - all rules are actually loaded and read - all fully operational.

I am assuming that the volume mount with docker compose tries to mount and automatically try to chmod the recursive data within the folders, which is denied. Then, when the docker file is loaded , the COPY and RUN commands make it all right.

It is important to note that I have ALSO tried NOT mounting the folder with docker-compose file and ONLY using the Dockerfile under /wazuh - which resulted in no joy.

Only way I have it working - with errors at the beginning is with all the settings mentioned above...

**Comment by jlruizmlg** [comment]
Hello!

The folder has been created by you? Try to delete and let docker create it,
docker assign his permissions.

I just run the container successful

Regards
----------------
Jose Luis Ruiz
@jlruizmlg
www.wazuh.com

**Comment by RANGERBEE** [comment]
Tried it - deleting my folder. Deleted all containers and restarted. It did not work.

Reverted back to my settings above and all works fine - just showing errors (above) on manager container first load is all. ..

**Comment by FloThinksPi** [comment]
See my Pull Request, if you add  a `:Z` to you container volumes , SELinux get managed automatically

**Comment by RANGERBEE** [comment]
Thank you!  Testing now....

**Comment by RANGERBEE** [comment]
Excellent!  All works perfectly with ":Z"
I used with my configs above - added :"Z"  and no more errors on boot of container.

Still not sure what the heck ":Z" does even after looking at the threads.  ;-/

Cheers!

**Comment by jlruizmlg** [comment]
Hi @FloThinksPi thanks for your help here, @RANGERBEE glad that this option helps, I'm going to merge your pull request now.
