### ISSUE TITLE
Elasticsearch container fails to connect

### ISSUE THREAD

**Issue by Opswatch** [wazuh/wazuh-docker#331]
OS: Ubuntu 18.04.4 vm

Docker version: 18.09.9

Using versions: 3.12.2_7.6.2

Steps taken:
Increased the vm.max_map_count

Git cloned repo and ran composer up 

No firewalls

Wazuh container and nginx start with no problems but the elasticsearch container gets stuck in a loop downloading some files and shows the following error:

0curl: (7) Failed connect to elasticsearch:9200; Connection refused
elasticsearch_1  | Elastic is unavailable - sleeping

Any ideas on what the issue could be?

**Comment by jm404** [comment]
Hi @Opswatch, 

I assume you executed `sysctl -w vm.max_map_count=262144` command. Let me add that this change is not permanent and will be lost if you reboot your machine.

To make it permanent you have to add it to the  `/etc/sysctl.conf` by executing 
```
echo 'vm.max_map_count=262144' >> /etc/sysctl.conf
```

If the problem persists, please paste us the logs you can find while executing the `docker-compose` in foreground, this will be very helpful in order to identify which is causing the error.


Best regards,

Jose

**Comment by Opswatch** [comment]
That is correct I made the map count permanent

Here is the log for the elastic search container:

{"type": "server", "timestamp": "2020-04-16T15:58:30,748Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "elasticsearch", "node.name": "es01", "message": "loaded module [rank-eval]" },
{"type": "server", "timestamp": "2020-04-16T15:58:30,748Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "elasticsearch", "node.name": "es01", "message": "loaded module [reindex]" },
{"type": "server", "timestamp": "2020-04-16T15:58:30,748Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "elasticsearch", "node.name": "es01", "message": "loaded module [repository-url]" },
{"type": "server", "timestamp": "2020-04-16T15:58:30,749Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "elasticsearch", "node.name": "es01", "message": "loaded module [search-business-rules]" },
{"type": "server", "timestamp": "2020-04-16T15:58:30,749Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "elasticsearch", "node.name": "es01", "message": "loaded module [spatial]" },
{"type": "server", "timestamp": "2020-04-16T15:58:30,749Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "elasticsearch", "node.name": "es01", "message": "loaded module [transform]" },
{"type": "server", "timestamp": "2020-04-16T15:58:30,749Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "elasticsearch", "node.name": "es01", "message": "loaded module [transport-netty4]" },
{"type": "server", "timestamp": "2020-04-16T15:58:30,750Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "elasticsearch", "node.name": "es01", "message": "loaded module [vectors]" },
{"type": "server", "timestamp": "2020-04-16T15:58:30,750Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "elasticsearch", "node.name": "es01", "message": "loaded module [x-pack-analytics]" },
{"type": "server", "timestamp": "2020-04-16T15:58:30,750Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "elasticsearch", "node.name": "es01", "message": "loaded module [x-pack-ccr]" },
{"type": "server", "timestamp": "2020-04-16T15:58:30,750Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "elasticsearch", "node.name": "es01", "message": "loaded module [x-pack-core]" },
{"type": "server", "timestamp": "2020-04-16T15:58:30,751Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "elasticsearch", "node.name": "es01", "message": "loaded module [x-pack-deprecation]" },
{"type": "server", "timestamp": "2020-04-16T15:58:30,751Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "elasticsearch", "node.name": "es01", "message": "loaded module [x-pack-enrich]" },
{"type": "server", "timestamp": "2020-04-16T15:58:30,751Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "elasticsearch", "node.name": "es01", "message": "loaded module [x-pack-graph]" },
{"type": "server", "timestamp": "2020-04-16T15:58:30,751Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "elasticsearch", "node.name": "es01", "message": "loaded module [x-pack-ilm]" },
{"type": "server", "timestamp": "2020-04-16T15:58:30,752Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "elasticsearch", "node.name": "es01", "message": "loaded module [x-pack-logstash]" },
{"type": "server", "timestamp": "2020-04-16T15:58:30,752Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "elasticsearch", "node.name": "es01", "message": "loaded module [x-pack-ml]" },
{"type": "server", "timestamp": "2020-04-16T15:58:30,752Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "elasticsearch", "node.name": "es01", "message": "loaded module [x-pack-monitoring]" },
{"type": "server", "timestamp": "2020-04-16T15:58:30,752Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "elasticsearch", "node.name": "es01", "message": "loaded module [x-pack-rollup]" },
{"type": "server", "timestamp": "2020-04-16T15:58:30,753Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "elasticsearch", "node.name": "es01", "message": "loaded module [x-pack-security]" },
{"type": "server", "timestamp": "2020-04-16T15:58:30,753Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "elasticsearch", "node.name": "es01", "message": "loaded module [x-pack-sql]" },
{"type": "server", "timestamp": "2020-04-16T15:58:30,753Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "elasticsearch", "node.name": "es01", "message": "loaded module [x-pack-voting-only-node]" },
{"type": "server", "timestamp": "2020-04-16T15:58:30,753Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "elasticsearch", "node.name": "es01", "message": "loaded module [x-pack-watcher]" },
{"type": "server", "timestamp": "2020-04-16T15:58:30,754Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "elasticsearch", "node.name": "es01", "message": "loaded plugin [repository-s3]" },
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current,
                                 Dload  Upload   Total   Spent    Left  Speed,

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Failed connect to elasticsearch:9200; Connection refused,
Elastic is unavailable - sleeping,
{"type": "server", "timestamp": "2020-04-16T15:58:37,586Z", "level": "INFO", "component": "o.e.x.s.a.s.FileRolesStore", "cluster.name": "elasticsearch", "node.name": "es01", "message": "parsed [0] roles from file [/usr/share/elasticsearch/config/roles.yml]" },
{"type": "server", "timestamp": "2020-04-16T15:58:38,308Z", "level": "INFO", "component": "o.e.x.m.p.l.CppLogMessageHandler", "cluster.name": "elasticsearch", "node.name": "es01", "message": "[controller/112] [Main.cc@110] controller (64 bit): Version 7.6.2 (Build e06ef9d86d5332) Copyright (c) 2020 Elasticsearch BV" },
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current,
                                 Dload  Upload   Total   Spent    Left  Speed,

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Failed connect to elasticsearch:9200; Connection refused,
Elastic is unavailable - sleeping,
{"type": "server", "timestamp": "2020-04-16T15:58:39,106Z", "level": "DEBUG", "component": "o.e.a.ActionModule", "cluster.name": "elasticsearch", "node.name": "es01", "message": "Using REST wrapper from plugin org.elasticsearch.xpack.security.Security" },
{"type": "server", "timestamp": "2020-04-16T15:58:39,295Z", "level": "INFO", "component": "o.e.d.DiscoveryModule", "cluster.name": "elasticsearch", "node.name": "es01", "message": "using discovery type [zen] and seed hosts providers [settings]" },
{"type": "server", "timestamp": "2020-04-16T15:58:40,621Z", "level": "INFO", "component": "o.e.n.Node", "cluster.name": "elasticsearch", "node.name": "es01", "message": "initialized" },
{"type": "server", "timestamp": "2020-04-16T15:58:40,621Z", "level": "INFO", "component": "o.e.n.Node", "cluster.name": "elasticsearch", "node.name": "es01", "message": "starting ..." },
{"type": "server", "timestamp": "2020-04-16T15:58:40,801Z", "level": "INFO", "component": "o.e.t.TransportService", "cluster.name": "elasticsearch", "node.name": "es01", "message": "publish_address {172.18.0.2:9300}, bound_addresses {0.0.0.0:9300}" },
{"type": "server", "timestamp": "2020-04-16T15:58:41,212Z", "level": "INFO", "component": "o.e.b.BootstrapChecks", "cluster.name": "elasticsearch", "node.name": "es01", "message": "bound or publishing to a non-loopback address, enforcing bootstrap checks" },
ERROR: [1] bootstrap checks failed,
[1]: max file descriptors [4096] for elasticsearch process is too low, increase to at least [65535],
ERROR: Elasticsearch did not exit normally - check the logs at /usr/share/elasticsearch/logs/elasticsearch.log,
{"type": "server", "timestamp": "2020-04-16T15:58:41,233Z", "level": "INFO", "component": "o.e.n.Node", "cluster.name": "elasticsearch", "node.name": "es01", "message": "stopping ..." },
{"type": "server", "timestamp": "2020-04-16T15:58:41,278Z", "level": "INFO", "component": "o.e.n.Node", "cluster.name": "elasticsearch", "node.name": "es01", "message": "stopped" },
{"type": "server", "timestamp": "2020-04-16T15:58:41,278Z", "level": "INFO", "component": "o.e.n.Node", "cluster.name": "elasticsearch", "node.name": "es01", "message": "closing ..." },
{"type": "server", "timestamp": "2020-04-16T15:58:41,307Z", "level": "INFO", "component": "o.e.n.Node", "cluster.name": "elasticsearch", "node.name": "es01", "message": "closed" },
{"type": "server", "timestamp": "2020-04-16T15:58:41,310Z", "level": "INFO", "component": "o.e.x.m.p.NativeController", "cluster.name": "elasticsearch", "node.name": "es01", "message": "Native controller process has stopped - no new native processes can be started" },
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current,
                                 Dload  Upload   Total   Spent    Left  Speed,

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Failed connect to elasticsearch:9200; Connection refused,
Elastic is unavailable - sleeping,
OpenJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.,
{"type": "server", "timestamp": "2020-04-16T15:58:47,059Z", "level": "INFO", "component": "o.e.e.NodeEnvironment", "cluster.name": "elasticsearch", "node.name": "es01", "message": "using [1] data paths, mounts [[/ (overlay)]], net usable_space [22gb], net total_space [39.1gb], types [overlay]" },
{"type": "server", "timestamp": "2020-04-16T15:58:47,063Z", "level": "INFO", "component": "o.e.e.NodeEnvironment", "cluster.name": "elasticsearch", "node.name": "es01", "message": "heap size [990.7mb], compressed ordinary object pointers [true]" },
{"type": "server", "timestamp": "2020-04-16T15:58:47,262Z", "level": "INFO", "component": "o.e.n.Node", "cluster.name": "elasticsearch", "node.name": "es01", "message": "node name [es01], node ID [9xj7PI0_TVGszXcV6xHU7w], cluster name [elasticsearch]" },
{"type": "server", "timestamp": "2020-04-16T15:58:47,263Z", "level": "INFO", "component": "o.e.n.Node", "cluster.name": "elasticsearch", "node.name": "es01", "message": "version[7.6.2], pid[1], build[default/docker/ef48eb35cf30adf4db14086e8aabd07ef6fb113f/2020-03-26T06:34:37.794943Z], OS[Linux/4.15.0-96-generic/amd64], JVM[AdoptOpenJDK/OpenJDK 64-Bit Server VM/13.0.2/13.0.2+8]" },
{"type": "server", "timestamp": "2020-04-16T15:58:47,263Z", "level": "INFO", "component": "o.e.n.Node", "cluster.name": "elasticsearch", "node.name": "es01", "message": "JVM home [/usr/share/elasticsearch/jdk]" },
{"type": "server", "timestamp": "2020-04-16T15:58:47,264Z", "level": "INFO", "component": "o.e.n.Node", "cluster.name": "elasticsearch", "node.name": "es01", "message": "JVM arguments [-Des.networkaddress.cache.ttl=60, -Des.networkaddress.cache.negative.ttl=10, -XX:+AlwaysPreTouch, -Xss1m, -Djava.awt.headless=true, -Dfile.encoding=UTF-8, -Djna.nosys=true, -XX:-OmitStackTraceInFastThrow, -Dio.netty.noUnsafe=true, -Dio.netty.noKeySetOptimization=true, -Dio.netty.recycler.maxCapacityPerThread=0, -Dio.netty.allocator.numDirectArenas=0, -Dlog4j.shutdownHookEnabled=false, -Dlog4j2.disable.jmx=true, -Djava.locale.providers=COMPAT, -Xms1g, -Xmx1g, -XX:+UseConcMarkSweepGC, -XX:CMSInitiatingOccupancyFraction=75, -XX:+UseCMSInitiatingOccupancyOnly, -Djava.io.tmpdir=/tmp/elasticsearch-9135483733528619687, -XX:+HeapDumpOnOutOfMemoryError, -XX:HeapDumpPath=data, -XX:ErrorFile=logs/hs_err_pid%p.log, -Xlog:gc*,gc+age=trace,safepoint:file=logs/gc.log:utctime,pid,tags:filecount=32,filesize=64m, -Des.cgroups.hierarchy.override=/, -Xms1g, -Xmx1g, -XX:MaxDirectMemorySize=536870912, -Des.path.home=/usr/share/elasticsearch, -Des.path.conf=/usr/share/elasticsearch/config, -Des.distribution.flavor=default, -Des.distribution.type=docker, -Des.bundled_jdk=true]" },
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current,
                                 Dload  Upload   Total   Spent    Left  Speed,

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Failed connect to elasticsearch:9200; Connection refused,
Elastic is unavailable - sleeping,
{"type": "server", "timestamp": "2020-04-16T15:58:50,300Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "elasticsearch", "node.name": "es01", "message": "loaded module [aggs-matrix-stats]" },
{"type": "server", "timestamp": "2020-04-16T15:58:50,300Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "elasticsearch", "node.name": "es01", "message": "loaded module [analysis-common]" },
{"type": "server", "timestamp": "2020-04-16T15:58:50,300Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "elasticsearch", "node.name": "es01", "message": "loaded module [flattened]" },
{"type": "server", "timestamp": "2020-04-16T15:58:50,301Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "elasticsearch", "node.name": "es01", "message": "loaded module [frozen-indices]" },
{"type": "server", "timestamp": "2020-04-16T15:58:50,301Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "elasticsearch", "node.name": "es01", "message": "loaded module [ingest-common]" },
{"type": "server", "timestamp": "2020-04-16T15:58:50,301Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "elasticsearch", "node.name": "es01", "message": "loaded module [ingest-geoip]" },
{"type": "server", "timestamp": "2020-04-16T15:58:50,301Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "elasticsearch", "node.name": "es01", "message": "loaded module [ingest-user-agent]" },
{"type": "server", "timestamp": "2020-04-16T15:58:50,302Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "elasticsearch", "node.name": "es01", "message": "loaded module [lang-expression]" },
{"type": "server", "timestamp": "2020-04-16T15:58:50,302Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "elasticsearch", "node.name": "es01", "message": "loaded module [lang-mustache]" },
{"type": "server", "timestamp": "2020-04-16T15:58:50,302Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "elasticsearch", "node.name": "es01", "message": "loaded module [lang-painless]" },
{"type": "server", "timestamp": "2020-04-16T15:58:50,302Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "elasticsearch", "node.name": "es01", "message": "loaded module [mapper-extras]" },
{"type": "server", "timestamp": "2020-04-16T15:58:50,303Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "elasticsearch", "node.name": "es01", "message": "loaded module [parent-join]" },
{"type": "server", "timestamp": "2020-04-16T15:58:50,303Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "elasticsearch", "node.name": "es01", "message": "loaded module [percolator]" },
{"type": "server", "timestamp": "2020-04-16T15:58:50,303Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "elasticsearch", "node.name": "es01", "message": "loaded module [rank-eval]" },
{"type": "server", "timestamp": "2020-04-16T15:58:50,303Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "elasticsearch", "node.name": "es01", "message": "loaded module [reindex]" },
{"type": "server", "timestamp": "2020-04-16T15:58:50,304Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "elasticsearch", "node.name": "es01", "message": "loaded module [repository-url]" },
{"type": "server", "timestamp": "2020-04-16T15:58:50,304Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "elasticsearch", "node.name": "es01", "message": "loaded module [search-business-rules]" },
{"type": "server", "timestamp": "2020-04-16T15:58:50,304Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "elasticsearch", "node.name": "es01", "message": "loaded module [spatial]" },
{"type": "server", "timestamp": "2020-04-16T15:58:50,305Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "elasticsearch", "node.name": "es01", "message": "loaded module [transform]" },
{"type": "server", "timestamp": "2020-04-16T15:58:50,305Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "elasticsearch", "node.name": "es01", "message": "loaded module [transport-netty4]" },
{"type": "server", "timestamp": "2020-04-16T15:58:50,305Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "elasticsearch", "node.name": "es01", "message": "loaded module [vectors]" },
{"type": "server", "timestamp": "2020-04-16T15:58:50,305Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "elasticsearch", "node.name": "es01", "message": "loaded module [x-pack-analytics]" },
{"type": "server", "timestamp": "2020-04-16T15:58:50,306Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "elasticsearch", "node.name": "es01", "message": "loaded module [x-pack-ccr]" },
{"type": "server", "timestamp": "2020-04-16T15:58:50,306Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "elasticsearch", "node.name": "es01", "message": "loaded module [x-pack-core]" },
{"type": "server", "timestamp": "2020-04-16T15:58:50,306Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "elasticsearch", "node.name": "es01", "message": "loaded module [x-pack-deprecation]" },
{"type": "server", "timestamp": "2020-04-16T15:58:50,306Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "elasticsearch", "node.name": "es01", "message": "loaded module [x-pack-enrich]" },
{"type": "server", "timestamp": "2020-04-16T15:58:50,307Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "elasticsearch", "node.name": "es01", "message": "loaded module [x-pack-graph]" },
{"type": "server", "timestamp": "2020-04-16T15:58:50,307Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "elasticsearch", "node.name": "es01", "message": "loaded module [x-pack-ilm]" },
{"type": "server", "timestamp": "2020-04-16T15:58:50,307Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "elasticsearch", "node.name": "es01", "message": "loaded module [x-pack-logstash]" },
{"type": "server", "timestamp": "2020-04-16T15:58:50,307Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "elasticsearch", "node.name": "es01", "message": "loaded module [x-pack-ml]" },
{"type": "server", "timestamp": "2020-04-16T15:58:50,308Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "elasticsearch", "node.name": "es01", "message": "loaded module [x-pack-monitoring]" },
{"type": "server", "timestamp": "2020-04-16T15:58:50,308Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "elasticsearch", "node.name": "es01", "message": "loaded module [x-pack-rollup]" },
{"type": "server", "timestamp": "2020-04-16T15:58:50,308Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "elasticsearch", "node.name": "es01", "message": "loaded module [x-pack-security]" },
{"type": "server", "timestamp": "2020-04-16T15:58:50,308Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "elasticsearch", "node.name": "es01", "message": "loaded module [x-pack-sql]" },
{"type": "server", "timestamp": "2020-04-16T15:58:50,309Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "elasticsearch", "node.name": "es01", "message": "loaded module [x-pack-voting-only-node]" },
{"type": "server", "timestamp": "2020-04-16T15:58:50,309Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "elasticsearch", "node.name": "es01", "message": "loaded module [x-pack-watcher]" },
{"type": "server", "timestamp": "2020-04-16T15:58:50,309Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "elasticsearch", "node.name": "es01", "message": "loaded plugin [repository-s3]" },

**Comment by Opswatch** [comment]
Going to close this up, I started a new fresh vm and its working fine, only difference is I installed docker from the main repos instead of using a ubuntu snap maybe that was causing some funky issues, thanks for the help.
