### ISSUE TITLE
Unable to generate report

### ISSUE THREAD

**Issue by ilhaan** [wazuh/wazuh-docker#332]
Kibana version: `6.8.8`
Wazuh Version: `3.12.2`

When I try to generate a CSV Report, I get the following error message: 

> Unable to generate report
> Error: Failed to decrypt report job data. Please ensure that xpack.reporting.encryptionKey is set and re-generate this report.

I added an encryption key by modifying `wazuh-ockerkibana/config/xpack_config.sh` as shown below: 
```bash
#!/bin/bash
# Wazuh Docker Copyright (C) 2020 Wazuh Inc. (License GPLv2)

kibana_config_file="/usr/share/kibana/config/kibana.yml"
if grep -Fq  "#xpack features" "$kibana_config_file";
then
  declare -A CONFIG_MAP=(
    [xpack.apm.ui.enabled]=$XPACK_APM
    [xpack.grokdebugger.enabled]=$XPACK_DEVTOOLS
    [xpack.searchprofiler.enabled]=$XPACK_DEVTOOLS
    [xpack.ml.enabled]=$XPACK_ML
    [xpack.canvas.enabled]=$XPACK_CANVAS
    [xpack.infra.enabled]=$XPACK_INFRA
    [xpack.monitoring.enabled]=$XPACK_MONITORING
    [console.enabled]=$XPACK_DEVTOOLS
  )
  for i in "${!CONFIG_MAP[@]}"
  do
    if [ "${CONFIG_MAP[$i]}" != "" ]; then
      sed -i 's/.'"$i"'.*/'"$i"': '"${CONFIG_MAP[$i]}"'/' $kibana_config_file
    fi
  done
else
  echo "
#xpack features
xpack.apm.ui.enabled: $XPACK_APM
xpack.grokdebugger.enabled: $XPACK_DEVTOOLS
xpack.searchprofiler.enabled: $XPACK_DEVTOOLS
xpack.ml.enabled: $XPACK_ML
xpack.canvas.enabled: $XPACK_CANVAS
xpack.infra.enabled: $XPACK_INFRA
xpack.monitoring.enabled: $XPACK_MONITORING
console.enabled: $XPACK_DEVTOOLS
xpack.reporting.encryptionKey: \"somethingsecret\"
" >> $kibana_config_file
fi
```
(I added `xpack.reporting.encryptionKey: \"somethingsecret\"` to the `echo` block at the bottom of the script) 

I confirmed that this change made it to the container I built by logging in to a running container and reading `/usr/share/kibana/config/kibana.yml`. 

However, I still get the above mentioned "Unable to generate report" error. 

Please let me know if I am doing something wrong here and how I can resolve this.

**Comment by jm404** [comment]
Hi @ilhaan,

We will try to reproduce your issue and let you know the results as soon as possible

Best regards,

Jose

**Comment by jm404** [comment]
Hi @ilhaan,

I tried to reproduce your issue with our Docker images `3.12.2_7.6.1` and `3.9.2_6.8.0` without success. Let me ask you for some info in order to have a better understanding of the problem:

- Are you using our Docker images with customized versions? If no please share your Dockerfiles and configs so we can review them.

- Check `cat /usr/share/kibana/optimize/wazuh-logs/wazuhapp.log` for some errors in the log

- Check permissions of `/usr/share/kibana/optimize/` folder and it's subfolders, sometimes when remounting volumes you can find some permissions errors if you changed base image or have custom scripts.

Feel free to share any other relevant information you consider.

Thanks for your patience,

Best regards

Jose

**Comment by ilhaan** [comment]
Hi @jm404, thanks for looking into this. 

* I'm using Kibana 6.8.8 and Wazuh 3.12.2 (mentioned this in my original post as well). Here is my `git diff` output showing changes I made: 
```diff --git a/kibana/Dockerfile b/kibana/Dockerfile
index 5e7c2f5..f3bee61 100644
--- a/kibana/Dockerfile
+++ b/kibana/Dockerfile
@@ -1,7 +1,7 @@
 # Wazuh Docker Copyright (C) 2020 Wazuh Inc. (License GPLv2)
-FROM docker.elastic.co/kibana/kibana:7.6.2
+FROM docker.elastic.co/kibana/kibana:6.8.8
 USER kibana
-ARG ELASTIC_VERSION=7.6.2
+ARG ELASTIC_VERSION=6.8.8
 ARG WAZUH_VERSION=3.12.2
 ARG WAZUH_APP_VERSION="${WAZUH_VERSION}_${ELASTIC_VERSION}"
 
diff --git a/kibana/config/xpack_config.sh b/kibana/config/xpack_config.sh
index fedfad4..8f5a8e8 100644
--- a/kibana/config/xpack_config.sh
+++ b/kibana/config/xpack_config.sh
@@ -31,5 +31,6 @@ xpack.canvas.enabled: $XPACK_CANVAS
 xpack.infra.enabled: $XPACK_INFRA
 xpack.monitoring.enabled: $XPACK_MONITORING
 console.enabled: $XPACK_DEVTOOLS
+xpack.reporting.encryptionKey: "something_secret"
 " >> $kibana_config_file
 fi
(END)
```
* `/usr/share/kibana/optimize/wazuh/logs/wazuhapp.log`: 
```
{"date":"2020-04-17T21:03:04.890Z","level":"info","location":"initialize","message":"Kibana index: .kibana"}
{"date":"2020-04-17T21:03:04.891Z","level":"info","location":"initialize","message":"App revision: 0493"}
{"date":"2020-04-17T21:03:04.891Z","level":"info","location":"initialize","message":"Total RAM: 257411MB"}
{"date":"2020-04-17T21:03:06.311Z","level":"info","location":"initialize","message":"App ready to be used."}
```
* `/usr/share/kibana/optimize/` permissions: 
```
bash-4.2$ ls -l /usr/share/kibana/optimize/
total 8
drwxrwsr-x 1 kibana root 4096 Apr 16 20:17 bundles
drwxr-sr-x 4 kibana root 4096 Apr 17 21:02 wazuh
```

Also, here is the `/usr/share/kibana/config/kibana.yml`: 
```
#
# ** THIS IS AN AUTO-GENERATED FILE **
#

# Default Kibana configuration for docker target
server.name: kibana
server.host: "0"
elasticsearch.hosts: [ "http://myelasticsearch:9200" ]
xpack.monitoring.ui.container.elasticsearch.enabled: true
#xpack features
xpack.apm.ui.enabled: true
xpack.grokdebugger.enabled: true
xpack.searchprofiler.enabled: true
xpack.ml.enabled: true
xpack.canvas.enabled: true
xpack.infra.enabled: true
xpack.monitoring.enabled: true
console.enabled: true
xpack.reporting.encryptionKey: "somethingsecret"
```
Let me know if you need something else.

**Comment by jm404** [comment]
Hi @ilhaan,

The version `3.12.2_6.8.8` is not supported in our `wazuh-docker` repo but we can adapt another branch to this version.

I will select the [3.9.2_6.8.0](https://github.com/wazuh/wazuh-docker/tree/3.9.2_6.8.0) branch as the base branch.

The required steps to adapt this branch are the following:

### Update the `docker-compose.yml` file

Replace every image version with `build: <component_name>` to force Docker to rebuild the images.

### Bump version to 3.12.2_6.8.8

Update any references to `3.9.2` to `3.12.2` and `6.8.0` to `6.8.8` for Wazuh, Filebeat, Elastic, Logstash and Kibana

### Update the `wazuh_app_config.sh`

It's required to update the content of `wazuh-docker/kibana/config/wazuh_app_config.sh to:
```bash
#!/bin/bash
# Wazuh Docker Copyright (C) 2020 Wazuh Inc. (License GPLv2)

wazuh_url="${WAZUH_API_URL:-https://wazuh}"
wazuh_port="${API_PORT:-55000}"
api_user="${API_USER:-foo}"
api_password="${API_PASS:-bar}"

kibana_config_file="/usr/share/kibana/optimize/wazuh/config/wazuh.yml"
mkdir -p /usr/share/kibana/optimize/wazuh/config/
touch $kibana_config_file

declare -A CONFIG_MAP=(
  [pattern]=$PATTERN
  [checks.pattern]=$CHECKS_PATTERN
  [checks.template]=$CHECKS_TEMPLATE
  [checks.api]=$CHECKS_API
  [checks.setup]=$CHECKS_SETUP
  [extensions.pci]=$EXTENSIONS_PCI
  [extensions.gdpr]=$EXTENSIONS_GDPR
  [extensions.audit]=$EXTENSIONS_AUDIT
  [extensions.oscap]=$EXTENSIONS_OSCAP
  [extensions.ciscat]=$EXTENSIONS_CISCAT
  [extensions.aws]=$EXTENSIONS_AWS
  [extensions.virustotal]=$EXTENSIONS_VIRUSTOTAL
  [extensions.osquery]=$EXTENSIONS_OSQUERY
  [timeout]=$APP_TIMEOUT
  [wazuh.shards]=$WAZUH_SHARDS
  [wazuh.replicas]=$WAZUH_REPLICAS
  [wazuh-version.shards]=$WAZUH_VERSION_SHARDS
  [wazuh-version.replicas]=$WAZUH_VERSION_REPLICAS
  [ip.selector]=$IP_SELECTOR
  [ip.ignore]=$IP_IGNORE
  [xpack.rbac.enabled]=$XPACK_RBAC_ENABLED
  [wazuh.monitoring.enabled]=$WAZUH_MONITORING_ENABLED
  [wazuh.monitoring.frequency]=$WAZUH_MONITORING_FREQUENCY
  [wazuh.monitoring.shards]=$WAZUH_MONITORING_SHARDS
  [wazuh.monitoring.replicas]=$WAZUH_MONITORING_REPLICAS
  [admin]=$ADMIN_PRIVILEGES
)

for i in "${!CONFIG_MAP[@]}"
do
    if [ "${CONFIG_MAP[$i]}" != "" ]; then
        sed -i 's/.*#'"$i"'.*/'"$i"': '"${CONFIG_MAP[$i]}"'/' $kibana_config_file
    fi
done

# remove default API entry (new in 3.11.0_7.5.1)
sed -ie '/- default:/,+4d' $kibana_config_file

CONFIG_CODE=$(curl -s -o /dev/null -w "%{http_code}" -XGET $el_url/.wazuh/_doc/1513629884013 ${auth})

grep -q 1513629884013 $kibana_config_file
_config_exists=$?

if [[ "x$CONFIG_CODE" != "x200" && $_config_exists -ne 0 ]]; then
cat << EOF > $kibana_config_file
hosts:
  - 1513629884013:
      url: $wazuh_url
      port: $wazuh_port
      user: $api_user
      password: $api_password
EOF
else
  echo "Wazuh APP already configured"
fi

``` 


### Execute `docker-compose up --build`

This way you should be able to log in to Kibana and generate required 

Hope it helps!

Best regards,

Jose

**Comment by ilhaan** [comment]
@jm404 thank you for the prompt response! Will give this a shot and let you know how it goes.

**Comment by ilhaan** [comment]
@jm404 Just tried this and still seeing the following error when I try to export a CSV: 
> Error: Failed to decrypt report job data. Please ensure that xpack.reporting.encryptionKey is set and re-generate this report.

**Comment by jm404** [comment]
Hi @ilhaan,

Could you detail me how are you generating the CSV files? I've tested it by going to `Discovery`tab and clicking on generate reports.

**Comment by ilhaan** [comment]
Hi @jm404, 

I am generating the CSV files using the Share -> CSV Reports -> Generate CSV button as shown below: 
![Screen Shot 2020-04-22 at 6 22 26 PM](https://user-images.githubusercontent.com/5787928/80048899-64567480-84c6-11ea-9111-ccc542c98220.png)
Will try to get you logs for this soon.

**Comment by ilhaan** [comment]
@jm404 Do I need to add `xpack.reporting.encryptionKey: \"somethingsecret\"` or something along those lines somewhere in the config now? Just realized the new configs for the older version do not have this set like I did [here](https://github.com/wazuh/wazuh-docker/issues/332#issuecomment-615471164)

**Comment by jm404** [comment]
Hi @ilhaan, the `xpack.reporting.encryptionKey` is not required, I managed to generate the CSV without configuring it

**Comment by ilhaan** [comment]
@jm404 Can I use the [3.9.2_6.8.0](https://github.com/wazuh/wazuh-docker/tree/3.9.2_6.8.0) branch to build Wazuh 3.13.0 and Kibana 6.8.10?
