### ISSUE TITLE
firewall checkpoint conf

### ISSUE THREAD

**Issue by mserranolm** [wazuh/wazuh-docker#346]
I can't find configuration or documentation to add a firewall checkpoint in our environment in docker

**Comment by xr09** [comment]
Hello @mserranolm, let me get this, you're trying to monitor a firewall with your Wazuh server deployed on Docker right?

**Comment by mserranolm** [comment]
Yes, I work in docker

**Comment by xr09** [comment]
In this case you can obtain the logs from the firewall through syslog. Basically you setup a syslog listener on your Wazuh server and then instruct your firewall to send the logs to this port.

More info on the docs, check out the example at the end.  https://documentation.wazuh.com/3.12/user-manual/reference/ossec-conf/remote.html

We support checkpoint logs though not all models, but this file could give you a head start in case you need to build your own. https://github.com/wazuh/wazuh-ruleset/blob/master/decoders/0050-checkpoint_decoders.xml

**Comment by xr09** [comment]
Hey @mserranolm I'm marking this issue as done, feel free to reopen if needed.
