### ISSUE TITLE
hostname/ip for self signed nginx cert

### ISSUE THREAD

**Issue by Opswatch** [wazuh/wazuh-docker#347]
Is there a way to add a hostname or ip address to the self signed certififcate for nginx, without it im not able to add beats dashboards to kibana since the self signed cert has no hostname or ip.

**Comment by xr09** [comment]
Hello @Opswatch!

You can customize the nginx container at your will, to give you a starting point you can take a look at our current rework, you can see how to use the official image on docker-compose [here](https://github.com/wazuh/wazuh-docker/blob/devel-rework/docker-compose.yml#L49) and a config sample [here](https://github.com/wazuh/wazuh-docker/tree/devel-rework/nginx_conf).

A quicker approach without the need to change images would be to create a custom `entrypoint.sh` based on the one shipping with our [nginx container](https://github.com/wazuh/wazuh-docker/blob/master/nginx/config/entrypoint.sh) and mounting this on your docker-compose

```yml
nginx:
    ...   
    volumes:
      - ./my_entrypoint.sh:/entrypoint.sh:ro
```

You can customize both the SSL certificate and the nginx config this way.

**Comment by xr09** [comment]
Marking this issue as solved, feel free to reopen if needed!
