### ISSUE TITLE
Update opendistro security image

### ISSUE THREAD

**Issue by amirkh81** [wazuh/wazuh-docker#351]
The last wazuh opendistro release is "wazuh:3.9.4_7.1.1-opendistro-security" and it is outdated. It causes a lot of incompatibility issues if you want to install wazuh plugin on opendistro kibana image. 
It will be really helpful, if you release the new version for opendistro-security for example for:
>  wazuh version "3.12.x"
> elastic version "7.7.x"

Thanks

**Comment by jm404** [comment]
Hi @amirkh81,

The branch `wazuh:3.9.4_7.1.1-opendistro-security` was a testing branch we created to test some OpenDistro features. We currently don't support it in our Docker images but it's definitely in our roadmap as we know that many users benefit of the OpenDistro features.

Anyway if you have any issue while adapting the testing branch or anything else, please reach us on Slack https://wazuh.com/community/join-us-on-slack/ , we'll be glad to help you!

Best regards,

Jose
