### ISSUE TITLE
Wazuh API service not restarted after password change

### ISSUE THREAD

**Issue by bermannoah** [wazuh/wazuh-docker#359]
Hey all -- it looks like when I change the API password (API_PASS=<new pass> in docker-compose) I still need to run a subsequent, manual, service wazuh-api restart. Looking in the setup scripts it seems as though a new password will trigger 

```
echo "Change Wazuh API user credentials"
change_user="node htpasswd -b -c user $API_USER $API_PASS"
eval $change_user
```

but then we don't restart the service afterwards, so it still maintains the old password (or in some cases resets to foo:bar). If I'm understanding this correctly I'm happy to submit a PR to add that service restart, but just wanted to be sure.

**Comment by xr09** [comment]
Hello @bermannoah!

That snippet of code comes from `00-wazuh.sh` which is executed before starting my_init (current init manager) which then will start the api as one of its processes, you can check the entrypoint script:  https://github.com/wazuh/wazuh-docker/blob/master/wazuh/config/entrypoint.sh

which steps are you taking exactly? Also, remember the variables `API_USER` and `API_PASS` must be defined for all container on the `docker-compose.yml` not just for the Wazuh manager.

**Comment by bermannoah** [comment]
Hey @xr09 I'll close this, I'm still not sure why it was happening but we seem to have resolved the issue and I can't get it to happen again.
