### ISSUE TITLE
Allow disabling the filebeat service on the docker container

### ISSUE THREAD

**Issue by gittygoo** [wazuh/wazuh-docker#363]
On the wazuh docker container it should be possible to prevent filebeat from running through an ENV variable or similar.

Use case:
At the moment we do not need filebeat as we just need access to the API (but will need in the future) so would be good to make it not use those resources  for now and be able to decide when to enable or not filebeat.

**Comment by manuasir** [comment]
Thank you for your suggestion @gittygoo. I think that due to the common Wazuh use case this is not going to be implemented for the moment. For your specific scenario, I suggest to manually stop the Filebeat service. Don't hesitate to contact us if you need assistance with the way to do that.
