### ISSUE TITLE
Waiting for Kibana API 

### ISSUE THREAD

**Issue by TheThingGoesSkra** [wazuh/wazuh-docker#369]
**Hi, I try to launch the wazuh docker on a Kali linux host but the Kibana API won't works:** 

**I got this message again and again :** 

kibana_1         | Waiting for Kibana API. Sleeping 5 seconds
kibana_1         | {"type":"response","@timestamp":"2020-08-14T15:21:27Z","tags":[],"pid":21,"method":"get","statusCode":503,"req":{"url":"/status","method":"get","headers":{"user-agent":"curl/7.29.0","host":"kibana:5601","accept":"*/*"},"remoteAddress":"172.20.0.4","userAgent":"172.20.0.4"},"res":{"statusCode":503,"responseTime":134,"contentLength":9},"message":"GET /status 503 134ms - 9.0B"}
elasticsearch_1  | {"type": "server", "timestamp": "2020-08-14T15:21:27,758Z", "level": "INFO", "component": "o.e.c.m.MetadataIndexTemplateService", "cluster.name": "elasticsearch", "node.name": "es01", "message": "adding template [wazuh] for index patterns [wazuh-alerts-3.x-*, wazuh-archives-3.x-*]", "cluster.uuid": "8zxhhxmOT82B9wbLDeCQ_g", "node.id": "8x6rO68URH2mqQujThXcuw"  }

**And this one trying to join the kibana container directly from host:** 

curl -XGET -I -w ''%{http_code}'' 172.20.0.4:5601/status                                                                                                 
HTTP/1.1 503 Service Unavailable
content-type: text/html; charset=utf-8
content-security-policy: script-src 'unsafe-eval' 'self'; worker-src blob: 'self'; style-src 'unsafe-inline' 'self'
kbn-name: kibana
kbn-license-sig: 045ff6eb4f4f33844f4d7eddf55c5f6bd636e7e11b1e1fefec0c2fec95b00cd1
kbn-xpack-sig: 81d3c61af2eabc8b8afc2034647ad614
cache-control: private, no-cache, no-store, must-revalidate
content-length: 111550
vary: accept-encoding
Date: Fri, 14 Aug 2020 14:57:47 GMT
Connection: keep-alive

**Moreover, I seen different error messages during the set up process :** 

elasticsearch_1  | {"type": "server", "timestamp": "2020-08-14T15:20:56,702Z", "level": "WARN", "component": "o.e.c.r.a.DiskThresholdMonitor", "cluster.name": "elasticsearch", "node.name": "es01", "message": "high disk watermark [90%] exceeded on [8x6rO68URH2mqQujThXcuw][es01][/usr/share/elasticsearch/data/nodes/0] free: 1.7gb[7.3%], shards will be relocated away from this node; currently relocating away shards totalling [0] bytes; the node is expected to continue to exceed the high disk watermark when these relocations are complete", "cluster.uuid": "8zxhhxmOT82B9wbLDeCQ_g", "node.id": "8x6rO68URH2mqQujThXcuw"  }

kibana_1         | {"type":"log","@timestamp":"2020-08-14T15:09:27Z","tags":["warning","plugins","apm"],"pid":39,"message":"Could not create index: '.apm-agent-configuration'. Retrying..."}
kibana_1         | {"type":"log","@timestamp":"2020-08-14T15:09:27Z","tags":["warning","plugins","apm"],"pid":39,"message":"{ Error: [cluster_block_exception] index [.apm-agent-configuration] blocked by: [TOO_MANY_REQUESTS/12/index read-only / allow delete (api)];\n    at respond (/usr/share/kibana/node_modules/elasticsearch/src/lib/transport.js:349:15)\n    at checkRespForFailure (/usr/share/kibana/node_modules/elasticsearch/src/lib/transport.js:306:7)\n    at HttpConnector.<anonymous> (/usr/share/kibana/node_modules/elasticsearch/src/lib/connectors/http.js:173:7)\n    at IncomingMessage.wrapper (/usr/share/kibana/node_modules/elasticsearch/node_modules/lodash/lodash.js:4929:19)\n    at IncomingMessage.emit (events.js:203:15)\n    at endReadableNT (_stream_readable.js:1145:12)\n    at process._tickCallback (internal/process/next_tick.js:63:19)\n  status: 429,\n  displayName: 'TooManyRequests',\n  message:\n   '[cluster_block_exception] index [.apm-agent-configuration] blocked by: [TOO_MANY_REQUESTS/12/index read-only / allow delete (api)];',\n  path: '/.apm-agent-configuration/_mapping',\n  query: {},\n  body:\n   { error:\n      { root_cause: [Array],\n        type: 'cluster_block_exception',\n        reason:\n         'index [.apm-agent-configuration] blocked by: [TOO_MANY_REQUESTS/12/index read-only / allow delete (api)];' },\n     status: 429 },\n  statusCode: 429,\n  response:\n   '{\"error\":{\"root_cause\":[{\"type\":\"cluster_block_exception\",\"reason\":\"index [.apm-agent-configuration] blocked by: [TOO_MANY_REQUESTS/12/index read-only / allow delete (api)];\"}],\"type\":\"cluster_block_exception\",\"reason\":\"index [.apm-agent-configuration] blocked by: [TOO_MANY_REQUESTS/12/index read-only / allow delete (api)];\"},\"status\":429}',\n  toString: [Function],\n  toJSON: [Function],\n  attemptNumber: 2,\n  retriesLeft: 9 }"}

kibana_1         | {"type":"error","@timestamp":"2020-08-14T15:09:29Z","tags":["warning","process"],"pid":39,"level":"error","error":{"message":"Error: index [.kibana_task_manager_1] blocked by: [TOO_MANY_REQUESTS/12/index read-only / allow delete (api)];: [cluster_block_exception] index [.kibana_task_manager_1] blocked by: [TOO_MANY_REQUESTS/12/index read-only / allow delete (api)];\n    at respond (/usr/share/kibana/node_modules/elasticsearch/src/lib/transport.js:349:15)\n    at checkRespForFailure (/usr/share/kibana/node_modules/elasticsearch/src/lib/transport.js:306:7)\n    at HttpConnector.<anonymous> (/usr/share/kibana/node_modules/elasticsearch/src/lib/connectors/http.js:173:7)\n    at IncomingMessage.wrapper (/usr/share/kibana/node_modules/elasticsearch/node_modules/lodash/lodash.js:4929:19)\n    at IncomingMessage.emit (events.js:203:15)\n    at endReadableNT (_stream_readable.js:1145:12)\n    at process._tickCallback (internal/process/next_tick.js:63:19)","name":"UnhandledPromiseRejectionWarning","stack":"UnhandledPromiseRejectionWarning: Error: index [.kibana_task_manager_1] blocked by: [TOO_MANY_REQUESTS/12/index read-only / allow delete (api)];: [cluster_block_exception] index [.kibana_task_manager_1] blocked by: [TOO_MANY_REQUESTS/12/index read-only / allow delete (api)];\n    at respond (/usr/share/kibana/node_modules/elasticsearch/src/lib/transport.js:349:15)\n    at checkRespForFailure (/usr/share/kibana/node_modules/elasticsearch/src/lib/transport.js:306:7)\n    at HttpConnector.<anonymous> (/usr/share/kibana/node_modules/elasticsearch/src/lib/connectors/http.js:173:7)\n    at IncomingMessage.wrapper (/usr/share/kibana/node_modules/elasticsearch/node_modules/lodash/lodash.js:4929:19)\n    at IncomingMessage.emit (events.js:203:15)\n    at endReadableNT (_stream_readable.js:1145:12)\n    at process._tickCallback (internal/process/next_tick.js:63:19)\n    at emitWarning (internal/process/promises.js:97:15)\n    at emitPromiseRejectionWarnings (internal/process/promises.js:143:7)\n    at process._tickCallback (internal/process/next_tick.js:69:34)"},"message":"Error: index [.kibana_task_manager_1] blocked by: [TOO_MANY_REQUESTS/12/index read-only / allow delete (api)];: [cluster_block_exception] index [.kibana_task_manager_1] blocked by: [TOO_MANY_REQUESTS/12/index read-only / allow delete (api)];\n    at respond (/usr/share/kibana/node_modules/elasticsearch/src/lib/transport.js:349:15)\n    at checkRespForFailure (/usr/share/kibana/node_modules/elasticsearch/src/lib/transport.js:306:7)\n    at HttpConnector.<anonymous> (/usr/share/kibana/node_modules/elasticsearch/src/lib/connectors/http.js:173:7)\n    at IncomingMessage.wrapper (/usr/share/kibana/node_modules/elasticsearch/node_modules/lodash/lodash.js:4929:19)\n    at IncomingMessage.emit (events.js:203:15)\n    at endReadableNT (_stream_readable.js:1145:12)\n    at process._tickCallback (internal/process/next_tick.js:63:19)"}
kibana_1         | {"type":"error","@timestamp":"2020-08-14T15:09:29Z","tags":["warning","process"],"pid":39,"level":"error","error":{"message":"Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)","name":"UnhandledPromiseRejectionWarning","stack":"Error: index [.kibana_task_manager_1] blocked by: [TOO_MANY_REQUESTS/12/index read-only / allow delete (api)];: [cluster_block_exception] index [.kibana_task_manager_1] blocked by: [TOO_MANY_REQUESTS/12/index read-only / allow delete (api)];\n    at respond (/usr/share/kibana/node_modules/elasticsearch/src/lib/transport.js:349:15)\n    at checkRespForFailure (/usr/share/kibana/node_modules/elasticsearch/src/lib/transport.js:306:7)\n    at HttpConnector.<anonymous> (/usr/share/kibana/node_modules/elasticsearch/src/lib/connectors/http.js:173:7)\n    at IncomingMessage.wrapper (/usr/share/kibana/node_modules/elasticsearch/node_modules/lodash/lodash.js:4929:19)\n    at IncomingMessage.emit (events.js:203:15)\n    at endReadableNT (_stream_readable.js:1145:12)\n    at process._tickCallback (internal/process/next_tick.js:63:19)"},"message":"Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)"}
kibana_1         | {"type":"log","@timestamp":"2020-08-14T15:09:29Z","tags":["warning","plugins","apm"],"pid":39,"message":"Could not create index: '.apm-custom-link'. Retrying..."}

**Finaly join the ELK url redirect me to this url : https://localhost/spaces/space_selector
and show me an elastic search web page with the "No spaces match search criteria" message.**

**What I need to do in order to make kibana work plz ?**

**Comment by TheThingGoesSkra** [comment]
Ok, it's good. I hadn't enough space on the disk. You need less than 90% used.

**Comment by manuasir** [comment]
Glad you solved this issue. I'm closing the ticket, don't hesitate to open a new one if you need it.

Regards
