### ISSUE TITLE
How do I add custom rules?

### ISSUE THREAD

**Issue by airdogvan** [wazuh/wazuh-docker#375]
I come from OSSEC and there I could define custom rules in /var/ossec/rules/local_rules.xml.

Is this possible at all with Wazuh's docker-compose?

I tried mounting a volume, like indicated in the docs at:
volumes:
      - /wazuh-data/:/var/ossec/data/:Z
But when I go in Portainer it tells me that that volume is not used.
And anyway in the /data dir I find:
agentless  api  etc  logs  process_list  queue  var

Don't see access to rules definition.

Also tried
1- After the container was up make a local copy of the ossec dir with docker cp <containerid>:/var/ossec .
2- Mounting that directory with 
    - ./ossec/:/var/ossec/

but after starting the container complains that it can't find files like 
tail: cannot open '/var/ossec/data/logs/api.log' for reading: No such file or directory

I checked the file is in the host dir but not in the container dir

So to be clear I'm looking for a way to make custom rules, as it is possible in the original OSSEC project, and make these rules persistent, i.e. will not disappear when container is brought down and then back up.

Help much appreciated.

**Comment by airdogvan** [comment]
Sorry didn't see the Kibana section "management" which makes it possible to add new rules...

**Comment by airdogvan** [comment]
Well in fact unless there's something I'm missing I still have problems.

As said, the volume mapping 
- /wazuh-data/:/var/ossec/data/:Z
doesn't seem to do anything for me.
Sometimes it shows up in Portainer but is unused, very often it doesn't show up at all in Portainer volumes or docker volume ls.

For reference I'm running Ubuntu 20.04 LTS

**Comment by xr09** [comment]
Hello @airdogvan ,

what you're using right there is not a Docker volume, that's a bind mount, your mounting a local directory into the container, this is why it doesn't show up when listing with `docker volume ls`.

https://docs.docker.com/storage/bind-mounts/

https://docs.docker.com/storage/volumes/


The right way of assigning a volume to the Wazuh container would be like this:

```yaml
services:
  wazuh:
    image: wazuh/wazuh:3.13.1_7.8.0
    hostname: wazuh-manager
    restart: always
    ports:
      - "1514:1514/udp"
      - "1515:1515"
      - "514:514/udp"
      - "55000:55000"
    volumes:
      - wazuh-data:/var/ossec/data/


volumes:
  wazuh-data:
```


Once you launch a cluster with this config you can stop the cluster and check the volume actually contains data.


```shell
$ docker volume ls
DRIVER              VOLUME NAME
local               0da1a64be1d796ac437c2184c931a9f14cf1f8199f6b4be8f0d0418c664840bc
local               6da57d3fa23038de34190024dcc1b24c55b4eb4f451fd85dd53e2b9a60927a17
local               8acda9d665def6ab037a7acd1a9d724983ecedb8fc08ad26c8a8b1d7a16b814a
local               22191f62e8c8cb124ea944cb69e130d17e9604b9a4ff2d2ed495c52eb07275d8
local               wazuh-docker_wazuh-data
```

`docker run --rm -ti -v wazuh-docker_wazuh-data:/mnt/vol alpine ls -l /mnt/vol`

```shell
total 24
drwxrwx---    2 root     1000          4096 Jul 14 17:52 agentless
drwxrwxr-x    3 root     root          4096 Sep  2 15:20 api
drwxrwx---    7 1000     1000          4096 Sep  2 15:20 etc
drwxrwx---    8 1000     1000          4096 Sep  2 15:20 logs
-rw-rw-r--    1 root     1000             0 Sep  2 15:20 process_list
drwxrwx---   15 root     1000          4096 Jul 14 17:52 queue
drwxrwxr-x    3 root     root          4096 Sep  2 15:20 var
```

I'm marking this as closed, feel free to reopen if needed. Thanks for joining us!
