### ISSUE TITLE
Migrating from 3.x to 4.x

### ISSUE THREAD

**Issue by manuasir** [wazuh/wazuh-docker#385]
Hi team,

### Objective

The main goal is to ensure Wazuh agents' information is not lost when upgrading from 3.x to 4.x. There will be some implementation designs above about files and processes involved.

### Old implementation insights

Until Wazuh v4.0 all the agent's information was stored in files located in `/var/ossec/queue/agent-info/`, that information was replicated into the `/var/ossec/var/db/global.db` database to be consulted by the Wazuh API and some tool like `agent-control` and `cluster-control`.

### New implementation design

From Wazuh v4.0, the `global.db` is managed by the `wazuh-db` daemon and stored into the folder along with other databases in `/var/ossec/queue/db/`. The previous `agent-info` files are not created any more and the information is stored directly in the database.

### Upgrade mechanism

- The `global.db` database moves to the new location. It must get the right owner and permissions.
- Attributes and tables are added to that database.
- Check the existence of the folder `agent-info`. If true, it gets removed along with its content.

More info and details: https://github.com/wazuh/wazuh/pull/6040/files#diff-bb3bb2723feb9d73304b38beb09dfe2eR70

**Comment by xr09** [comment]
This procedure is documented on #381
