### ISSUE TITLE
Persist Configuration 3.13

### ISSUE THREAD

**Issue by alphaDev23** [wazuh/wazuh-docker#413]
Using  wazuh/wazuh:3.13.2_7.9.1.  How is the configuration and client keys persisted?  I added a volume referencing /var/ossec/etc but the image fails (first 2 items related to the api fail when viewing from Kibana).  Removing the volume resolves the api issue but the configuration is unable to be persisted.

I noticed 4.0 contains volumes in the wazuh-manager definition but these images are not yet on docker hub.

**Comment by xr09** [comment]
Hi @alphaDev23, our 3.13 images achieved persistence with a volume mounted on `/var/ossec/data`, there is some internal logic to save all relevant data there, here you can see the volume definition: https://github.com/wazuh/wazuh-docker/blob/3.13/wazuh/Dockerfile#L50-L54

For 4.0 we switched to several volumes and removed this logic for a more transparent approach.

Hope this helps.

**Comment by xr09** [comment]
Hey @alphaDev23, I'm marking this issue as solved, feel free to reopen if needed.
