### ISSUE TITLE
ossec-authd service?

### ISSUE THREAD

**Issue by alphaDev23** [wazuh/wazuh-docker#416]
Manual states to stop  ossec-authd on the wazuh-manager if not adding an agent.  "By default, there is no authentication or authorization involved in this transaction, so it is recommended that this daemon only be run when a new agent is being added."

Where are these services on the wazuh-manager container?  The following service list does not include ossec-authd.

root@wazuh-manager:~# service --status-all
 [ - ]  bootmisc.sh
 [ - ]  checkfs.sh
 [ - ]  checkroot-bootclean.sh
 [ - ]  checkroot.sh
 [ + ]  cron
 [ + ]  filebeat
 [ - ]  hostname.sh
 [ ? ]  hwclock.sh
 [ - ]  killprocs
 [ - ]  mountall-bootclean.sh
 [ - ]  mountall.sh
 [ - ]  mountdevsubfs.sh
 [ - ]  mountkernfs.sh
 [ - ]  mountnfs-bootclean.sh
 [ - ]  mountnfs.sh
 [ ? ]  ondemand
 [ - ]  postfix
 [ - ]  procps
 [ - ]  rc.local
 [ - ]  sendsigs
 [ - ]  ssh
 [ + ]  syslog-ng
 [ - ]  umountfs
 [ - ]  umountnfs.sh
 [ - ]  umountroot
 [ - ]  urandom
 [ + ]  wazuh-api
 [ - ]  wazuh-manager

**Comment by xr09** [comment]
Which image version are you running?

Authd is started by default when the manager starts:

![Screenshot_20201201_123535](https://user-images.githubusercontent.com/1380243/100735590-c0289a80-33d1-11eb-85df-e9bb98294505.png)

Here is the start command: https://github.com/wazuh/wazuh-docker/blob/master/wazuh-odfe/config/etc/cont-init.d/2-manager#L113

The `ossec-control` script has integrated logic to determine which ossec processes to start depending on the ossec.conf modules enabled.

**Comment by xr09** [comment]
Hey @alphaDev23, I'm marking this issue as solved, feel free to reopen if needed.
