### ISSUE TITLE
Password Fun

### ISSUE THREAD

**Issue by evil-toast-nom-nom** [wazuh/wazuh-docker#419]
Hey There, first off, thanks for creating a great product!

I used [this ](https://documentation.wazuh.com/4.0/docker/wazuh-container.html) guide to perform a "production" deployment.

From what I could see the following passwords were hard-coded in the docker-compose file: "production-cluster.yml"
Elastic Credentials: 
[here](https://github.com/wazuh/wazuh-docker/blob/3f53a0c174ea7dfd7be65b972b87c5103e985da9/production-cluster.yml#L16), [here](https://github.com/wazuh/wazuh-docker/blob/3f53a0c174ea7dfd7be65b972b87c5103e985da9/production-cluster.yml#L47), and [here](https://github.com/wazuh/wazuh-docker/blob/3f53a0c174ea7dfd7be65b972b87c5103e985da9/production-cluster.yml#L142)
API Credentials: 
[here](https://github.com/wazuh/wazuh-docker/blob/3f53a0c174ea7dfd7be65b972b87c5103e985da9/production-cluster.yml#L22) and [here](https://github.com/wazuh/wazuh-docker/blob/3f53a0c174ea7dfd7be65b972b87c5103e985da9/production-cluster.yml#L148)

When I changed the respective credentials in the ["production-cluser.yml"](https://github.com/wazuh/wazuh-docker/blob/master/docker-compose.yml) file as well as updating the hashes in the ["internal_users.yml"](https://github.com/wazuh/wazuh-docker/blob/3f53a0c174ea7dfd7be65b972b87c5103e985da9/production_cluster/elastic_opendistro/internal_users.yml#L14) 

I ran into an issue where I invariably end up with a loop with the following log messages: 
kibana_1           | Waiting for Kibana API. Sleeping 5 seconds
elasticsearch_1    | [2020-12-05T09:35:18,939][WARN ][c.a.o.s.a.BackendRegistry] [elasticsearch] Authentication finally failed for elasticadmin from 172.21.0.7:50470

This continues until I stop the containers. 

I have tested the hashes in the "internal_users.yml" against the expected passwords just to be sure. 

If I don't change the passwords, I don't have any issues with running the full cluster. 
I have also tried various combinations of password lengths and different complexity levels. 20 char full ascii to 8 char numeric, and everything in between. 

I would really appreciate your guidance in finding a solution for this challenge. 
Additionally, it would be a good idea to encourage people to change both "elastic" and "api" credentials when creating the cluster as this might result in people's clusters being accessed by unauthorized entites using default credentials.

**Comment by neonmei** [comment]
Hi @evil-toast-nom-nom,
You can -and we strongly advise to- change the elastic credentials presented in `production-cluster.yml` and `internal_users.yml` at elastic cluster creation time.  This behaviour you observe comes from upstream opendistro image:
 * https://github.com/opendistro-for-elasticsearch/opendistro-build/issues/201

In the event you wish to change passwords on an live elastic cluster,  you have to do it manually. First you should update your `internal_users.yml`, work out the security index update using `securityadmin.sh` and reflect those changes in kibana. For these elastic maintenance tasks, there are plenty of resources available as noted in the original issue, to name a few:

* https://discuss.opendistrocommunity.dev/t/default-password-reset/102
* https://opendistro.github.io/for-elasticsearch-docs/docs/security/configuration/security-admin/
* https://opendistro.github.io/for-elasticsearch-docs/docs/troubleshoot/security-admin/
* https://aws.amazon.com/blogs/opensource/change-passwords-open-distro-for-elasticsearch/

Once you worked out the new credentials, you can update `production-cluster.yml` with this information.
Regarding wazuh-api password update, you can change it in the `production-cluster.yml` and it will get automatically updated on container re-creation. For reference see these files:
 * wazuh-odfe/config/etc/cont-init.d/2-manager
 * kibana-odfe/config/wazuh_app_config.sh

Hope this helps.

**Comment by mhrznamn068** [comment]
Getting same issues of authentication

**Comment by xr09** [comment]
Hi @evil-toast-nom-nom,

I just completed the process described on the docs and it's working as expected, the resources provided by @neonmei is all you need.

Just for reference, did you test with curl from the kibana container?  `curl -k -u user:custom_pass https://elasticsearch:9200`

**Comment by xr09** [comment]
Hi again @evil-toast-nom-nom, any feedback on this?

**Comment by evil-toast-nom-nom** [comment]
Hey @xr09 thank you for the response! I'm, finally back, your recommendations makes sense, will re-deploy stack to confirm resolution.

**Comment by xr09** [comment]
Closing this issue as solved, feel free to re-open if needed.
