### ISSUE TITLE
Wazuh v5: Core changes

### ISSUE THREAD

**Issue by pereyra-m** [wazuh/wazuh-docker#436]
### Description

Hi team!

This a tracking issue, meant to enumerate all the changes done in the **wazuh/wazuh** repository by the Core team for `v5.0.0`.
These changes need to be considered for Wazuh 5.0 release.

**Note**: Some of them, are breaking changes.

Regards.

### Items list

- **Ruleset normalization**: all the references to _ossec_ were updated in decoders and rules (epic: wazuh/wazuh-ruleset#784)
- **Configuration tags normalization**: the `<ossec_config>` tag was updated  (epic: https://github.com/wazuh/wazuh/issues/7291)

**Comment by teddytpc1** [comment]
These changes will be done as part of the DevOps overhaul objective.
