### ISSUE TITLE
Define release workflow for building images with ARGs

### ISSUE THREAD

**Issue by xr09** [wazuh/wazuh-docker#437]
## Release Workflow

So far we've been using the built-in Dockerf Hub hooks to trigger image building on the registry itself, this has been successful so far but is not as powerful as it could be.

With the backport of the xpack images we're reusing the `wazuh-odfe` container definition to build both `wazuh-odfe` and `wazuh` images dynamically through different ARGs on build time.

By defining the FILEBEAT_CHANNEL and FILEBEAT_VERSION we can reuse the same sources and build an image with regular filebeat for vanilla Elastic or filebeat-oss for Opendistro compatibility.

![Screenshot_20210209_094355](https://user-images.githubusercontent.com/1380243/107337999-56a4c680-6abb-11eb-9321-3537f02e81bc.png)

## Problem

Docker Hub has no simple solution for building images with ARG values set. See [open issue on Docker's hub-feedback repo](https://github.com/docker/hub-feedback/issues/508)

## Proposed solutions

- Override the build hook on Docker Hub and re-define the buid commands to inject ARGs.
- Build the images on Github Actions by checking for a "docker-release" label and the "merged" condition.

## References

- [ ] https://docs.docker.com/docker-hub/builds/advanced/#override-the-build-phase-to-set-variables
- [ ] [build-and-push action](https://github.com/marketplace/actions/build-and-push-docker-images) on Github Actions
- [ ] [trigger action on PR close](https://brennerm.github.io/posts/trigger-github-actions-on-pr-close.html)

**Comment by alberpilot** [comment]
No more needed, due to own indexer and dashboard.
