### ISSUE TITLE
username&password login

### ISSUE THREAD

**Issue by nu11secur1ty** [wazuh/wazuh-docker#439]
Hello dear friends, how can I change this stupid username and password "admin"?
Thank you and BR

**Comment by nu11secur1ty** [comment]
Hello dear friends, is anyone there?
BR

**Comment by xr09** [comment]
Hi there @nu11secur1ty, you can customize the elasticsearch user by following section `2.3` of the docs [here](https://documentation.wazuh.com/4.0/docker/wazuh-container.html#production-deployment) and specifying the custom user on the docker-compose like the example on: `production-cluster.yml`

![Screenshot_20210215_143114](https://user-images.githubusercontent.com/1380243/107952766-798f1900-6f9a-11eb-9923-e31c7fae2689.png)

![Screenshot_20210215_143226](https://user-images.githubusercontent.com/1380243/107952885-a3e0d680-6f9a-11eb-8f78-304ce4943aa2.png)


![Screenshot_20210215_143148](https://user-images.githubusercontent.com/1380243/107952818-8c095280-6f9a-11eb-9eb6-91c278ad8deb.png)

**Comment by nu11secur1ty** [comment]
Thank you, dear friend!
BR

**Comment by xr09** [comment]
Closing this issue as solved, feel free to reopen if needed.

**Comment by nu11secur1ty** [comment]
Hello friend, after I changed the password kibana can not running, stuck on (Kibana server is not ready yet) :)

**Comment by nu11secur1ty** [comment]
???

**Comment by nu11secur1ty** [comment]
> Closing this issue as solved, feel free to reopen if needed.
Hello friend, after I changed the password Kibana can not running, stuck on (Kibana server is not ready yet) :)
So. I need to know where you set up this default "admin" "admin" when Kibana says please log in to a system. that's all I need dear friend! I was searching at all files and configs and I can't see anything!
BR
Actually, I just want to change this ridiculous user "admin" "admin" at the beginning of Kibana
BR
