### ISSUE TITLE
password changing of admin login in to Kibana - Docker

### ISSUE THREAD

**Issue by nu11secur1ty** [wazuh/wazuh-docker#446]
Hello dear friend xr09, after I changed the password, in to `compose` file, Kibana can not running, stuck on (Kibana server is not ready yet) for more than 30 minutes :dancing_men:  :D, you know why ;)

So. I need to know where you set up this default "admin" "admin" when Kibana says please log in to a system and then connect to my nodes ;) you know what I mean ;), that's all I need dear friend! I was searching at all files and configs and I can't see anything!
BR

**Comment by nu11secur1ty** [comment]
When you want to change this... credentials for the user admin...
```
Will connect to localhost:9300 ... done
ERR: An unexpected IllegalStateException occured: failed to load plugin class [com.amazon.opendistroforelasticsearch.security.OpenDistroSecurityPlugin]
```

**Comment by nu11secur1ty** [comment]
:D :D :D

**Comment by fhielpos** [comment]
Hello nu11secur1ty,

The process to change the opendistro password from docker is the following:

1. Access the elasticsearch node:
```docker-compose exec elasticsearch bash```

This should give you a shell inside `/usr/share/elasticsearch`

2. Move to the `opendistro_security` directory and give the `hash.sh` script the proper permissions:
```cd plugins/opendistro_security
chmod +x tools/hash.sh
```

3. Create a new hash for your password:
```
tools/hash.sh -p NewPassword
```

4. Now copy the hash and replace the one inside `securityconfig/internal_users.yml` on your desired user:
```
admin:
  hash: "<your_new_hash_here>"
  reserved: true
  backend_roles:
  - "admin"
  description: "Demo admin user"
```

5. Execute the securityadmin tool with your certificates:
```
tools/securityadmin.sh -f securityconfig/internal_users.yml -icl -nhnv \
  -cacert ../../config/root-ca.pem \
  -cert ../../config/kirk.pem \
  -key ../../config/kirk-key.pem
```

This is example is with the default certificates, if you are using custom ones, you will need to change the paths with yours.

After that, you should have the following output or similar from the `securityadmin`:
```
Open Distro Security Admin v7
Will connect to localhost:9300 ... done
Connected as CN=kirk,OU=client,O=client,L=test,C=de
Elasticsearch Version: 7.10.0
Open Distro Security Version: 1.12.0.0
Contacting elasticsearch cluster 'elasticsearch' and wait for YELLOW clusterstate ...
Clustername: wazuh-cluster
Clusterstate: YELLOW
Number of nodes: 1
Number of data nodes: 1
.opendistro_security index already exists, so we do not need to create one.
Populate config from /usr/share/elasticsearch/plugins/opendistro_security
Will update '_doc/internalusers' with securityconfig/internal_users.yml
   SUCC: Configuration for 'internalusers' created or updated
Done with success
```

You can also save the `internal_users.yml` file and mount it as a volume when bootstrapping new clusters.

Hope this clarifies your questions!

**Comment by nu11secur1ty** [comment]
Ok, I love you buddy, and thanks for your reply.
KR

**Comment by ashishsecdev** [comment]
> 2\. opendistro_security

The correct path should be `/usr/share/elasticsearch/**plugins**/opendistro_security/tools`

Looks like you missed on `plugins` in your answer.

**Comment by jsoliani** [comment]
The updated path for 4.3.x with Wazuh-Indexer should be `/usr/share/wazuh-indexer/plugins/opendistro-security/tools`

**Comment by akshanshshrivastava** [comment]
Hi there, I want to do same for wazuh kubernetes which is in OpenSearch. but there is no ELASTICSEARCH_PASSWORD in opensearch. 
Where should I change the password?
@fhielpos can you please help me with this :(
