### ISSUE TITLE
NGINX Conf: README

### ISSUE THREAD

**Issue by ar0dd** [wazuh/wazuh-docker#457]
## Broken Link

Was trying to get an understanding for setting up valid vs self signed certs. 

https://github.com/wazuh/wazuh-docker/blob/master/nginx_conf/README.md

**Comment by jcruzlp** [comment]
> ## Broken Link
> 
> Was trying to get an understanding for setting up valid vs self signed certs.
> 
> https://github.com/wazuh/wazuh-docker/blob/master/nginx_conf/README.md

Hello ar0dd,
Thank you for report this link! It was unnoticed, we'll fix this as soon as possible.
To help you with the understanding of the certificates, the main difference is that the trusted certificate is signed by a Certification Authority (or CA), so you have a warranty that it has all the validation standards.
On the other hand, the self-signed certificate could be signed by anyone, so please, be sure that you trust the one who signed those certificates.
To help at the replacement of the demo certificates one of the implicated parts of Wazuh is nginx, that broken link used to contain similar information to the one that appears at our Documentation here: https://documentation.wazuh.com/current/docker/wazuh-container.html#production-deployment
On that page at the 2.- section you can have information about how to replace those demo certificates, to one more secures. And at the 2.5 section, you can find the part that affects Nginx SSL certs.
Thank you for reporting the issue, if you have any further questions, please do not hesitate to ask.
Regards.
