### ISSUE TITLE
Wazuh API Issue

### ISSUE THREAD

**Issue by cohere-soc** [wazuh/wazuh-docker#468]
Wazuh API Connection continues to load. 

![image](https://user-images.githubusercontent.com/54118204/115622894-74b25280-a2c6-11eb-9d42-900c4099b327.png)

The error it's producing is:
Error: 3099 - ERROR3099 - Some Wazuh daemons are not ready yet in node "manager" (wazuh-modulesd->failed)"

![image](https://user-images.githubusercontent.com/54118204/115623605-687ac500-a2c7-11eb-9c90-4c410d25737b.png)

Any suggestions?

**Comment by okynos** [comment]
Hello @cohere-soc 

We detected a problem with the vulnerability-detector NVD feed download that makes some components to stop working.
Probably you suffer this error. The easiest way to avoid this error is update your environment to the 4.1.5 Wazuh version.

Perform these actions:
1. Go to current wazuh-docker git repository deployment.
2. Run `docker-compose down`.
3. Check out to `v4.1.5` tag `git checkout v4.1.5`.
4. Run `docker-compose up`.

I hope it helps don't hesitate to ask us if you have any problem.

Regards.

**Comment by bermannoah** [comment]
Hi @okynos -- will a version for 3.13.3-1 be pushed to dockerhub anytime soon?

**Comment by alberpilot** [comment]
I proceed to close this issue. Please don't hesitate to close it again if you have any doubt. 

Regards, 
Alberto R

**Comment by bermannoah** [comment]
Hi @alberpilot sorry for the delay, this worked perfectly! Thanks again, appreciate everybody's hard work. :)
