### ISSUE TITLE
Docake Update Documentation

### ISSUE THREAD

**Issue by zero77** [wazuh/wazuh-docker#484]
Apologies if i have missed this as its already documented.
But, is there any documentation on updating the wazuh docker images or can i just do a docker pull on all images in the stack.

**Comment by rauldpm** [comment]
Hello @zero77 

Sorry for the late reply.

You can find documentation about Docker in 4.1 in these links:

- https://documentation.wazuh.com/current/docker/docker-installation.html
- https://documentation.wazuh.com/current/docker/wazuh-container.html
- https://documentation.wazuh.com/current/docker/container-usage.html
- https://documentation.wazuh.com/current/docker/upgrade-guide.html
