### ISSUE TITLE
Question regarding upgrades through docker-compose.yml

### ISSUE THREAD

**Issue by kir4h** [wazuh/wazuh-docker#49]
Hi,

While upgrading from 3.3.1 to 3.5.0 using docker-compose file, I have faced several issues so I am now wondering what is the correct procedure in order to upgrade a wazuh environment by using this docker-compose file.

In my case I have uncommented the mount for ossec data
```
    volumes:
      - /mnt/ossec/data:/var/ossec/data:Z
```
What I did:

1. Remove the wazuh running containers `docker-compose down`
2. Edit docker-compose.yml to upgrade the versions according to the most recent ones in this repo
3. Start wazuh containers `docker-compose up -d` 

Is this the proper approach? For instance some of the files I had to edit were the rules contained in ruleset, which are in a volume and maintained therefore accross versions. In my case, some of them were referencing frequency="0" as incorrect values.

 I had also to create an empty api folder (otherwise wazuh-api wouldn't start), and I am now facing some database issues (missing columns, don't have the details at the moment but can give them if necessary)

I also saw that there is the /wazuh_config special folder that copies part of the relevant configuration as a bootstrap, so maybe I should not put  `/var/ossec/data` under a volume? But then again there is api configuration as well so... again, just trying to figure out the puzzle and what I did the wrong way.

Thanks!

**Comment by kir4h** [comment]
By looking through Wazuh mailing list, it seems [this happened also to someone else](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/wazuh/bdhrTMEMgLM/98jBl39FDAAJ)

As @mjflve explains in that thread, entrypoint in Wazuh containers is the responsible for copying the <dir>-template folders (those are the ones supplied with the image) to the <dir> folders (used in the container). Thing is this logic is only applied if <dir> doesn't exist in the volume (in case we want /var/ossec/data as a volume to persist configs after upgrading). Meaning that in general, new template files will not be applied after an upgrade, which can lead to errors because of changes in those files.

The list of `template` dirs is:
``` 
"etc"
"ruleset"
"logs"
"stats"
"queue"
"var/db"
"api"
``` 

For instance in my case, wazuh-api was expecting a folder /var/ossec/data/logs/api to exist, but this folder didn't exist in 3.3.1 in the image. As /var/ossec/data/logs already exists in the volume, new files and folders are not created (in this specific case, maybe a cp -n executed even if the folder exists could help but it won't always be the case)

**Comment by SitoRBJ** [comment]
Hello @kir4h,

First of all, we want to apologize for the delay.

You are absolutely right. Wazuh updates are usually done following the process you described, but until recently, this process produced errors as you mentioned. 

The problem arises when the differences between versions are wide and difficult to control because our intention from Wazuh is to constantly improve the product and improve its functionality as well as its operation and management. 

This makes keeping updates in Docker complex to manage, as product changes can vary greatly, causing errors when updating. 

Therefore we have decided to set a minimum of files to export to the external volume. At first these files should not give problems in the updates but for example, changes in the functioning of the rules as the value of the field frequency in your case could result in an error. 

```
DATA_DIRS[((i++))]="api/configuration"
DATA_DIRS[((i++))]="etc/client.keys"
DATA_DIRS[((i++))]="etc/decoders"
DATA_DIRS[((i++))]="etc/lists"
DATA_DIRS[((i++))]="etc/local_internal_options.conf"
DATA_DIRS[((i++))]="etc/localtime"
DATA_DIRS[((i++))]="etc/ossec.conf"
DATA_DIRS[((i++))]="etc/ossec-init.conf"
DATA_DIRS[((i++))]="etc/rootcheck"
DATA_DIRS[((i++))]="etc/rules"
DATA_DIRS[((i++))]="etc/shared"
DATA_DIRS[((i++))]="etc/sslmanager.cert"
DATA_DIRS[((i++))]="etc/sslmanager.key"
DATA_DIRS[((i++))]="logs"
DATA_DIRS[((i++))]="queue/db"
DATA_DIRS[((i++))]="queue/rootcheck"
DATA_DIRS[((i++))]="queue/agent-groups"
DATA_DIRS[((i++))]="queue/agent-info"
DATA_DIRS[((i++))]="queue/agents-timestamp"
DATA_DIRS[((i++))]="queue/agentless"
DATA_DIRS[((i++))]="queue/cluster"
DATA_DIRS[((i++))]="queue/rids"
DATA_DIRS[((i++))]="queue/fts"
DATA_DIRS[((i++))]="var/multigroups"
```

https://github.com/wazuh/wazuh-docker/blob/master/wazuh/config/data_dirs.env

By this way of proceeding, any file that you want to save or do not want to keep should be managed by the user at this time.

Thank you for your patience, let us know any doubt or suggestion you consider necessary.

Kind regards,

Alfonso Ruiz-Bravo

**Comment by jesuslinares** [comment]
Hi @kir4h ,

As mentioned by @SitoRBJ, this is already fixed.

Please, feel free to re-open the issue if you have any issues/questions.

Thanks.

**Comment by kir4h** [comment]
Thanks for the work @SitoRBJ,

Narrowing down the scope of data_dirs.env will help for sure. As you mention, we will still be affected by ossec inner changes (like the frequency values in rules), or by subfolders like logs/api but hopefully the issues encountered will be reduced.

Let me recap high level behaviour so that other readers can get an idea of the procedure:

1. During docker image build, `init.bash` is invoked. This script:
    *  Inspects `/var/ossec` folder. Renames by appending a `-template` suffix  every folder/file present  in `data_dirs.env`   
    * creates a symbolic link of this file/folder so that the version contained in `data` subfolder (that is, data from the volume which is therefore persisted) is the one used (/var/ossec/folder points to /var/ossec/data/folder)
2. Upon container start (`entrypoint.sh`), for every file/folder  in `data_dirs.env` which doesn't exist in `/var/ossec/data`, this file/folder is copied to `/var/ossec/data` (populating it, this is considered `INITIAL_INSTALL`)

So in the end `data_dirs.env` determine what is removed from the base image (moved to -template and persistent version linked instead) and what is populated in the volume if it doesn't exists.

I was thinking maybe a good idea would be to have a link where this kind of breaking changes are documented. I take it this is not only affecting Docker version of wazuh but wazuh itself (I'm thinking of the frequency value for instance) right?
