### ISSUE TITLE
KQL Queries

### ISSUE THREAD

**Issue by Sivavamsiraju** [wazuh/wazuh-docker#495]
Hi I am tring to fetch the data using the KQL Queries.

Can any one help me out how to get out put using the KQL Queries.

And i am having no knowledge on KQL Queries.

Please help me out.

Thanks In Advance.

**Comment by rauldpm** [comment]
Helo @Sivavamsiraju 

You can currently use KQL Queries in the wazuh kibana interface. The most used location is: `Side panel -> Kibana -> Discover`. Here you will see a search bar where on the right it will appear "KQL" or "Lucene" if KQL is deactivated.

![lucene](https://user-images.githubusercontent.com/14913942/130236540-85270efe-92e8-47a9-b58d-7d9d22b4b649.png)


As an example, I am going to give you these three captures, in the first you can see a search for alerts with a rule level greater than 5 (119 results), the second show alerts less than 5 (84 results) and in the third alerts with a level equal to 5

![png](https://user-images.githubusercontent.com/14913942/130236577-7154a206-427c-4297-9667-399d11979a1f.png)
![png](https://user-images.githubusercontent.com/14913942/130236585-53f622bb-5730-47da-929b-376b3d31fc3d.png)
![=](https://user-images.githubusercontent.com/14913942/130236587-3ee4a65a-d3b3-4b16-a3d3-f253c12d14b2.png)

Regarding the documentation, this syntax is the majority of Elastic, so it is better to consult it in its documentation:

- Lucene: https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-query-string-query.html#query-string-syntax
- KQL: https://www.elastic.co/guide/en/kibana/current/kuery-query.html

**Comment by alberpilot** [comment]
I procced to close this issue due to inactivity. Please don't hesitate to open it again if necessary. 

Regards, 
Alberto R
