### ISSUE TITLE
What's missing for final release?

### ISSUE THREAD

**Issue by igorgatis** [wazuh/wazuh-docker#5]
Looks promising. What's in the roadmap?

Btw, could you please explain main differences between this docker set and wazuh/ossec-elk?

**Comment by jlruizmlg** [comment]
Hi @igorgatis we have a lot of differences

## **wazuh-manager 2.0**
In the following link you can see the Changelog between the version 1.1.1 (included in ossec-elk container) and the actual 2.0 https://github.com/wazuh/wazuh/blob/master/CHANGELOG.md.

## **wazuh-api 2.0**
The [Wazuh API](https://documentation-dev.wazuh.com/user-manual/api/index.html) is an open source RESTful API that allows the Wazuh manager to be interacted with from a web browser, command line tool like cURL, or any script or program that can make web requests. The Wazuh Kibana app relies on this heavily, and Wazuh’s goal is to accommodate complete remote management of the Wazuh infrastructure via the Wazuh Kibana app.

## **Logstash 5.2.2**
Now logstash 5.2.2 include geoloctaion file, so we don't need to download manually, also can apply mapping into Elasticsearch, not more "curl".

## **Kibana 5.2.2**
We include [Wazuh-app](https://github.com/wazuh/wazuh-kibana-app) plugin, this plugin use wazuh-api 2.0 to show you information from your manager configuration, status, services running, agents connected, not connected, etc.
![screen shot 2017-03-31 at 7 57 26 am](https://cloud.githubusercontent.com/assets/13950509/24549614/26f10cae-15e8-11e7-8af1-670d2431b306.png)
![screen shot 2017-03-31 at 7 57 32 am](https://cloud.githubusercontent.com/assets/13950509/24549673/69d2c42c-15e8-11e7-9851-888ccedcc457.png)
![screen shot 2017-03-31 at 7 57 38 am](https://cloud.githubusercontent.com/assets/13950509/24549685/7ef8c3f6-15e8-11e7-8420-4ddf5c443aea.png)

**Comment by igorgatis** [comment]
Any ETA for "Final Release"?

**Comment by jlruizmlg** [comment]
Hi @igorgatis  the code is done.
 
If the code is done, why haven’t we released it?
 
We are now working on the documentation (uses cases, installation guide, components, etc.) and different modules like Puppet, Docker, Ansible, SaltStack, and more which is very important for us and the community.
 
If you install the stable branch 2.0 from the link above or our packages from the following link you will be using Wazuh 2.0
