### ISSUE TITLE
Review Kibana configuration when using X-Pack security

### ISSUE THREAD

**Issue by JuanjiJG** [wazuh/wazuh-docker#50]
Review this Wazuh mailing list post: https://groups.google.com/forum/#!topic/wazuh/pCzCwZG1rRw

Add options when the user is using X-Pack security on Elasticsearch, Logstash and Kibana.

Regards,
Juanjo

**Comment by manuasir** [comment]
Done here https://github.com/wazuh/wazuh-docker/pull/119
