### ISSUE TITLE
Creation of archive folder fails on startup for Wazuh created with kustomization

### ISSUE THREAD

**Issue by linxcat** [wazuh/wazuh-docker#507]
The orchestration written in the odfe folder of this repository is quite good, except that I consistently have a specific problem causing startup to fail. Once services.d begins starting everything up on the manager (master) It always fails because of a bad folder creation attempt

```
021/08/31 19:46:36 wazuh-agentlessd: INFO: Not configured. Exiting.
2021/08/31 19:46:36 wazuh-authd: INFO: Started (pid: 381).
2021/08/31 19:46:36 wazuh-authd: INFO: Accepting connections on port 1515. Using password specified on file: etc/authd.pass
2021/08/31 19:46:36 wazuh-authd: INFO: Setting network timeout to 1.000000 sec.
2021/08/31 19:46:37 wazuh-db: INFO: Started (pid: 396).
2021/08/31 19:46:38 wazuh-execd: INFO: Started (pid: 420).
2021/08/31 19:46:38 wazuh-analysisd: INFO: Total rules enabled: '3882'
2021/08/31 19:46:38 wazuh-analysisd: INFO: The option <queue_size> is deprecated and won't apply. Set up each queue size in the internal_options file.
2021/08/31 19:46:38 wazuh-analysisd: INFO: Started (pid: 433).
2021/08/31 19:46:38 wazuh-analysisd: CRITICAL: (1107): Could not create directory 'logs/archives/2021/' due to [(2)-(No such file or directory)].
[services.d] done.
```

Creating the archive folder in /var/log/ doesn't work, with and without reboot.

I know that there is supposed to be a /var/ossec folder in these containers, but that location doesn't exist at all. Just what the heck is going on?

**Comment by linxcat** [comment]
I've solved this error in my personal fork of wazuh-docker. I added this line to the permanent_data.env file:
`PERMANENT_DATA[((i++))]="/var/ossec/logs/archives"`

This creates the archives folder, which is required since wazuh itself is apparently incapable of creating the whole directory tree automatically

**Comment by vcerenu** [comment]
Hi @linxcat 

Added permanent_data line to fix this Issue.
Any questions or queries please open a new Issue. 
Thanks for the contribution!!

Regards
