### ISSUE TITLE
Support Wazuh with OpenSearch Dashboard (successor of OpenDistro)

### ISSUE THREAD

**Issue by antonisnyc94** [wazuh/wazuh-docker#517]
Amazon moved away from opendistro towards opensearch, so now kibana is replaced with dashboard. Can we make the wazuh plugin compatible with that?

Thanks,
Tony

**Comment by alberpilot** [comment]
Hello @antonisnyc94 

  The @wazuh/frontend team is working on it, so we will let you know when it is ready. 

Regards, 
Alberto R

**Comment by alberpilot** [comment]
Let me close this issue @antonisnyc94, please re-open if you need more information. 

Regards, 
Alberto R

**Comment by antonisnyc94** [comment]
Hey @alberpilot ,

Do you know an estimated time for this? It doesnt have to be on point, just something for me to know on how to proceed with my deployments. Revert back to ES 7.10.2 or stick with OpenSearch 1.0.0. 

regards,
Tony

**Comment by alberpilot** [comment]
Hello @antonisnyc94 

  There is no ETA for now, I would say that it will not be immediate. As soon as I have more information I will let you know.

**Comment by semirke** [comment]
Hi, 
just a +1.
I hope you can figure it out soon :) 

Bests
