### ISSUE TITLE
possible typo in kibana Dockerfile

### ISSUE THREAD

**Issue by rbytheway** [wazuh/wazuh-docker#52]
I've been struggling when building the Wazuh Kibana container with the build never returning after running the kibana-plugin install wazuh-app line.  I modified the following line (replaced the "." in kibana.kibana with ":") and now the docker build takes ~20 minutes and completes successfully.  

line 11:    chown -R kibana.kibana /usr/share/kibana &&\
changed to:     chown -R kibana:kibana /usr/share/kibana &&\

**Comment by jesusgn90** [comment]
Hi @rbytheway , done in https://github.com/wazuh/wazuh-docker/pull/53, thanks for reporting this typo.

Best regards,
Jesús
