### ISSUE TITLE
Cant use AWS integration with the container

### ISSUE THREAD

**Issue by fillipejs** [wazuh/wazuh-docker#54]
The container cant access /proc/sys/net/core/rmem_max, therefore, fails to correctly process the AWS CloudTrail logs.

Tried to add privileged mode and use sysctls options on the compose, added the dependencies needed by the integration plugin expanding the original Wazuh dockerfile.

Manager/api Dockerfile:
`FROM wazuh/wazuh:3.6.1_6.4.0

RUN apt-get update && apt-get install python-pip && pip install boto3`

Docker compose:
`version: '2.1'

services:
  wazuh:
    build: wazuh-manager/
    hostname: wazuh-manager
    restart: always
    ports:
      - "1514:1514/udp"
      - "1515:1515"
      - "514:514/udp"
      - "55000:55000"
    networks:
        - docker_elk
    volumes:
      - /home/appuser/wazuh-data/data:/var/ossec/data:Z
      - /home/appuser/wazuh-data/postfix:/etc/postfix:Z
      - /home/appuser/wazuh-data/ossec.conf:/wazuh-config-mount/etc/ossec.conf
    depends_on:
      - logstash
    sysctls:
      - net.core.rmem_max=212992
    privileged: true
  logstash:
    image: wazuh/wazuh-logstash:3.6.1_6.4.0
    hostname: logstash
    restart: always
    links:
      - elasticsearch:elasticsearch
    ports:
      - "5000:5000"
    networks:
      - docker_elk
    depends_on:
      - elasticsearch
    environment:
      - LS_HEAP_SIZE=2048m
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.0
    hostname: elasticsearch
    restart: always
    ports:
      - "9200:9200"
    environment:
      - node.name=node-1
      - cluster.name=wazuh
      - network.host=0.0.0.0
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 2g
    volumes:
      - /home/appuser/elasticsearch-data:/usr/share/elasticsearch/data:Z
    networks:
        - docker_elk
  kibana:
    image: wazuh/wazuh-kibana:3.6.1_6.4.0
    hostname: kibana
    restart: always
    ports:
      - "5601:5601"
    networks:
      - docker_elk
    depends_on:
      - elasticsearch
    links:
      - elasticsearch:elasticsearch
      - wazuh:wazuh

networks:
  docker_elk:
    driver: bridge
    ipam:
      config:
      - subnet: 172.25.0.0/24`

Fails with the error:
`Creating appuser_wazuh_1         ... error

ERROR: for appuser_wazuh_1  Cannot start service wazuh: OCI runtime create failed: container_linux.go:348: starting container process caused "process_linux.go:402: container init caused \"open /proc/sys/net/core/rmem_max: no such file or directory\"": unknown

ERROR: for wazuh  Cannot start service wazuh: OCI runtime create failed: container_linux.go:348: starting container process caused "process_linux.go:402: container init caused \"open /proc/sys/net/core/rmem_max: no such file or directory\"": unknown
ERROR: Encountered errors while bringing up the project.`

When running the original container and docker compose got this error
`2018/09/24 14:03:42 wazuh-modulesd:aws-s3: INFO: Executing Bucket Analisys: softbox-wazuh-cloudtrail
2018/09/24 14:03:42 wazuh-modulesd:aws-s3: WARNING: Bucket:  -  Returned exit code 1
2018/09/24 14:03:42 wazuh-modulesd:aws-s3: WARNING: Bucket:  -  Unknown error: [Errno 2] No such file or directory: '/proc/sys/net/core/rmem_max'`

I also added those parameters to the Linux host but can't see it set on the container...

If someone could help me I would be grateful.

**Comment by snaow** [comment]
Hi,

The AWS integration is getting the value of `/proc/sys/net/core/rmem_max` in order to get the maximum socket buffer size.
`rmem_max` is kernel parameter that controls the maxium size of receive buffers used by sockets.

The source code lines involved are:

- [https://github.com/wazuh/wazuh/blob/3.6.1/wodles/aws/aws-s3.py#L782](https://github.com/wazuh/wazuh/blob/3.6.1/wodles/aws/aws-s3.py#L782)

------ 

We will fix this for next versions, in case you want to make it work now, you can apply the following hot fix:

Get your current rmem_max value from your docker host:

```
[root@localhost vagrant]# cat /proc/sys/net/core/rmem_max
212992
```

Modify the source code to hardcode this parameter:

- `vi /var/ossec/wodles/aws/aws-s3`
- Replace the following content:

```
with open('/proc/sys/net/core/rmem_max', 'r') as kernel_param:
    max_queue_buffer = int(kernel_param.read().strip())
```
    
By:

```
max_queue_buffer = int(212992)`
```

- Save changes

That's should be all, let us know how it goes.

Regards,
Pedro.

**Comment by SitoRBJ** [comment]
Hello @fillipejs and @snaow,

We are sorry for the delay. 

The variable that caused problems in this section,

https://github.com/wazuh/wazuh/blob/master/wodles/aws/aws-s3.py#L782-L783

is no longer used. 

The following PR fixes the AWS integration used in Docker: [#1880](https://github.com/wazuh/wazuh/pull/1880)

We are working on an alternative solution until the PR is accepted.

We will keep you informed. Thank you very much for your patience. 

Best regards,

Alfonso Ruiz-Bravo

**Comment by SitoRBJ** [comment]
Hello @fillipejs  and @snaow,

We have created a branch dedicated to integration with AWS. This is a temporary solution, until the corrected code is accepted and merged. 

Branch: https://github.com/wazuh/wazuh-docker/tree/aws-integration-compatibility

Use: https://github.com/wazuh/wazuh-docker/blob/aws-integration-compatibility/Use.txt

We hope we have been helpful.

Thank you for your attention and for your patience. 

Best regards,

Alfonso Ruiz-Bravo

**Comment by jesuslinares** [comment]
We will continue this issue here: https://github.com/wazuh/wazuh-docker/issues/68.

Thanks.
