### ISSUE TITLE
Wazuh-apid.py  overloaded

### ISSUE THREAD

**Issue by kendyblack** [wazuh/wazuh-docker#546]
![image](https://user-images.githubusercontent.com/66987635/140673968-6385a904-bf73-4fc6-9ccc-18f9d23aca29.png)

####
Wazuh-apid.py  overloaded despite only receiving requests from one interface.
Please help me fix for api ?

**Comment by lastranikos** [comment]
Hi @kendyblack 
We have not previously reported cases of overloaded in the api.
Can you send information about:
- Your environment.
- Server distribution.
- Cores, ram, and disk space would be helpful.

And in the case of Wazuh, information about the installed:
- Wazuh manager version.
- What type of installation you did.
- Operating system and version.

And the Wazuh manager logs, and the api. To be able to verify what happened.
- /var/ossec/logs/api.log
- /var/ossec/logs/ossec.log

**Comment by kendyblack** [comment]
api.log
![image](https://user-images.githubusercontent.com/66987635/141403312-3e661827-298a-445e-8731-f552dc55a158.png)

**Comment by kendyblack** [comment]
wazuh-odfe/ v4.1.5 .
Server : Centos 7.9
8 CPU
4 GB RAM

**Comment by kendyblack** [comment]
when api runing . cpu apid is around 230%. It causes the api call to fail

**Comment by lastranikos** [comment]
Hi @kendyblack 
can you check /var/ossec/logs/ossec.log? If you do not have critical information, we may review it.

As an observation from version 4.1.5 to the latest stable version of Wazuh (4.2.5), a significant number of improvements were made to the performance of the Wazuh API. That is why I recommend you evaluate the possibility of making an upgrade.

Do you have an allinone server? (with Wazuh manager, Filebeat, Elastic and Kibana)
When do I start this issue? Was it from any change in the configuration or upgrade?

This is the changelog for the latest stable version.
https://github.com/wazuh/wazuh/blob/4.2/CHANGELOG.md

**Comment by kendyblack** [comment]
[ossec.txt](https://github.com/wazuh/wazuh-docker/files/7568269/ossec.txt)

I don't build allinone server. I have an elk cluster on another server. Call to  wazuh-manager with API wazuh. on ossec.log . I don't see anything for API error

**Comment by lastranikos** [comment]
Hi @kendyblack could it be that you sent the Wazuh config file and not the log file?

**Comment by kendyblack** [comment]
![image](https://user-images.githubusercontent.com/66987635/143373538-da1c595f-b353-43b4-9ce4-48e32031465c.png)

**Comment by kendyblack** [comment]
![image](https://user-images.githubusercontent.com/66987635/143373660-52ce7d91-c17d-4ad3-9d9c-b9f2a5b84385.png)

**Comment by lastranikos** [comment]
Hi @kendyblack
We have not yet been able to replicate this issue.
It would be really useful to have the Wazuh Manager logs. Have you had any problem getting them?
You can find the file in:
`/var/ossec/logs/ossec.log`

**Comment by alberpilot** [comment]
Hello @kendyblack 

Feel free to re-open this issue if you need it, I proceed to close due to inactivity. 
Regards, 
Alberto R
