### ISSUE TITLE
Wazuh Plugin  for OpenSearch-Dashboard

### ISSUE THREAD

**Issue by Franckiboy15** [wazuh/wazuh-docker#556]
I know this is a know issue, but do you have now an ETA on when a new plugin for Opensearch-Dashboard will be available?

**Comment by alberpilot** [comment]
Hello @Franckiboy15 
  It's a really hard question. We would like to have it ready before the middle of next year. We are doing our best to have it asap, and for now, I can't be more accurate. 

Hope it helps.
Regards, 
Alberto R
