### ISSUE TITLE
Missing wazuh-template.json in wazuh-master

### ISSUE THREAD

**Issue by pandamasta** [wazuh/wazuh-docker#557]
Hi all,
I couldn't get data from agent registred in cluster node 'manager'. Ok for agent in cluster node 'worker 01'

I got:

`wazuh-master_1     | 2021-11-30T09:25:57.165Z	ERROR	[publisher_pipeline_output]	pipeline/output.go:154	Failed to connect to backoff(elasticsearch(https://elasticsearch:9200)): Connection marked as failed because the onConnect callback failed: error loading template: error checking json file /etc/filebeat/wazuh-template.json for template: stat /etc/filebeat/wazuh-template.json: no such file or directory`

I add the template in wazuh-master_1: /etc/filebeat/wazuh-template.json  from https://raw.githubusercontent.com/wazuh/wazuh/v4.2.5/extensions/elasticsearch/7.x/wazuh-template.json

I restart the agent and it fixed the problem

Cheers

**Comment by vcerenu** [comment]
hello @pandamasta 
The wazuh-template.json file is stored inside the **filebeat-etc** volume.

```
$ docker volume ls | grep filebeat
local     wazuh-docker_filebeat-etc
local     wazuh-docker_filebeat-var
local     wazuh-docker_worker-filebeat-etc
local     wazuh-docker_worker-filebeat-var
$ docker volume inspect wazuh-docker_filebeat-etc
[
    {
        "CreatedAt": "2021-11-30T10:00:41-03:00",
        "Driver": "local",
        "Labels": {
            "com.docker.compose.project": "wazuh-docker",
            "com.docker.compose.version": "1.25.0",
            "com.docker.compose.volume": "filebeat-etc"
        },
        "Mountpoint": "/var/lib/docker/volumes/wazuh-docker_filebeat-etc/_data",
        "Name": "wazuh-docker_filebeat-etc",
        "Options": null,
        "Scope": "local"
    }
]
$ ls -ltr /var/lib/docker/volumes/wazuh-docker_filebeat-etc/_data | grep wazuh-template
-rw------- 1 root root  52820 dic 31  1969 wazuh-template.json
$ 
```

I have performed tests of deployments and it is found when it lifts, so it is necessary to verify that if you have made a wazuh deployment of any previous version, the file is located behind the volume and if it has the necessary permissions.
