### ISSUE TITLE
Allow custom commands or scripts to be run before services are started

### ISSUE THREAD

**Issue by forana** [wazuh/wazuh-docker#57]
`/entrypoint.sh` both configures and starts the services, meaning that, in order to run `ossec-control` actions and have the changes be picked up, there are two hacky solutions I see:

1. Either run those via `docker exec` and then either restart the container or the services within (neither of which are great for an automated installation), or
2. Volume over a modified copy of [wazuh.runit.service](https://github.com/wazuh/wazuh-docker/blob/master/wazuh/config/wazuh-api.runit.service) and add custom commands before `service wazuh-manager start`, which means that future changes to that file will not be picked up.

There should be a way to do this explicitly.

**Comment by SitoRBJ** [comment]
Hello @forana,

We are sorry for the delay. 

This issue is solved in your PR #58

Thank you for your contribution, we proceed to close the issue. 

Best regards,

Alfonso Ruiz-Bravo
