### ISSUE TITLE
Email not working, am I editing the correct ossec.conf file?

### ISSUE THREAD

**Issue by carldavis** [wazuh/wazuh-docker#579]
I cannot get email alerts working and it seems very straightforward. (I have already setup a relay server but there is no traffic from Wazuh to that server.) Before I continue to trouble-shoot I would like to ask if I am editing the correct file. There are two ossec.conf files in the image,

```
/var/ossec/etc/ossec.conf
/wazuh-config-mount/etc/ossec.conf
```

I am editing the local file wazuh_manager.conf which is mounted via 
```
volumes:
  - ./production_cluster/wazuh_cluster/wazuh_manager.conf:/wazuh-config-mount/etc/ossec.conf` 
```

Should I be making changes to `/var/ossec/etc/ossec.conf` instead?

**Comment by teddytpc1** [comment]
Hi @carldavis.
You should modify the `/var/ossec/etc/ossec.conf` file. This file is the one Wazuh is using.
The first time the container is started the `/wazuh-config-mount/etc/ossec.conf` will be copied to `/var/ossec/etc/ossec.conf`. If you need to persist the change in case you create a new environment, you should also make the change in `/wazuh-config-mount/etc/ossec.conf`.

**Comment by carldavis** [comment]
@teddytpc1, Thank you much for the assistance. I was able to get email working once I understood which file to edit.

**Comment by teddytpc1** [comment]
Glad to hear that! I will close the issue. Thanks for the response.
