### ISSUE TITLE
Adapt the Docker deployment to use the new Wazuh indexer default ports.

### ISSUE THREAD

**Issue by alberpilot** [wazuh/wazuh-docker#580]
As mentioned in https://github.com/wazuh/wazuh-packages/issues/1285, the Wazuh indexer must use the same default ports as elasticsearch. We need to change all deployment-involved files to 9200 and 9300 as default ports.

**Comment by vcerenu** [comment]
The requested changes have been made in the PR https://github.com/wazuh/wazuh-docker/pull/577

**Comment by teddytpc1** [comment]
This was tested today and it is working fine.
