### ISSUE TITLE
Adapt the Docker deployment to use the new Wazuh dashboard configuration file name.

### ISSUE THREAD

**Issue by alberpilot** [wazuh/wazuh-docker#581]
Based on https://github.com/wazuh/wazuh-packages/issues/1282, we need to change the Wazuh dashboard configuration file from `dashboard.yml` to `opensearch_dashboards.yml`.

**Comment by teddytpc1** [comment]
This was added to the https://github.com/wazuh/wazuh-docker/pull/577 PR.
