### ISSUE TITLE
Change to /var/ossec/etc/internal_options.conf not persistent

### ISSUE THREAD

**Issue by carldavis** [wazuh/wazuh-docker#592]
Greetings,

I am trying to resolve the error `wazuh-analysisd: ERROR: Too many fields for JSON decoder.` I would like attempt to [resolve](https://github.com/wazuh/wazuh/issues/1439) this by making a change to /var/ossec/etc/internal_options.conf but am not able to determine the correct way to make that change persistent. Specifically I want to change the following: `analysisd.decoder_order_size=1024`

I first created a `local_internal_options.conf` (see file contents below) and tried to mount as a volume in docker-compose.yml

```
     volumes:
       - ./local_internal_options.conf:/var/ossec/etc/local_internal_options.conf`
```
       
local_internal_options.conf was mounted to `/var/ossec/etc/local_internal_options.conf` however it does not appear to have been read (I am unsure how to validate this but the "Too many fields for JSON decoder" error persists). I then tried to mount a duplicate of internal_options.conf (with analysisd.decoder_order_size=1024) directly via docker-compose.yml, however this also failed.

Any guidance in this matter is appreciated.

Contents of local_internal_options.conf
```
# local_internal_options.conf
#
# This file should be handled with care. It contains
# run time modifications that can affect the use
# of OSSEC. Only change it if you know what you
# are doing. Look first at ossec.conf
# for most of the things you want to change.
#
# This file will not be overwritten during upgrades.

analysisd.decoder_order_size=1024
```

**Comment by rauldpm** [comment]
Hello @carldavis 

Currently the docker deployment has a persistent mode that produces this problem that you show, therefore, to mount it through a volume you would have to add the following to the docker-compose.yml file:

```
volumes:
- (...)
- ${PWD}/local_internal_options.conf:/wazuh-config-mount/etc/local_internal_options.conf
```

Note that the destination where the file is mounted is `/wazuh-config-mount/etc/` and not `/var/ossec/etc/`

When running docker-compose up you will see something like this in the log:

```
wazuh_1          | Identified Wazuh configuration files to mount...
wazuh_1          | '/wazuh-config-mount/etc/local_internal_options.conf' -> '/var/ossec/etc/local_internal_options.conf'
```

When accessing the container you will see the following:

```
- docker exec -it 3c4524c60f04 /bin/bash                                                                                                                                                                  
[root@wazuh-manager /]# cat /var/ossec/etc/local_internal_options.conf 
# local_internal_options.conf
#
# This file should be handled with care. It contains
# run time modifications that can affect the use
# of OSSEC. Only change it if you know what you
# are doing. Look first at ossec.conf
# for most of the things you want to change.
#
# This file will not be overwritten during upgrades


analysisd.decoder_order_size=1024
[root@wazuh-manager /]#
```

Regards, Raúl.

**Comment by rauldpm** [comment]
Issue closed due to inactivity, if necessary please feel free to reopen the issue or open a new issue.
