### ISSUE TITLE
Deployment on Docker - Test rework of Docker repository

### ISSUE THREAD

**Issue by SitoRBJ** [wazuh/wazuh-docker#608]
# Test rework of Docker repository 

## Repository review 🔴 

<details>

<summary>Repository review</summary>

### Outdated references 🔴 

- opendistro 🔴 

```bash
multi-node/config/wazuh_indexer/wazuh1.indexer.yml:39:opendistro_security.audit.config.disabled_rest_categories: NONE
multi-node/config/wazuh_indexer/wazuh1.indexer.yml:40:opendistro_security.audit.config.disabled_transport_categories: NONE
multi-node/config/wazuh_indexer/wazuh3.indexer.yml:39:opendistro_security.audit.config.disabled_rest_categories: NONE
multi-node/config/wazuh_indexer/wazuh3.indexer.yml:40:opendistro_security.audit.config.disabled_transport_categories: NONE
multi-node/config/wazuh_indexer/wazuh2.indexer.yml:39:opendistro_security.audit.config.disabled_rest_categories: NONE
multi-node/config/wazuh_indexer/wazuh2.indexer.yml:40:opendistro_security.audit.config.disabled_transport_categories: NONE
```

https://github.com/wazuh/wazuh-docker/blob/4.3/multi-node/config/wazuh_indexer/wazuh1.indexer.yml#L39-L40
https://github.com/wazuh/wazuh-docker/blob/4.3/multi-node/config/wazuh_indexer/wazuh2.indexer.yml#L39-L40
https://github.com/wazuh/wazuh-docker/blob/4.3/multi-node/config/wazuh_indexer/wazuh3.indexer.yml#L39-L40

Should be:

![image](https://user-images.githubusercontent.com/8913336/161238051-a655f18f-7fec-423a-9b06-a8cd90da22f2.png)

https://opensearch.org/docs/latest/security-plugin/audit-logs/index/

This section appears in the wazuh indexer yaml when deployed in multi-node, but is not found in the single-node wazuh indexer yaml, it does not seem consistent. We think it should also appear in the single-node configuration.

References are found in roles and index names but are defaulted in OpenSearch.

- Open Distro 🟡 

https://github.com/wazuh/wazuh-docker/blob/4.3/build-docker-images/wazuh-indexer/config/roles_mapping.yml#L2

This line refers to Open Distro, it is true that many OpenSearch roles and indexes still keep opendistro as a name, but maybe it could be reworded if appropriate.

- xpack 🔴

Deprecated wazuh.yml configuration:

https://github.com/wazuh/wazuh-docker/blob/4.3/build-docker-images/wazuh-dashboard/Dockerfile#L83-L89

https://github.com/wazuh/wazuh-docker/blob/4.3/build-docker-images/wazuh-dashboard/config/wazuh.yml#L84

Original wazuh.yml from wazuh-kibana-app repository:

https://github.com/wazuh/wazuh-kibana-app/blob/4.3-1.2-wzd/server/lib/initial-wazuh-config.ts

We have also found references in the changelog file and readme versions section.

- demo 🔴 

```bash
build-docker-images/wazuh-indexer/config/opensearch.yml:22:- "CN=demo.indexer,OU=Wazuh,O=Wazuh,L=California,C=US"
build-docker-images/wazuh-indexer/config/internal_users.yml:11:## Demo users
build-docker-images/wazuh-indexer/config/internal_users.yml:18:  description: "Demo admin user"
build-docker-images/wazuh-indexer/config/internal_users.yml:23:  description: "Demo kibanaserver user"
build-docker-images/wazuh-indexer/config/internal_users.yml:35:  description: "Demo kibanaro user"
build-docker-images/wazuh-indexer/config/internal_users.yml:42:  description: "Demo logstash user"
build-docker-images/wazuh-indexer/config/internal_users.yml:49:  description: "Demo readall user"
build-docker-images/wazuh-indexer/config/internal_users.yml:56:  description: "Demo snapshotrestore user"
build-docker-images/wazuh-indexer/config/config.sh:101:cp -pr /wazuh-certificates/demo.indexer.pem ${TARGET_DIR}${CONFIG_DIR}/indexer.pem
build-docker-images/wazuh-indexer/config/config.sh:102:cp -pr /wazuh-certificates/demo.indexer-key.pem ${TARGET_DIR}${CONFIG_DIR}/indexer-key.pem
build-docker-images/wazuh-indexer/config/roles_mapping.yml:11:## Demo roles mapping
build-docker-images/wazuh-indexer/config/config.yml:4:    name: demo.indexer
build-docker-images/wazuh-indexer/config/config.yml:5:    ip: demo.indexer
build-docker-images/wazuh-dashboard/config/config.sh:37:cp /wazuh-certificates/demo.dashboard.pem ${CONFIG_DIR}/certs/dashboard.pem
build-docker-images/wazuh-dashboard/config/config.sh:38:cp /wazuh-certificates/demo.dashboard-key.pem ${CONFIG_DIR}/certs/dashboard-key.pem
build-docker-images/wazuh-dashboard/config/config.yml:4:    name: demo.dashboard
build-docker-images/wazuh-dashboard/config/config.yml:5:    ip: demo.dashboard
single-node/config/wazuh_indexer/internal_users.yml:11:## Demo users
single-node/config/wazuh_indexer/internal_users.yml:18:  description: "Demo admin user"
single-node/config/wazuh_indexer/internal_users.yml:23:  description: "Demo kibanaserver user"
single-node/config/wazuh_indexer/internal_users.yml:35:  description: "Demo kibanaro user"
single-node/config/wazuh_indexer/internal_users.yml:42:  description: "Demo logstash user"
single-node/config/wazuh_indexer/internal_users.yml:49:  description: "Demo readall user"
single-node/config/wazuh_indexer/internal_users.yml:56:  description: "Demo snapshotrestore user"
Binary file .git/objects/pack/pack-66841084daac61552fe737ec4c60b7b5602b5cb2.pack matches
multi-node/config/wazuh_indexer/internal_users.yml:11:## Demo users
multi-node/config/wazuh_indexer/internal_users.yml:18:  description: "Demo admin user"
multi-node/config/wazuh_indexer/internal_users.yml:23:  description: "Demo kibanaserver user"
multi-node/config/wazuh_indexer/internal_users.yml:35:  description: "Demo kibanaro user"
multi-node/config/wazuh_indexer/internal_users.yml:42:  description: "Demo logstash user"
multi-node/config/wazuh_indexer/internal_users.yml:49:  description: "Demo readall user"
multi-node/config/wazuh_indexer/internal_users.yml:56:  description: "Demo snapshotrestore user"
```

References are found in the Open Distro to Wazuh-Indexer migration document.

### Readme 🟡 

- Content

We can read a disclaimer that wazuh-indexer works in single cluster mode, but we have a docker-compose in the multi-node section that contradicts this.

![image](https://user-images.githubusercontent.com/8913336/161249348-539e15c8-7f7d-43e7-927d-ef56c52752cd.png)

https://github.com/wazuh/wazuh-docker/blob/4.3/multi-node/docker-compose.yml#L69-L137 

</details>

## Single node test 🔴

<details>

<summary>single-node test</summary>

### checks  🔴

- WUI 🔴 

**NOTE: The same INDEXER user appears but with different passwords, this seems confusing. Should be the same** 🔴 

https://files.slack.com/files-pri/TMYFNFQ3W-F039PNCJH0T/image.png

![image](https://user-images.githubusercontent.com/8913336/161257267-748c444a-4c1d-4aa9-94bb-7af40fb7dde5.png)

The main button is not visible 🔴

![image](https://user-images.githubusercontent.com/8913336/161258051-c98cce55-c5d2-48ab-95d9-8b7482a2c7dc.png)

- Indexer indices 🟡 

![image](https://user-images.githubusercontent.com/8913336/161257813-001088f3-d21d-4a8b-afaa-55d41b91d1e6.png)

As a suggestion, we could make through a template that the auditlog index comes with 0 replicas to avoid the yellow status that will be shown in the indexer cluster health.

</details>

## Multi node test 🔴

<details>

<summary>multi-node test</summary>

### Checks  🔴

- WUI 🔴 

The main button is not visible 🔴

![image](https://user-images.githubusercontent.com/8913336/161261869-bd131282-28c2-49f8-a2c5-f9489455b369.png)

</details>

## Test migration 🔴 

<details>

<summary>test migration</summary>

- Mitragion 🔴

3. Inspect elasticsearch volume 🔴 

```bash
docker volume inspect wazuh-docker_elastic-data-1
[
    {
        "CreatedAt": "2022-04-01T12:57:57Z",
        "Driver": "local",
        "Labels": {
            "com.docker.compose.project": "wazuh-docker",
            "com.docker.compose.version": "1.29.2",
            "com.docker.compose.volume": "elastic-data-1"
        },
        "Mountpoint": "/var/lib/docker/volumes/wazuh-docker_elastic-data-1/_data",
        "Name": "wazuh-docker_elastic-data-1",
        "Options": null,
        "Scope": "local"
    }
]
```

**NOTE: We need the project and version. We believe that the documentation should mention it at this point.** 🔴 

```bash
            "com.docker.compose.project": "wazuh-docker",
            "com.docker.compose.version": "1.29.2",
```

6. Copy the volume content from elasticsearch to Wazuh indexer volumes and old Wazuh manager content to new volumes. Test migration script 🔴 

**NOTE: Please, this advice before!!! In 5th step for example** 🔴 

![image](https://user-images.githubusercontent.com/8913336/161270844-9d1d628a-7270-46ad-9aa0-857efce51910.png)

**NOTE: Please add migration script helper with run examples** 🔴

</details>

**Comment by vcerenu** [comment]
Several fixes were made within the branch [608-misc-fixes](https://github.com/wazuh/wazuh-docker/tree/608-misc-fixes), continue with the rest.

**Comment by vcerenu** [comment]
About opendistro reference in opendistro_security.audit.config.disabled_rest_categories parameter.

The parameter that opensearch says to replace the one in opendistro doesn't work. As it was a parameter to disable Audit Logs logging options, it was removed from the multi-node files.

![image](https://user-images.githubusercontent.com/56500015/162485997-b2863e00-1d06-4c1e-91e0-fcb86aeee140.png)


About Demo references: They are indeed demo references, those that come from the build -docker-images directory correspond to demo certificates that are added to the image to be able to start indexer without mounting a certificate, and in the case of the single-node and multi-node directories they are demo users and passwords , which should be changed in the user-generated deploy to avoid a security breach.

About the main button, We spoke with Alberpilot and the lack of it would not be a stopper
