### ISSUE TITLE
Error while copying multigroups files during second Docker deployment

### ISSUE THREAD

**Issue by jnasselle** [wazuh/wazuh-docker#622]
| Related issue|
|---|
| wazuh/wazuh#13224|
## Description

When following the [Single Node Deployment](https://documentation-dev.wazuh.com/current/deployment-options/docker/wazuh-container.html#single-node-deployment) and [Multi Node Deployment](https://documentation-dev.wazuh.com/current/deployment-options/docker/wazuh-container.html#multi-node-deployment) guide, I noticed that during the second deployment a Error message was shown
 
![image](https://user-images.githubusercontent.com/1791430/165390160-7df135aa-a7b5-43a2-bb50-e3684abcd190.png)

The deployment process continue without any trouble, but showing this error is unnecesary

**Comment by c-bordon** [comment]
This error is due to validation:
```
mount_permanent_data() {
  for permanent_dir in "${PERMANENT_DATA[@]}"; do
    # Check if the path is not empty
    if find ${permanent_dir} -mindepth 1 | read; then
      print "The path ${permanent_dir} is already mounted"
    else
      print "Installing ${permanent_dir}"
      exec_cmd "cp -a ${WAZUH_INSTALL_PATH}/data_tmp/permanent${permanent_dir}/. ${permanent_dir}"
    fi
  done
```

The directory `/var/ossec/var/multigroups` is empty that's why the first if does not pass, it is being tested with an additional validation

**Comment by vcerenu** [comment]
A check was added to find out if there are files to copy within the permanent directories, if there are no files, a warning is logged and the normal process continues
