### ISSUE TITLE
Upgrading process is not working properly

### ISSUE THREAD

**Issue by havidarou** [wazuh/wazuh-docker#63]
Current process involves copying whole folders from older installation into new ones.
For example, the whole /api folder is copied, which results in the Wazuh API crushing.

This process should be seamless.

**Comment by SitoRBJ** [comment]
Hello team, 

This error is solved in PR #65, where we have reduced the number of files exported to the external volume of `/var/ossec` in order to reduce possible conflicts in the updates through Docker.

We proceed to close the issue. 

Regards,

Alfonso
