### ISSUE TITLE
Remove acme-user api user from deployment

### ISSUE THREAD

**Issue by rauldpm** [wazuh/wazuh-docker#632]
Hello team, helping a community user about api users and run_as, I have discovered the following:

- The API has an user called: `acme-user`, with `Administrator` role and `Allow run as` disabled
- This user is created by indicating the user in the` API_USERNAME` variable in docker-compose.yml file
- The acme-user user does not have the necessary configuration to use run_as as a base, that is:
   - Enable `Allow run as` for that user in the interface (Wazuh -> Security -> Users)
   - Enable run_as in wazuh.yml
   - After doing this, a permissions missing message will appear on the interface

![image](https://user-images.githubusercontent.com/14913942/167886497-26b256d2-6c33-46c5-aae2-7292b757c980.png)

- If we provide a custom API user, we must give it with full permissions ready to use, otherwise, we must use the wazuh-wui user, since as @davidjiglesias has indicated to me, the app has internal mechanisms hardcoded with the user wazuh-wui for security.
- If said user is kept with `Allow run as` disabled and the `run_as` is changed to true, then two error messages are displayed in addition to not being able to access the interface configuration

![1](https://user-images.githubusercontent.com/14913942/167887015-131e7584-c5bd-42d7-83da-da5a4d5eb4b5.png)

- After changing acme-user to wazuh-wui and running docker-compose up (clean run), the user acme-user does not appears in the users list.

Regards, Raúl.

**Comment by vcerenu** [comment]
Solved in https://github.com/wazuh/wazuh-docker/pull/633
