### ISSUE TITLE
Change "Docker" to "Docker-compose"

### ISSUE THREAD

**Issue by Spades0** [wazuh/wazuh-docker#634]
The term "Docker" should be "Docker-compose" in https://github.com/wazuh/wazuh-docker/blob/4.3/multi-node/Migration-to-Wazuh-4.3.md and https://github.com/wazuh/wazuh-docker/blob/v4.3.0/multi-node/Migration-to-Wazuh-4.3.md
![image](https://user-images.githubusercontent.com/20155990/168067611-4089bad5-169c-4edf-8375-9680c4803805.png)

**Comment by vcerenu** [comment]
Changed the description within the document to indicate the version of Docker Compose that is requested in the documentation
