### ISSUE TITLE
Use OSS variants for ELK stack

### ISSUE THREAD

**Issue by itskingori** [wazuh/wazuh-docker#64]
Why don't we use the OSS variants of the ELK stack?

* `docker.elastic.co/kibana/kibana-oss:6.4.2`
* `docker.elastic.co/logstash/logstash-oss:6.4.2`

So that we don't have to have issues with X-Pack (we use the OSS version of Elasticsearch).

**References:**

* https://github.com/wazuh/wazuh-docker/blob/3.6.1_6.4.2/kibana/Dockerfile#L2
* https://github.com/wazuh/wazuh-docker/blob/3.6.1_6.4.2/logstash/Dockerfile#L2

**Comment by manuasir** [comment]
Hello @itskingori ,

This is a very interesting idea! We're thinking about launching a branch for OSS images.
Feel free to share your thoughts on this here.

Regards

**Comment by itskingori** [comment]
@manuasir We've moved on from Wazuh, so this is no longer a problem for us. And might not be a problem for most of your users. We had this issue because we're running the OSS docker images of Elasticsearch and all your components use the non-OSS docker images. If your users use the bundles Elasticsearch it should not be a problem.
