### ISSUE TITLE
Missing packages in wash container

### ISSUE THREAD

**Issue by slawekgl79** [wazuh/wazuh-docker#66]
According to documentation (https://documentation.wazuh.com/2.0/user-manual/manager/output-options/manual-email-report/smtp_authentication.html) there are few extra packages needed to run postfix as local SMTP relay.  

Two of them (mailutils and libsasl2-modules) are missing in the latest version of wash container.

Can you please include them in your Dockerfile for future builds?

**Comment by SitoRBJ** [comment]
Hello @slawekgl79,

We are sorry for the delay. 
We created the PR #67  to fix this issue. Until the code is merged, you can use the code located in this branch.

You will only need to follow these commands:

1. Download the branch.

$ git clone https://github.com/wazuh/wazuh-docker.git -b smtp-packages --single-branch

2. Construction of the services with the personalized configuration of the branch. 

$ docker-compose build

3. Builds, (re)creates, starts, and attaches to containers for a service.

$ docker-compose up

We hope this will be helpful. Please do not hesitate to contact us with any questions, problems or suggestions. 

Thank you very much for your attention. 

Kind regards,

Alfonso Ruiz-Bravo

**Comment by slawekgl79** [comment]
Hi @SitoRBJ,

thank you for handling my issue!

Best Regards
Slawek
