### ISSUE TITLE
ERROR: manifest for wazuh/wazuh-*:4.5.0 not found: manifest unknown: manifest unknown

### ISSUE THREAD

**Issue by DemonWareXT** [wazuh/wazuh-docker#671]
Hello everyone,

I think the images for 4.5.0 are broken, I get the error ```ERROR: manifest for wazuh/wazuh-manager:4.5.0 not found: manifest unknown: manifest unknown```
I have tried docker-compose on WSL, Ubuntu and MacOS

The version 4.3.3 seems to work however.

Regards

**Comment by teddytpc1** [comment]
Hi @DemonWareXT.
I assume you tried starting up the environment using master branch. That branch contains development code and the docker images have not been created. 
You should be using the latest tag, which is `v4.3.3`, as you mentioned.

**Comment by DemonWareXT** [comment]
Hi @teddytpc1  that of course fixed my problems :)
thanks a bunch
