### ISSUE TITLE
Error when lookin for decoders in the Wazuh App

### ISSUE THREAD

**Issue by xBounceIT** [wazuh/wazuh-docker#688]
Wazuh 4.3.4 on Docker

When loading the decoder page on the Wazuh App this message appears:
_callee3$/<@https://wazuh.omissis.it/1/bundles/plugin/wazuh/wazuh.chunk.9.js:5:2584962

Here is the console error of the Browser
XHRPOS Thttps://wazuh.omissis.it/api/request
[HTTP/1.1 500 Internal Server Error 1025ms]

	
statusCode	500
error	"Internal Server Error"
message	"3013 - Error reading decoders file: WAZUH_HOME/etc/decoders/001-website-decoder.xml"

**Comment by teddytpc1** [comment]
Hi @xBounceIT.
I was not able to reproduce the error. I went to `Wazuh` > `Decoders` and opened one of the decoders' XMLs without any errors.
Would you please let me know if you created the `001-website-decoder.xml` file?
Can you run the following commands?
- Single-node deployment:
`docker exec single-node_wazuh.manager_1 ls -la /var/ossec/etc/decoders/`
- Multi-node deployment:
`docker exec multi-node_wazuh.master_1 ls -la /var/ossec/etc/decoders/`
`docker exec multi-node_wazuh.worker_1 ls -la /var/ossec/etc/decoders/`

We need to check the `001-website-decoder.xml` file ownership.

**Comment by xBounceIT** [comment]
Hi, there were incorrect permission set to the 001-website-decoder.xml file which after changing solved the problem.

Thanks for your help.
