### ISSUE TITLE
Improve INDEXER_USERNAME and INDEXER_PASSWORD behavior for Filebeat

### ISSUE THREAD

**Issue by teddytpc1** [wazuh/wazuh-docker#695]
The `INDEXER_USERNAME` and `INDEXER_PASSWORD` is only replaced in the `filebeat.yml` the first time it is executed when the `/etc/filebeat` directory is persisted. So, if those variables are updated, they will not be updated in the YML file.
We should modify this behavior, so the users can update the Filebeat password from the manager's manifest.

**Comment by vcerenu** [comment]
The replacement of the parameters used by filebeat was only done if there were lines marked with the "#" symbol, a step that was modified to eliminate these symbols if they were present within the filebeat.yml file, but the replacement of the line where the parameter was declared by that same line but with the value of the different environment variables that are declared in the docker-compose.yml file when starting a service with the Wazuh manager image.
