### ISSUE TITLE
Received fatal alert: bad_certificate wazuh.indexer_1 

### ISSUE THREAD

**Issue by VladimirZD** [wazuh/wazuh-docker#701]
I am running Wazuh docker single-node configuration. For some time it was up and most of the stuff was working, integrity monitoring and security events are visible, but System auditing is empty and no data from Syslog.
I checked docs and it seems I didn't follow instructions as I should so I forgot to update IP information in certs.yml (https://documentation.wazuh.com/current/deployment-options/docker/wazuh-container.html#single-node-deployment).
So I did docker system prune, docker volumes prune, and started from zero.
I edited certs. yam, but I was not sure which IP info to put as docker services are getting IP assigned by docker in random order.
after a few tries (10+) I managed to get services running with the same IPs I put to certs.yml.

Sadly it is not working, I have 2 errors now.
1. When Wazuh is doing a health check I get an error  "No template found for ....."
![image](https://user-images.githubusercontent.com/8065995/181349532-46b353a8-fc38-4865-9ca5-cbb7bdbb26df.png)
2. In logs I can see error 
`wazuh.indexer_1    | [2022-07-26T22:18:04,840][ERROR][o.o.s.s.h.n.SecuritySSLNettyHttpServerTransport] [wazuh.indexer] Exception during establishing a SSL connection: javax.net.ssl.SSLHandshakeException: Received fatal alert: bad_certificate
wazuh.indexer_1    | javax.net.ssl.SSLHandshakeException: Received fatal alert: bad_certificate
wazuh.indexer_1    |    at sun.security.ssl.Alert.createSSLException(Alert.java:131) ~[?:?]
wazuh.indexer_1    |    at sun.security.ssl.Alert.createSSLException(Alert.java:117) ~[?:?]`

Any ideas where the problem is or hints on how to get stuff working?

Thnx

**Comment by gdiazlo** [comment]
Closing this as it was solved in Slack https://wazuh.slack.com/archives/C0A933R8E/p1659339216609729

**Comment by sonaton** [comment]
Can you describe the solution here?

**Comment by VladimirZD** [comment]
I am not 100% sure where the issue was, but for me, it was solved by updating Wazuh to 4.3.6, updating the agent to 4.3.6, then unregistering the agent and registering it again.
