### ISSUE TITLE
Error building containers

### ISSUE THREAD

**Issue by steveyminecraft** [wazuh/wazuh-docker#715]
When I attempt to run the image builder I get the following error
`Removing intermediate container e972ee1dfad2
 ---> 8608540cdf03
Step 10/27 : COPY config/check_repository.sh /
 ---> ffc7f6e7664f
Step 11/27 : RUN chmod 775 /check_repository.sh
 ---> Running in cab5548b8b86
Removing intermediate container cab5548b8b86
 ---> 6651e89377fc
Step 12/27 : RUN source /check_repository.sh
 ---> Running in 3eae2742f9ff
Warning: apt-key output should not be parsed (stdout is not a terminal)
Executing: /tmp/apt-key-gpghome.GUuuUqBGh4/gpg.1.sh --fetch-keys https://packages-dev.wazuh.com/key/GPG-KEY-WAZUH
gpg: requesting key from 'https://packages-dev.wazuh.com/key/GPG-KEY-WAZUH'
gpg: key 96B3EE5F29111145: public key "Wazuh.com (Wazuh Signing Key) <support@wazuh.com>" imported
gpg: Total number processed: 1
gpg:               imported: 1
deb https://packages-dev.wazuh.com/pre-release/apt/ unstable main
Removing intermediate container 3eae2742f9ff
 ---> cb4b32bad1eb
Step 13/27 : RUN apt-get update &&     apt-get install wazuh-manager=${WAZUH_VERSION}-${WAZUH_TAG_REVISION}
 ---> Running in 15601b3520c8
Hit:1 http://security.ubuntu.com/ubuntu focal-security InRelease
Hit:2 http://archive.ubuntu.com/ubuntu focal InRelease
Hit:3 http://archive.ubuntu.com/ubuntu focal-updates InRelease
Hit:4 http://archive.ubuntu.com/ubuntu focal-backports InRelease
Get:5 https://packages-dev.wazuh.com/pre-release/apt unstable InRelease [17.3 kB]
Get:6 https://packages-dev.wazuh.com/pre-release/apt unstable/main amd64 Packages [26.6 kB]
Fetched 43.9 kB in 1s (43.5 kB/s)
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
E: Version '4.5.0-1' for 'wazuh-manager' was not found
The command '/bin/sh -c apt-get update &&     apt-get install wazuh-manager=${WAZUH_VERSION}-${WAZUH_TAG_REVISION}' returned a non-zero code: 100
ERROR: Service 'wazuh.manager' failed to build : Build failed
`

**Comment by c-bordon** [comment]
Hello, I am seeing that you are working on the master branch, in this branch we have the development of the next version of Wazuh, so we recommend you use the latest release tag, which has the latest stable version of Wazuh:
https://github.com/wazuh/wazuh-docker/tree/v4.3.7
Retry your tests from this branch
