### ISSUE TITLE
Error in login "Cookie “security_authentication” has been rejected because it is already expired. " 

### ISSUE THREAD

**Issue by giper45** [wazuh/wazuh-docker#721]
Hello, we have a wazuh docker instance installed in production environment. 
Unfortunately, without any update, we encounter the following error in the login: 

<img width="416" alt="image" src="https://user-images.githubusercontent.com/18548727/190596912-f6ce4c7a-639b-40de-9463-718d1d331469.png">   

The error seems to be related with an unstable kibana version issue: 
https://github.com/wazuh/wazuh-kibana-app/issues/4108     

The error is related with

Anyway, we did not perform any update on the envirnoment and it always worked in the years. 
We use the following docker images (production-cluster.yml environment):  

```   
image: wazuh/wazuh-odfe:4.1.5    
image: amazon/opendistro-for-elasticsearch:1.13.2                                                                      
image: wazuh/wazuh-kibana-odfe:4.1.5                                                                                   
```

Could you give us a solution? 
Thank you very much in advance.

**Comment by teddytpc1** [comment]
Hi, @giper45.
I see that this issue was addressed by @AlexRuiz7 [here](https://github.com/wazuh/wazuh-kibana-app/issues/4536).
Do you need further assistance?

**Comment by giper45** [comment]
Hi @teddytpc1 , yes, it was the solution, not related with the docker stack, sorry for the issue. 
Thank you very much.
