### ISSUE TITLE
Error file not found: ./build-docker-images/build-images.yml in Wazuh docker Image Builder

### ISSUE THREAD

**Issue by AdamFarouklg** [wazuh/wazuh-docker#731]
When executed the build-images.sh file in the ./build-docker-images directory, this error happened eventhough the build-images.yml file is existing in this directory. 
<img width="570" alt="image" src="https://user-images.githubusercontent.com/65499327/196049267-fd9e387a-eaf4-4383-8862-674d3199a6be.png">

**Comment by rauldpm** [comment]
Hello @AdamFarouklg 

To run this script you need to run it from the root of the directory, the command would be:

- bash build-docker-images/build-images.sh

Please, read the README.md file: https://github.com/wazuh/wazuh-docker/blob/v4.3.9/build-docker-images/README.md

Regards, Raúl.
