### ISSUE TITLE
Disable filebeat service on wazuh-manager docker container

### ISSUE THREAD

**Issue by egrzeszczak** [wazuh/wazuh-docker#732]
Hi, I'm trying to run a wazuh manager in a docker container, but I need to use something else instead of filebeat (I want to use fluentbit). Is there an efficient way to **disable the filebeat service** so the container won't shut itself down?

Docker image I'm working with:
`wazuh/wazuh-manager:4.3.8`

Similar issue: 
#363

When trying to stop the service manually from inside the container:
```
root@420da2fa5557:/# service filebeat stop
...
Filebeat exited. code=256
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
```

Any hint on how to achieve this would be much appreciated

**Comment by teddytpc1** [comment]
Hi @egrzeszczak.
The best way to achieve this will be to build a new image without Filebeat. You will need to:
- Modify the [Dockerfile](https://github.com/wazuh/wazuh-docker/blob/v4.3.8/build-docker-images/wazuh-manager/Dockerfile) to delete all the Filebeat-related steps.

- Modify [this line](https://github.com/wazuh/wazuh-docker/blob/v4.3.8/build-docker-images/wazuh-manager/Dockerfile#L36) in the Dockerfile to make sure the [1-config-filebeat](https://github.com/wazuh/wazuh-docker/blob/v4.3.8/build-docker-images/wazuh-manager/config/etc/cont-init.d/1-config-filebeat) file and the [services.d/filebeat](https://github.com/wazuh/wazuh-docker/tree/v4.3.8/build-docker-images/wazuh-manager/config/etc/services.d/filebeat) are not copied to the Wazuh manager's image. You can modify the line in the Dockerfile, or remove the file and directory.

You can find how to build the images here:
- [README](https://github.com/wazuh/wazuh-docker/blob/v4.3.8/build-docker-images/README.md)

**Comment by egrzeszczak** [comment]
Hello @teddytpc1 

Thank you! Will try to build that manager this way on the weekend. I've also used Filebat to pass logs to graylog successfully, will decide which is best for my project. For now thanks for your help

Have a nice day :sunglasses:
