### ISSUE TITLE
Failed to load settings from /usr/share/wazuh-indexer/config/opensearch.yml

### ISSUE THREAD

**Issue by security101** [wazuh/wazuh-docker#737]
Hi, 

I apply https://documentation.wazuh.com/current/deployment-options/docker/wazuh-container.html for a docker-compose Single-node deployment. Docker-compose runs and completes but when looking at the logfile I see frequently repeating the message: 

> single-node-wazuh.indexer-1    | Exception in thread "main" SettingsException[Failed to load settings from /usr/share/wazuh-indexer/config/opensearch.yml]; nested: AccessDeniedException[/usr/share/wazuh-indexer/config/opensearch.yml];

WAZUH Docker: v4.3.9
Docker Compose version v2.6.0
CentOS 8 (4.18.0-394.el8.x86_64 )

Any advice? 

Thank you in advance.

**Comment by rauldpm** [comment]
Hello @security101 

This error seems to be due to the permissions of said file, could you show us its properties?

```
ls -l /usr/share/wazuh-indexer/config/opensearch.yml
```

In a functional deployment it should have the following values:

```
wazuh-indexer@wazuh:~$ ls -l /usr/share/wazuh-indexer/config/opensearch.yml
-rw-r--r--. 1 root root 1882 Oct 31 13:44 /usr/share/wazuh-indexer/config/opensearch.yml
```

Have you made any changes to the code before or after deploying?

**Comment by alberpilot** [comment]
I proceed to close this issue due to inactivity. Please don't hesitate to re-open if necessary.
