### ISSUE TITLE
Upgrade Elastic stack to 6.5.2

### ISSUE THREAD

**Issue by h4xmd** [wazuh/wazuh-docker#74]
We are in a state where we have upgraded our servers to ElasticSearch 6.5.2 which means that Kibana will no longer connect to them.

I tried to make a branch and pull request with the changes but get a 403 in doing so.

**Comment by jesuslinares** [comment]
Hi @h4xmd ,

We added the PR https://github.com/wazuh/wazuh-docker/pull/75. It will be published soon.
Thanks.
