### ISSUE TITLE
Remove `queue_size` option from managers `ossec.conf`

### ISSUE THREAD

**Issue by alberpilot** [wazuh/wazuh-docker#748]
The `queue_size` option was deprecated in 4.4.0 and should be removed from the manager configuration docker. It's necessary to determine if current values were the default values and, if so, safely remove them. In another case, the corresponding option in `internal_options.conf` should be added. 

## Tasks
- Identify the `queue_size` option location, including configuration templates. 
- Investigate if `queue_size` value is the default one. If so, remove `queue_size` option from all occurrences. Otherwise, modify `internal_options.conf` including the current value to the new `queue_size` option. 

## Validation
Make sure that the message
```
2022/11/16 22:23:41 wazuh-analysisd: INFO: The option <queue_size> is deprecated and won't apply. Set up each queue size in the internal_options file.
```
doesn't appear and no related errors occur.

**Comment by vcerenu** [comment]
It was analyzed in the documentation and the value I had configured for the `queue_size` parameter was the default value:
https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/remote.html?highlight=queue_size#queue-size

We proceeded to remove the queue_size tags from all the `ossec.conf`

**Comment by alberpilot** [comment]
The option to remove should be present in the global section but in this repository is not there.
