### ISSUE TITLE
Review upgrade

### ISSUE THREAD

**Issue by jesuslinares** [wazuh/wazuh-docker#76]
The upgrade is failing due to:

**.templates.db files**
It will be fixed en Wazuh v3.8.0 (https://github.com/wazuh/wazuh/issues/2050) but we need a workaround:
The following files must be removed before the upgrade:
- /var/ossec/queue/db/.template.db
- /var/ossec/var/db/.template.db

**internal_options.conf**
Since we save the internal_options.conf in etc, it will not be overwritten during an upgrade. If Wazuh expects new settings in that file, it will fail.
We need to remove it and push the new one.

**Comment by havidarou** [comment]
Also, db migration is not possible due to newer versions not mounting older db paths (syscheck).
I'm not sure what could be the best solution to this issue.
