### ISSUE TITLE
Docker-Compose Proxy Issue

### ISSUE THREAD

**Issue by denizciftci-sec** [wazuh/wazuh-docker#762]
Hi, 

We have issues with proxy in our docker-compose environment. We are running single-node setup in a docker environment.
When I define the proxy variable in config file for wazuh-manager (http_proxy,https_proxy,no_proxy) in order to test integration between slack, I receive the alerts on slack side but the alerts are not appearing in the dashboard.
There is no strict restriction on the proxy side, we just need to use it for internet access.
How can I define a proper proxy environment settings for indexer, manager, dashboard?
For testing purposes when I put http_proxy/https_proxy in dashboard environment settings, even the api service got crashed.

**Comment by teddytpc1** [comment]
Hi @denizciftci-sec.
1. What value have you configured for the `no_proxy` variable?
2. Can you share the `docker-compose.yml` file with the proxy-related variables, please?
3. What do you mean by "config file for wazuh-manager" here: `When I define the proxy variable in config file for wazuh-manager`?.

**Comment by denizciftci-sec** [comment]
Hi, I was able to solve this issue. The fix was re-creating the containers after defining the new proxy variables. docker-compose reboot wont let the add new env variables in images. thanks

**Comment by teddytpc1** [comment]
Glad to hear that. I will close the issue. Thanks.
