### ISSUE TITLE
Wazuh 4.4 installation - The opensearch-env binary fails for custom wazuh-indexer configuration path

### ISSUE THREAD

**Issue by mingo-devsec** [wazuh/wazuh-docker#772]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.4.0 | Wazuh Indexer | Manager | Sources | Linux |

## Description
We noticed that `opensearch-env` has failed when running the `opensearch-plugin` during the Wazuh Indexer installation in version 4.4 by using the wazuh-indexer [Dockerfile](https://github.com/wazuh/wazuh-docker/blob/4.4/build-docker-images/wazuh-indexer/config/config.sh)
```
/usr/share/wazuh-indexer/bin/opensearch-env: line 106: cd: /etc/wazuh-indexer: No such file or directory
```
### Additional context
We found that `OPENSEARCH_PATH_CONF` is defined to `/etc/wazuh-indexer` in the `opensearch-env` of the new base:
https://packages-dev.wazuh.com/pre-release/stack/indexer/wazuh-indexer-base-4.4.0-1-linux-x64.tar.xz

It impacts deployments with other `OPENSEARCH_PATH_CONF` than `/etc/wazuh-indexer`

If you set your customized OPENSEARCH_PATH_CONF variable, be aware that other default environment variables will not be loaded.
Reference: https://opensearch.org/docs/2.4/install-and-configure/configuration/#configuration-file

**Comment by teddytpc1** [comment]
This issue is already resolved.
