### ISSUE TITLE
Vulnerability Tests

### ISSUE THREAD

**Issue by vcerenu** [wazuh/wazuh-docker#773]
It is necessary to verify the implementation of the vulnerability test for Docker images with Trivi in the test that is carried out when generating a PR to the main branch of the wazuh-docker repository.
The development of this test was carried out in the branch https://github.com/wazuh/wazuh-docker/tree/4.3-include-trivy and it is necessary to check that it is compatible with the current tests.

**Comment by vcerenu** [comment]
Implemented Wazuh image scans in Docker within the Github Action test. It was verified that the test is carried out correctly and the results are imported correctly in the Github security tab.

**Comment by teddytpc1** [comment]
The task should be executed periodically using `cron` instead of an action.

**Comment by vcerenu** [comment]
The vulnerability scan of the job executed during the Pull Requests was eliminated and a new Workflow was created where the scan job is executed on Mondays at 8:00 am UTC.

**Comment by vcerenu** [comment]
I was working on the configuration of the vulnerability test, to add execution options and the messages sent by Slack.

Timeout parameters were also added since one of the tests is quite long and that generated many errors in its execution.

**Comment by vcerenu** [comment]
The analysis scripts were divided for each of the generated Docker images:

![image](https://user-images.githubusercontent.com/56500015/219136412-b83ead7f-1156-4a87-911b-4d5fa2648801.png)

The results are uploaded separately, but when viewing the Code Scanning analysis, the results appear all together in a single window, mixing them:

![image](https://user-images.githubusercontent.com/56500015/219136628-e9818819-6dd0-4901-bcfa-6e4c77509ac8.png)

The URL submission is modified to review the analysis carried out, it contained a hardcoded path to the branch where the development was located and now the branch is completed with a Github Actions parameter, which at the time of the PR associates the number of PR that is being generated, but it is necessary to verify if at the moment of executing the cronjob it is associated with the branch where it is executed, otherwise it will be necessary to modify this parameter
