### ISSUE TITLE
change default admin password error in filebeat.yml

### ISSUE THREAD

**Issue by reset2099** [wazuh/wazuh-docker#775]
I have an issue with this: 
[Change the password of an existing user (on single-node docker)](https://documentation.wazuh.com/current/deployment-options/docker/wazuh-container.html#change-the-password-of-an-existing-user)
for changing default admin password.

I follow all steps, but showing logs from "single-node-wazuh.manager-1" I get multiple errors:
```
2023-01-31T16:21:11.096Z	ERROR	[publisher_pipeline_output]	pipeline/output.go:154	Failed to connect to backoff(elasticsearch(https://wazuh.indexer:9200)): 401 Unauthorized: Unauthorized
2023-01-31T16:21:11.096Z	INFO	[publisher_pipeline_output]	pipeline/output.go:145	Attempting to reconnect to backoff(elasticsearch(https://wazuh.indexer:9200)) with 12 reconnect attempt(s)
2023-01-31T16:21:11.096Z	INFO	[publisher]	pipeline/retry.go:219	retryer: send unwait signal to consumer
2023-01-31T16:21:11.096Z	INFO	[publisher]	pipeline/retry.go:223	  done
```
from this issue [#712](https://github.com/wazuh/wazuh-docker/issues/712) the problem is in "filebeat.yml"
doing this:

```
docker exec -it single-node_wazuh.manager_1 sed -i "s/SecretPassword/your_admin_password/g" /etc/filebeat/filebeat.yml 

docker exec -it single-node_wazuh.manager_1 service filebeat restart
```
Don't solve the problem. After restarting filebeat  the file "filebeat.yml" don't save changes it always has "SecretPassword"

I'm using wazuh 4.3.10 version deploy in single-node mode 
please help me

**Comment by rauldpm** [comment]
Hello @reset2099 

To change the password of the admin user, you must follow the steps specified in the previous issue and modify the docker-compose file with the new password.

1. Generate a new hash

```
docker run --rm -ti wazuh/wazuh-indexer:4.3.10 bash /usr/share/wazuh-indexer/plugins/opensearch-security/tools/hash.sh
```

2. Modify the hash of the `admin` user in the file `single-node/config/wazuh_indexer/internal_users.yml`

3. Modify the `docker-compose.yml` file by changing the password of the `admin` user to the new `password` (you will have to make two changes)

4. Start the environment

```
docker-compose up
```

Note: During execution, you will see messages like the following in the Wazuh indexer logs:

```
[2023-02-01T17:12:28,940][WARN ][o.o.s.a.BackendRegistry  ] [wazuh.indexer] Authentication finally failed for admin from 172.24.0.3:43742
```

5. Access the Wazuh indexer container and run the following commands:

```
docker exec -it single-node_wazuh.indexer_1 bash
```

```
export INSTALLATION_DIR=/usr/share/wazuh-indexer
export OPENSEARCH_PATH_CONF=${INSTALLATION_DIR}/config
CACERT=$OPENSEARCH_PATH_CONF/certs/root-ca.pem
KEY=$OPENSEARCH_PATH_CONF/certs/admin-key.pem
CERT=$OPENSEARCH_PATH_CONF/certs/admin.pem
export JAVA_HOME=/usr/share/wazuh-indexer/jdk
bash /usr/share/wazuh-indexer/plugins/opensearch-security/tools/securityadmin.sh -cd /usr/share/wazuh-indexer/plugins/opensearch-security/securityconfig/ -nhnv -cacert  $CACERT -cert $CERT -key $KEY -p 9300 -icl
```

6. After this, access the Wazuh manager container and run a Filebeat test

```
docker exec -it single-node_wazuh.manager_1 bash
```

```
filebeat test output
```

7. Access the Wazuh dashboard UI using the admin user and the new password

**Comment by rauldpm** [comment]
Closed due to inactivity. Please don't hesitate to open it again if necessary.
