### ISSUE TITLE
Add functionality for persistent Filebeat files

### ISSUE THREAD

**Issue by rauldpm** [wazuh/wazuh-docker#779]
## Description

It is necessary to add the necessary functionality to allow mounting files related to Filebeat by specifying a destination path in the volumes section of the `wazuh.manager` service in the `docker-compose.yml` file.

This comes from the following case:

- Modify the filebeat.yml file so that it removes or adds a configuration, let's say the case of removing the `seccomp` section.

For this, the user currently has two options:

1. Modify the filebeat.yml file from the repository and redo the image
2. Mount the file manually
   1. Create the filebeat.yml locally with the desired content
   2. Set root:root to the file
   3. Set file permissions

```
chown root:root filebeat.yml
sudo chmod go -w filebeat.yml
```

Once this is done, it is necessary to add the following configuration to the docker-compose.yml file:

```
- ./<path>/filebeat.yml:/etc/filebeat/filebeat.yml
```

This will apply the changes permanently to the created containers so that any modification would be reflected, but currently, this behavior is not desirable since it implies establishing user, group, and permissions on the system where the deployment is made.

It is necessary to add the necessary functionality to specify a mount point as done with `/wazuh-config-mount/etc/ossec.conf`, something like `/filebeat-config-mount/etc/filebeat/filebeat.yml`

**Comment by teddytpc1** [comment]
This issue will be closed as not planned because the intention of the deployments is to avoid having the configuration files in the repository, but using the ones that come with the installation.
