### ISSUE TITLE
Docker hub wazuh images for version 3.7.1 are not tagged properly

### ISSUE THREAD

**Issue by b3zn0gim** [wazuh/wazuh-docker#78]
From documentation at https://documentation.wazuh.com/current/docker/wazuh-container.html we're pointed to docker-compose.yml at https://raw.githubusercontent.com/wazuh/wazuh-docker/master/docker-compose.yml. 

So docker-compose.yml wants to pull images with tag 3.7.1_6.5.3 (for example wazuh/wazuh:3.7.1_6.5.3)

But there is no image with such tag on Docker hub:
```
$ docker pull wazuh/wazuh:3.7.1_6.5.3
Error response from daemon: manifest for wazuh/wazuh:3.7.1_6.5.3 not found
```

Neither it is listed on builds page:
https://hub.docker.com/r/wazuh/wazuh/builds

I assume that latest image should be tagged as 3.7.1_6.5.3 or something like that. Or docker-compose.yml should be fixed. At least I see that latest image contains wazuh version 3.7.1...

```
$ docker history --no-trunc wazuh/wazuh:latest | grep WAZUH_VERSION
<missing>                                                                 3 hours ago         |2 FILEBEAT_VERSION=6.5.3 WAZUH_VERSION=3.7.1-1 /bin/sh -c sed -i '784s/^/    /' /var/ossec/wodles/aws/aws-s3
```

**Comment by jesuslinares** [comment]
Hi @b3zn0gim,

Thanks for the heads up. We have been pinned in the documentation the current version present in Docker Hub (**3.7.0_6.5.0**): https://documentation.wazuh.com/current/docker/wazuh-container.html.

The version **3.7.1_6.5.3** will be in Docker Hub soon.

Regards.
