### ISSUE TITLE
Definite guide to changing the default password single node deployment, container. 

### ISSUE THREAD

**Issue by jeevadotnet** [wazuh/wazuh-docker#789]
Good day

Is there a 100% working guide on how to change the admin password from SecretPassword to something else? I've went through every single guide, even asked ChatGPT 4 with a doc dump into the prompt. Nothing works.

My wazuh deployment is now in a worse of state than before.

**Comment by rauldpm** [comment]
Hello @jeevadotnet 

You can follow the documentation from the following link: https://documentation.wazuh.com/current/deployment-options/docker/wazuh-container.html#change-the-password-of-an-existing-user

1. Stop the deployment stack if it’s running:

```
docker-compose stop
```

2. Run this command to generate a hash of your new password. Once the container launches, input the new password and press enter:

```
docker run --rm -ti wazuh/wazuh-indexer:4.3.10 bash /usr/share/wazuh-indexer/plugins/opensearch-security/tools/hash.sh
```

3. Copy the generated hash. Replace the current `admin` user hash in the `/single-node/config/wazuh_indexer/internal_users.yml` file.

4. Change all occurrences of the default `INDEXER_PASSWORD` in the `docker-compose.yml` file to the new password.

5. Start the deployment stack:

```
docker-compose start
```

6. Run `docker ps` and note the name of the Wazuh indexer container.

7. Run `docker exec -it single-node_wazuh.indexer-1 bash` to enter the container. `single-node_wazuh.indexer-1` is the container name obtained in the previous step.

8. Set the following variables:

```
export INSTALLATION_DIR=/usr/share/wazuh-indexer
export OPENSEARCH_PATH_CONF=${INSTALLATION_DIR}/config
CACERT=$OPENSEARCH_PATH_CONF/certs/root-ca.pem
KEY=$OPENSEARCH_PATH_CONF/certs/admin-key.pem
CERT=$OPENSEARCH_PATH_CONF/certs/admin.pem
export JAVA_HOME=/usr/share/wazuh-indexer/jdk
```

9. Run the `securityadmin.sh` script to apply all changes:

10. Exit the Wazuh indexer container and login with the new credentials on the Wazuh dashboard.

**Comment by jeevadotnet** [comment]
Great, thanks for the time taken to reply in such detail.

I think I missed the part of looking for all instances of `Change all occurrences of the default INDEXER_PASSWORD in the docker-compose.yml file to the new password.` Noticed that there are two locations where it is located in the file.

Confirmed it is working now.
