### ISSUE TITLE
Docker don`t accept the ssl generated 

### ISSUE THREAD

**Issue by VozDeOuro** [wazuh/wazuh-docker#806]
i did the start as said on documentation and i created the certificated with the docker compose generate-indexer-certs.yml
and its still failed is there something that i can do to fix it ?

here is my docker compose 

> `version: '3.7'
> 
> services:
>   wazuh.manager:
>     image: wazuh/wazuh-manager:4.3.10
>     hostname: wazuh.manager
>     restart: always
>     ports:
>       - "1514:1514"
>       - "1515:1515"
>       - "516:516/udp"
>       - "55000:55000"
>     environment:
>       - INDEXER_URL=https://wazuh.indexer:9200
>       - INDEXER_USERNAME=admin
>       - INDEXER_PASSWORD=59
>       - FILEBEAT_SSL_VERIFICATION_MODE=none
>       - SSL_CERTIFICATE_AUTHORITIES=/etc/ssl/root-ca.pem
>       - SSL_CERTIFICATE=/etc/ssl/filebeat.pem
>       - SSL_KEY=/etc/ssl/filebeat.key
>       - API_USERNAME=lc
>       - API_PASSWORD=3X
>     volumes:
>       - wazuh_api_configuration:/var/ossec/api/configuration
>       - wazuh_etc:/var/ossec/etc
>       - wazuh_logs:/var/ossec/logs
>       - wazuh_queue:/var/ossec/queue
>       - wazuh_var_multigroups:/var/ossec/var/multigroups
>       - wazuh_integrations:/var/ossec/integrations
>       - wazuh_active_response:/var/ossec/active-response/bin
>       - wazuh_agentless:/var/ossec/agentless
>       - wazuh_wodles:/var/ossec/wodles
>       - filebeat_etc:/etc/filebeat
>       - filebeat_var:/var/lib/filebeat
>       - ./config/wazuh_indexer_ssl_certs/root-ca-manager.pem:/etc/ssl/root-ca.pem
>       - ./config/wazuh_indexer_ssl_certs/wazuh.manager.pem:/etc/ssl/filebeat.pem
>       - ./config/wazuh_indexer_ssl_certs/wazuh.manager-key.pem:/etc/ssl/filebeat.key
>       - ./config/wazuh_cluster/wazuh_manager.conf:/wazuh-config-mount/etc/ossec.conf
> 
>   wazuh.indexer:
>     image: wazuh/wazuh-indexer:4.3.10
>     hostname: wazuh.indexer
>     restart: always
>     ports:
>       - "9200:9200"
>     environment:
>       - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
>     volumes:
>       - wazuh-indexer-data:/var/lib/wazuh-indexer
>       - ./config/wazuh_indexer_ssl_certs/root-ca.pem:/usr/share/wazuh-indexer/certs/root-ca.pem
>       - ./config/wazuh_indexer_ssl_certs/wazuh.indexer-key.pem:/usr/share/wazuh-indexer/certs/wazuh.indexer.key
>       - ./config/wazuh_indexer_ssl_certs/wazuh.indexer.pem:/usr/share/wazuh-indexer/certs/wazuh.indexer.pem
>       - ./config/wazuh_indexer_ssl_certs/admin.pem:/usr/share/wazuh-indexer/certs/admin.pem
>       - ./config/wazuh_indexer_ssl_certs/admin-key.pem:/usr/share/wazuh-indexer/certs/admin-key.pem
>       - ./config/wazuh_indexer/wazuh.indexer.yml:/usr/share/wazuh-indexer/opensearch.yml
>       - ./config/wazuh_indexer/internal_users.yml:/usr/share/wazuh-indexer/opensearch-security/internal_users.yml
> 
>   wazuh.dashboard:
>     image: wazuh/wazuh-dashboard:4.3.10
>     hostname: wazuh.dashboard
>     restart: always
>     ports:
>       - 5601:5601
>     environment:
>       - INDEXER_USERNAME=admin
>       - INDEXER_PASSWORD=aaad
>       - WAZUH_API_URL=https://wazuh.manager
>       - API_USERNAME=wazuh-wui
>       - API_PASSWORD=aaaaa
>     volumes:
>       - ./config/wazuh_indexer_ssl_certs/wazuh.dashboard.pem:/usr/share/wazuh-dashboard/certs/wazuh-dashboard.pem
>       - ./config/wazuh_indexer_ssl_certs/wazuh.dashboard-key.pem:/usr/share/wazuh-dashboard/certs/wazuh-dashboard-key.pem
>       - ./config/wazuh_indexer_ssl_certs/root-ca.pem:/usr/share/wazuh-dashboard/certs/root-ca.pem
>       - ./config/wazuh_dashboard/opensearch_dashboards.yml:/usr/share/wazuh-dashboard/config/opensearch_dashboards.yml
>       - ./config/wazuh_dashboard/wazuh.yml:/usr/share/wazuh-dashboard/data/wazuh/config/wazuh.yml
>     depends_on:
>       - wazuh.indexer
>     links:
>       - wazuh.indexer:wazuh.indexer
>       - wazuh.manager:wazuh.manager
> 
>       
> volumes:
>   wazuh_api_configuration:
>   wazuh_etc:
>   wazuh_logs:
>   wazuh_queue:
>   wazuh_var_multigroups:
>   wazuh_integrations:
>   wazuh_active_response:
>   wazuh_agentless:
>   wazuh_wodles:
>   filebeat_etc:
>   filebeat_var:
>   wazuh-indexer-data:`

  
  **and here the log** 

> wazuh-all-wazuh.indexer-1    | [2023-04-04T02:53:15,660][WARN ][o.o.h.AbstractHttpServerTransport] [wazuh.indexer] caught exception while handling client http traffic, closing connection Netty4HttpChannel{localAddress=/192.168.128.2:9200, remoteAddress=/192.168.128.3:57442}
> wazuh-all-wazuh.indexer-1    | io.netty.handler.codec.DecoderException: javax.net.ssl.SSLHandshakeException: PKIX path validation failed: java.security.cert.CertPathValidatorException: Path does not chain with any of the trust anchors
> wazuh-all-wazuh.indexer-1    |  at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:477) ~[netty-codec-4.1.72.Final.jar:4.1.72.Final]
> wazuh-all-wazuh.indexer-1    |  at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276) ~[netty-codec-4.1.72.Final.jar:4.1.72.Final]
> wazuh-all-wazuh.indexer-1    |  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.72.Final.jar:4.1.72.Final]
> wazuh-all-wazuh.indexer-1    |  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.72.Final.jar:4.1.72.Final]
> wazuh-all-wazuh.indexer-1    |  at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.72.Final.jar:4.1.72.Final]
> wazuh-all-wazuh.indexer-1    |  at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) [netty-transport-4.1.72.Final.jar:4.1.72.Final]
> wazuh-all-wazuh.indexer-1    |  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.72.Final.jar:4.1.72.Final]
> wazuh-all-wazuh.indexer-1    |  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.72.Final.jar:4.1.72.Final]
> wazuh-all-wazuh.indexer-1    |  at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) [netty-transport-4.1.72.Final.jar:4.1.72.Final]
> wazuh-all-wazuh.indexer-1    |  at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166) [netty-transport-4.1.72.Final.jar:4.1.72.Final]
> wazuh-all-wazuh.indexer-1    |  at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:722) [netty-transport-4.1.72.Final.jar:4.1.72.Final]
> wazuh-all-wazuh.indexer-1    |  at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:623) [netty-transport-4.1.72.Final.jar:4.1.72.Final]
> wazuh-all-wazuh.indexer-1    |  at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:586) [netty-transport-4.1.72.Final.jar:4.1.72.Final]
> wazuh-all-wazuh.indexer-1    |  at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496) [netty-transport-4.1.72.Final.jar:4.1.72.Final]
> wazuh-all-wazuh.indexer-1    |  at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986) [netty-common-4.1.72.Final.jar:4.1.72.Final]
> wazuh-all-wazuh.indexer-1    |  at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-common-4.1.72.Final.jar:4.1.72.Final]
> wazuh-all-wazuh.indexer-1    |  at java.lang.Thread.run(Thread.java:832) [?:?]
> wazuh-all-wazuh.indexer-1    | Caused by: javax.net.ssl.SSLHandshakeException: PKIX path validation failed: java.security.cert.CertPathValidatorException: Path does not chain with any of the trust anchors
> wazuh-all-wazuh.indexer-1    |  at sun.security.ssl.Alert.createSSLException(Alert.java:131) ~[?:?]
> wazuh-all-wazuh.indexer-1    |  at sun.security.ssl.TransportContext.fatal(TransportContext.java:369) ~[?:?]
> wazuh-all-wazuh.indexer-1    |  at sun.security.ssl.TransportContext.fatal(TransportContext.java:312) ~[?:?]
> wazuh-all-wazuh.indexer-1    |  at sun.security.ssl.TransportContext.fatal(TransportContext.java:307) ~[?:?]
> wazuh-all-wazuh.indexer-1    |  at sun.security.ssl.CertificateMessage$T13CertificateConsumer.checkClientCerts(CertificateMessage.java:1301) ~[?:?]
> wazuh-all-wazuh.indexer-1    |  at sun.security.ssl.CertificateMessage$T13CertificateConsumer.onConsumeCertificate(CertificateMessage.java:1204) ~[?:?]
> wazuh-all-wazuh.indexer-1    |  at sun.security.ssl.CertificateMessage$T13CertificateConsumer.consume(CertificateMessage.java:1181) ~[?:?]
> wazuh-all-wazuh.indexer-1    |  at sun.security.ssl.SSLHandshake.consume(SSLHandshake.java:396) ~[?:?]
> wazuh-all-wazuh.indexer-1    |  at sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:480) ~[?:?]
> wazuh-all-wazuh.indexer-1    |  at sun.security.ssl.SSLEngineImpl$DelegatedTask$DelegatedAction.run(SSLEngineImpl.java:1267) ~[?:?]
> wazuh-all-wazuh.indexer-1    |  at sun.security.ssl.SSLEngineImpl$DelegatedTask$DelegatedAction.run(SSLEngineImpl.java:1254) ~[?:?]
> wazuh-all-wazuh.indexer-1    |  at java.security.AccessController.doPrivileged(AccessController.java:691) ~[?:?]
> wazuh-all-wazuh.indexer-1    |  at sun.security.ssl.SSLEngineImpl$DelegatedTask.run(SSLEngineImpl.java:1199) ~[?:?]
> wazuh-all-wazuh.indexer-1    |  at io.netty.handler.ssl.SslHandler.runDelegatedTasks(SslHandler.java:1547) ~[netty-handler-4.1.72.Final.jar:4.1.72.Final]
> wazuh-all-wazuh.indexer-1    |  at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1393) ~[netty-handler-4.1.72.Final.jar:4.1.72.Final]
> wazuh-all-wazuh.indexer-1    |  at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1234) ~[netty-handler-4.1.72.Final.jar:4.1.72.Final]
> wazuh-all-wazuh.indexer-1    |  at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1283) ~[netty-handler-4.1.72.Final.jar:4.1.72.Final]
> wazuh-all-wazuh.indexer-1    |  at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:507) ~[netty-codec-4.1.72.Final.jar:4.1.72.Final]
> wazuh-all-wazuh.indexer-1    |  at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:446) ~[netty-codec-4.1.72.Final.jar:4.1.72.Final]
> wazuh-all-wazuh.indexer-1    |  ... 16 more
> wazuh-all-wazuh.indexer-1    | Caused by: sun.security.validator.ValidatorException: PKIX path validation failed: java.security.cert.CertPathValidatorException: Path does not chain with any of the trust anchors
> wazuh-all-wazuh.indexer-1    |  at sun.security.validator.PKIXValidator.doValidate(PKIXValidator.java:369) ~[?:?]
> wazuh-all-wazuh.indexer-1    |  at sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:275) ~[?:?]
> wazuh-all-wazuh.indexer-1    |  at sun.security.validator.Validator.validate(Validator.java:264) ~[?:?]
> wazuh-all-wazuh.indexer-1    |  at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:285) ~[?:?]
> wazuh-all-wazuh.indexer-1    |  at sun.security.ssl.X509TrustManagerImpl.checkClientTrusted(X509TrustManagerImpl.java:138) ~[?:?]
> wazuh-all-wazuh.indexer-1    |  at sun.security.ssl.CertificateMessage$T13CertificateConsumer.checkClientCerts(CertificateMessage.java:1279) ~[?:?]
> wazuh-all-wazuh.indexer-1    |  at sun.security.ssl.CertificateMessage$T13CertificateConsumer.onConsumeCertificate(CertificateMessage.java:1204) ~[?:?]
> wazuh-all-wazuh.indexer-1    |  at sun.security.ssl.CertificateMessage$T13CertificateConsumer.consume(CertificateMessage.java:1181) ~[?:?]
> wazuh-all-wazuh.indexer-1    |  at sun.security.ssl.SSLHandshake.consume(SSLHandshake.java:396) ~[?:?]
> wazuh-all-wazuh.indexer-1    |  at sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:480) ~[?:?]
> wazuh-all-wazuh.indexer-1    |  at sun.security.ssl.SSLEngineImpl$DelegatedTask$DelegatedAction.run(SSLEngineImpl.java:1267) ~[?:?]
> wazuh-all-wazuh.indexer-1    |  at sun.security.ssl.SSLEngineImpl$DelegatedTask$DelegatedAction.run(SSLEngineImpl.java:1254) ~[?:?]
> wazuh-all-wazuh.indexer-1    |  at java.security.AccessController.doPrivileged(AccessController.java:691) ~[?:?]
> wazuh-all-wazuh.indexer-1    |  at sun.security.ssl.SSLEngineImpl$DelegatedTask.run(SSLEngineImpl.java:1199) ~[?:?]
> wazuh-all-wazuh.indexer-1    |  at io.netty.handler.ssl.SslHandler.runDelegatedTasks(SslHandler.java:1547) ~[netty-handler-4.1.72.Final.jar:4.1.72.Final]
> wazuh-all-wazuh.indexer-1    |  at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1393) ~[netty-handler-4.1.72.Final.jar:4.1.72.Final]
> wazuh-all-wazuh.indexer-1    |  at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1234) ~[netty-handler-4.1.72.Final.jar:4.1.72.Final]
> wazuh-all-wazuh.indexer-1    |  at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1283) ~[netty-handler-4.1.72.Final.jar:4.1.72.Final]
> wazuh-all-wazuh.indexer-1    |  at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:507) ~[netty-codec-4.1.72.Final.jar:4.1.72.Final]
> wazuh-all-wazuh.indexer-1    |  at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:446) ~[netty-codec-4.1.72.Final.jar:4.1.72.Final]
> wazuh-all-wazuh.indexer-1    |  ... 16 more
> wazuh-all-wazuh.indexer-1    | Caused by: java.security.cert.CertPathValidatorException: Path does not chain with any of the trust anchors
> wazuh-all-wazuh.indexer-1    |  at sun.security.provider.certpath.PKIXCertPathValidator.validate(PKIXCertPathValidator.java:158) ~[?:?]
> wazuh-all-wazuh.indexer-1    |  at sun.security.provider.certpath.PKIXCertPathValidator.engineValidate(PKIXCertPathValidator.java:84) ~[?:?]
> wazuh-all-wazuh.indexer-1    |  at java.security.cert.CertPathValidator.validate(CertPathValidator.java:309) ~[?:?]
> wazuh-all-wazuh.indexer-1    |  at sun.security.validator.PKIXValidator.doValidate(PKIXValidator.java:364) ~[?:?]
> wazuh-all-wazuh.indexer-1    |  at sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:275) ~[?:?]
> wazuh-all-wazuh.indexer-1    |  at sun.security.validator.Validator.validate(Validator.java:264) ~[?:?]
> wazuh-all-wazuh.indexer-1    |  at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:285) ~[?:?]
> wazuh-all-wazuh.indexer-1    |  at sun.security.ssl.X509TrustManagerImpl.checkClientTrusted(X509TrustManagerImpl.java:138) ~[?:?]
> wazuh-all-wazuh.indexer-1    |  at sun.security.ssl.CertificateMessage$T13CertificateConsumer.checkClientCerts(CertificateMessage.java:1279) ~[?:?]
> wazuh-all-wazuh.indexer-1    |  at sun.security.ssl.CertificateMessage$T13CertificateConsumer.onConsumeCertificate(CertificateMessage.java:1204) ~[?:?]
> wazuh-all-wazuh.indexer-1    |  at sun.security.ssl.CertificateMessage$T13CertificateConsumer.consume(CertificateMessage.java:1181) ~[?:?]
> wazuh-all-wazuh.indexer-1    |  at sun.security.ssl.SSLHandshake.consume(SSLHandshake.java:396) ~[?:?]
> wazuh-all-wazuh.indexer-1    |  at sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:480) ~[?:?]
> wazuh-all-wazuh.indexer-1    |  at sun.security.ssl.SSLEngineImpl$DelegatedTask$DelegatedAction.run(SSLEngineImpl.java:1267) ~[?:?]
> wazuh-all-wazuh.indexer-1    |  at sun.security.ssl.SSLEngineImpl$DelegatedTask$DelegatedAction.run(SSLEngineImpl.java:1254) ~[?:?]
> wazuh-all-wazuh.indexer-1    |  at java.security.AccessController.doPrivileged(AccessController.java:691) ~[?:?]
> wazuh-all-wazuh.indexer-1    |  at sun.security.ssl.SSLEngineImpl$DelegatedTask.run(SSLEngineImpl.java:1199) ~[?:?]
> wazuh-all-wazuh.indexer-1    |  at io.netty.handler.ssl.SslHandler.runDelegatedTasks(SslHandler.java:1547) ~[netty-handler-4.1.72.Final.jar:4.1.72.Final]
> wazuh-all-wazuh.indexer-1    |  at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1393) ~[netty-handler-4.1.72.Final.jar:4.1.72.Final]
> wazuh-all-wazuh.indexer-1    |  at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1234) ~[netty-handler-4.1.72.Final.jar:4.1.72.Final]
> wazuh-all-wazuh.indexer-1    |  at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1283) ~[netty-handler-4.1.72.Final.jar:4.1.72.Final]
> wazuh-all-wazuh.indexer-1    |  at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:507) ~[netty-codec-4.1.72.Final.jar:4.1.72.Final]
> wazuh-all-wazuh.indexer-1    |  at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:446) ~[netty-codec-4.1.72.Final.jar:4.1.72.Final]
> wazuh-all-wazuh.indexer-1    |  ... 16 more
> wazuh-all-wazuh.dashboard-1  | {"type":"log","@timestamp":"2023-04-04T02:53:15Z","tags":["error","opensearch","data"],"pid":39,"message":"[ConnectionError]: unable to verify the first certificate"}
> wazuh-all-wazuh.dashboard-1  | {"type":"log","@timestamp":"2023-04-04T02:53:18Z","tags":["error","opensearch","data"],"pid":39,"message":"[ConnectionError]: unable to verify the first certificate"}

**Comment by teddytpc1** [comment]
Hi @VozDeOuro.
1. What branch/tag are you using?
2. The Wazuh indexer container volume's path has been modified in the `docker-compose.yml`. Have you made the corresponding changes in the `single-node/config/wazuh_indexer/wazuh.indexer.yml`?
3. I also see that the Wazuh manager container port map `514:514` has been changed to `516:516`. What is the reason for this change?

**Comment by VozDeOuro** [comment]
1: on git master on docker 4.3.10 on all 
2 : on bottom
3: my port 514 is already in use 

the paths are correct

wazuh.indexer.yml

> network.host: "0.0.0.0"
> node.name: "wazuh.indexer"
> path.data: /var/lib/wazuh-indexer
> path.logs: /var/log/wazuh-indexer
> discovery.type: single-node
> http.port: 9200-9299
> transport.tcp.port: 9300-9399
> compatibility.override_main_response_version: true
> plugins.security.ssl.http.pemcert_filepath: /usr/share/wazuh-indexer/certs/wazuh.indexer.pem
> plugins.security.ssl.http.pemkey_filepath: /usr/share/wazuh-indexer/certs/wazuh.indexer.key
> plugins.security.ssl.http.pemtrustedcas_filepath: /usr/share/wazuh-indexer/certs/root-ca.pem
> plugins.security.ssl.transport.pemcert_filepath: /usr/share/wazuh-indexer/certs/wazuh.indexer.pem
> plugins.security.ssl.transport.pemkey_filepath: /usr/share/wazuh-indexer/certs/wazuh.indexer.key
> plugins.security.ssl.transport.pemtrustedcas_filepath: /usr/share/wazuh-indexer/certs/root-ca.pem
> plugins.security.ssl.http.enabled: true
> plugins.security.ssl.transport.enforce_hostname_verification: false
> plugins.security.ssl.transport.resolve_hostname: false
> plugins.security.authcz.admin_dn:
> - "CN=admin,OU=Wazuh,O=Wazuh,L=California,C=US"
> plugins.security.check_snapshot_restore_write_privileges: true
> plugins.security.enable_snapshot_restore_privilege: true
> plugins.security.nodes_dn:
> - "CN=wazuh.indexer,OU=Wazuh,O=Wazuh,L=California,C=US"
> plugins.security.restapi.roles_enabled:
> - "all_access"
> - "security_rest_api_access"
> plugins.security.system_indices.enabled: true
> plugins.security.system_indices.indices: [".opendistro-alerting-config", ".opendistro-alerting-alert*", ".opendistro-anomaly-results*", ".opendistro-anomaly-detector*", ".opendistro-anomaly-checkpoints", ".opendistro-anomaly-detection-state", ".opendistro-reports-*", ".opendistro-notifications-*", ".opendistro-notebooks", ".opensearch-observability", ".opendistro-asynchronous-search-response*", ".replication-metadata-store"]
> plugins.security.allow_default_init_securityindex: true
> cluster.routing.allocation.disk.threshold_enabled: false

**Comment by VozDeOuro** [comment]
any idea what it could be ?

**Comment by T0jgli** [comment]
Hi! [This ](https://github.com/wazuh/wazuh-docker/issues/822#issuecomment-1523096642) fixed for me. The path for certificates changed in latest version

**Comment by teddytpc1** [comment]
Hi @VozDeOuro.
You should use the tag `v4.3.10` to deploy. `master` branch contains the latest development changes.
To get it working you have to:
- Remove the current deployment with `docker-compose down`.
- Remove all the related volumes.
- Remove the created certificates.
- Checkout to the `v4.3.10` tag.
- Follow the deployment procedure including the certificate generation.

**Comment by VozDeOuro** [comment]
thx it was fixed
