### ISSUE TITLE
change service names on default compose file for docker swarm

### ISSUE THREAD

**Issue by javierspn** [wazuh/wazuh-docker#819]
The default service names are not allowed for a docker swarm:

_wazuh.manager
wazuh.dashboard_ 

Etc.

They should be modified to:

_wazuh-manager or wazuhmanager 
wazuh-dashboard or wazuhdaahboard_

Other than that, once you modify them on the original compose file the stack runs without issues.

Thanks!

**Comment by ketamin00** [comment]
+1 - having this problem as well

**Comment by rauldpm** [comment]
Issue closed due to inactivity
