### ISSUE TITLE
wazuh behind a reverse proxy

### ISSUE THREAD

**Issue by r4a5a88** [wazuh/wazuh-docker#875]
Hello,

I have the following setup:
We have a reverse proxy with muultiple alias and subdirectories.
The Wazuh Dashboard is on /wazuh
Wazuh runs on singel node moede on a seperate VM 
The URL is https://URL/wazuh but it redirects it tohttps://URL/app/login?

In the create indexer.yml I added - HTTP_PROXY=https://URL/wazuh

IS there a config where you can set the subdirectory variable

**Comment by Maleksafi** [comment]
can share dashboard config , 
try to add this on your dashboard 
server.rewriteBasePath: false

**Comment by colinmollenhour** [comment]
I set it up behind Caddy for free automatic SSL on a unique domain name. Remove the exposed ports for 443 and 9200 from docker-compose.yml and then point Caddy at port 5601 of the dashboard and disable SSL in the file below:

```
--- a/single-node/config/wazuh_dashboard/opensearch_dashboards.yml
+++ b/single-node/config/wazuh_dashboard/opensearch_dashboards.yml
@@ -5,8 +5,9 @@ opensearch.ssl.verificationMode: certificate
 opensearch.requestHeadersWhitelist: ["securitytenant","Authorization"]
 opensearch_security.multitenancy.enabled: false
 opensearch_security.readonly_mode.roles: ["kibana_read_only"]
-server.ssl.enabled: true
+server.ssl.enabled: false
 server.ssl.key: "/usr/share/wazuh-dashboard/certs/wazuh-dashboard-key.pem"
 server.ssl.certificate: "/usr/share/wazuh-dashboard/certs/wazuh-dashboard.pem"
 opensearch.ssl.certificateAuthorities: ["/usr/share/wazuh-dashboard/certs/root-ca.pem"]
 uiSettings.overrides.defaultRoute: /app/wazuh
```

In fact I think the default files should use Caddy out of the box to make this more obvious.

**Comment by r4a5a88** [comment]
yes, I solved it without docker by installing wazuh on a server and turning ssl off in the dashboard config

**Comment by zilvernet** [comment]
is there a way to do this on the single-node docker install?

**Comment by colinmollenhour** [comment]
@zilvernet Yes, see my comment above.

**Comment by GoGit-IT** [comment]
> is there a way to do this on the single-node docker install?

Actually it is easy:
- Open and edit: `/wazuh-docker/single-node/config/wazuh_dashboard/opensearch_dashboards.yml`
- Comment out the following lines like this:
```
#server.ssl.enabled: true
#server.ssl.key: "/usr/share/wazuh-dashboard/certs/wazuh-dashboard-key.pem"
#server.ssl.certificate: "/usr/share/wazuh-dashboard/certs/wazuh-dashboard.pem"
```
Restart/recreate the 3 containers for wazuh.

**Comment by vinay-keshava** [comment]
how to disable ssl in dashboard
i did a quick install from this command
`curl -sO https://packages.wazuh.com/4.9/wazuh-install.sh && sudo bash ./wazuh-install.sh -a`
