### ISSUE TITLE
manifest unknown for wazuh-manager:4.8.0

### ISSUE THREAD

**Issue by Luke-Williams9** [wazuh/wazuh-docker#902]
Following directions in /single-node/README.md

Certificates generated without any issue.
_docker-compose up_ errors out when pulling wazuh-manager:

```
Pulling wazuh.manager (wazuh/wazuh-manager:4.8.0)...
ERROR: manifest for wazuh/wazuh-manager:4.8.0 not found: manifest unknown: manifest unknown
```

Tested on 2 different test machines, in 2 different locations with 2 different internet connections.

When following instructions on [the wazuh documentation site](https://documentation.wazuh.com/current/deployment-options/docker/wazuh-container.html), using v4.4.5, it pulls without issue.

**Comment by malekaaa** [comment]
can you try to build a docker image and run it? This resolves the issue for me
