### ISSUE TITLE
  Wazuh alerts index replicas and shards env variables

### ISSUE THREAD

**Issue by SitoRBJ** [wazuh/wazuh-docker#92]
Hello team,

It is necessary to create environment variables to be able to manage the shards and replicas of the Wazuh alert index. 

Best regards,

Alfonso Ruiz-Bravo

**Comment by jesuslinares** [comment]
We need to do it in Elasticsearch, not in Kibana: https://github.com/wazuh/wazuh-docker/issues/108.
