### ISSUE TITLE
exec /entrypoint.sh: exec format error on RPI4 8gb, Ubuntu Server 22.04 64-bit

### ISSUE THREAD

**Issue by acutediabeetus** [wazuh/wazuh-docker#924]
I am using the docker installation steps here:
https://documentation.wazuh.com/current/deployment-options/docker/wazuh-container.html

and when running line "sudo docker-compose -f generate-indexer-certs.yml run --rm generator" I'm getting following error:
![image](https://github.com/wazuh/wazuh-docker/assets/50199492/2fe54b6f-7740-494d-b08f-8d163fef24b8)

The first time I tried generate the certs, the animation of each of the certs was displayed in the cli and then the above error appeared.

**Comment by rauldpm** [comment]
Hello, currently the deployment for wazuh-docker is compatible with Intel architecture since support for ARM architecture is currently being worked on in the Wazuh dashboard and Wazuh indexer packages due to Filebeat incompatibility on ARM https://github.com/wazuh/wazuh-packages/issues/1637

**Comment by homeassistant-hacs-m** [comment]
Thank you, that makes a lot of sense!

**Comment by vnasser** [comment]
Hello All,
Picking up this old thread again since it's been over 8 months.
So where does Wazuh stand as far as Docker / Pi install of the dashboard components?

**Comment by bbenjamin-sys** [comment]
Hello, 
I'm interested in deploying wazuh on arm64, I'm stuck at the same point for version 4.7, would you have any links to follow progress and be able to contribute if needed.

**Comment by vnasser** [comment]
@bbenjamin-sys 
Wuzah 4.7 dashboard components aren’t yet compatible with ARM architecture. We are all waiting patiently for the glorious 🥳 day when this will be supported.

**Comment by dk-raw** [comment]
It's been almost a full year. Any updates @rauldpm ?
