### ISSUE TITLE
Enable monitoring

### ISSUE THREAD

**Issue by SitoRBJ** [wazuh/wazuh-docker#94]
Hello team,

It is necessary to add the monitoring activation in Elasticsearch. 

```
curl -XPUT "$el_url/_cluster/settings" -H 'Content-Type: application/json' -d'
{
  "persistent": {
    "xpack.monitoring.collection.enabled": true
  }
}
'
```

Regards,

Alfonso Ruiz-Bravo

**Comment by jlruizmlg** [comment]
I think you can enable the Monitoring through the Kibana interface, isn't it??
<img width="1680" alt="screen shot 2019-01-27 at 6 40 04 am" src="https://user-images.githubusercontent.com/13950509/51797131-75023700-21fe-11e9-87eb-ee630465e1bb.png">

**Comment by SitoRBJ** [comment]
Hello @jlruizmlg,

I'm happy to talk to you. You're right, we can enable monitoring from the Kibana interface, but we want to enable it by default in the creation of containers. 

Best regards,

Alfonso Ruiz-Bravo

**Comment by jesuslinares** [comment]
This should be done from Elasticsearch. Moved to this issue: https://github.com/wazuh/wazuh-docker/issues/108.
