### ISSUE TITLE
OpenSearch Plugins - Missing Security

### ISSUE THREAD

**Issue by wolfjudge** [wazuh/wazuh-docker#953]
Hello Wazuh,

We are testing Wazuh in Docker container at the moment and we wanted to test out the tenancy part.

I have encountered an issue trying to configure the Security part on OpenSearch Plugins menu. Security is missing. I also found that in official document in OpenSearch it is enabled by default, so I am not sure why am I missing it.

So the question is, is this by design and I need to enable it, or is it some bug?

Regards

Vuk

**Comment by davidcr01** [comment]
Hello.

First, I would like you to ask about what version of Wazuh you are using.
About reproducing the issue, I deployed a Wazuh Docker deployment of one of our recent versions (4.5.0) following the [related documentation](https://documentation.wazuh.com/current/deployment-options/docker/wazuh-container.html) and everything works as expected.

I have attached a screenshot that shows how the OpenSeach Plugins -> Security page is working correctly.
![image](https://github.com/wazuh/community/assets/72193239/1571313d-a660-4a29-b2ca-29d64c95e671)


Maybe you can get more information by looking at the logs of the Wazuh dashboard app:
```console
sudo docker exec -it single-node-wazuh.dashboard-1 bash
cat /usr/share/wazuh-dashboard/data/wazuh/logs/wazuhapp.log
```
