### ISSUE TITLE
Unable to Add Agent

### ISSUE THREAD

**Issue by gagestinson** [wazuh/wazuh-docker#978]
I am trying to add an agent to my Wazuh Dashboard. I have tried an Ubuntu arm64 computer as well as a Windows 10 x86_64 computer. Both do not connect.

After using the `sudo grep ^status /var/ossec/var/run/wazuh-agentd.state` command provided in the documentation, the following output is given: "status='pending'". 

Using `cat /var/ossec/logs/ossec.log` the following output is given on the latest line:
"2023/09/05 13:51:04 wazuh-agentd: INFO: Requesting a key from server: 192.168.32.2
2023/09/05 13:51:04 wazuh-agentd: ERROR: (1208): Unable to connect to enrollment service at '[192.168.32.2]:1515'"

Just as clarification, 192.168.32.2 is the IP address for the arm64 computer and 192.168.32.4 is the IP address for the Wazuh Manager. I have tried using the both IPs in the `
curl -so wazuh-agent.deb https://packages.wazuh.com/4.x/apt/pool/main/w/wazuh-agent/wazuh-agent_4.5.1-1_arm64.deb && sudo WAZUH_MANAGER='192.168.32.4' WAZUH_AGENT_GROUP='Lab' WAZUH_AGENT_NAME='orangepi5' dpkg -i ./wazuh-agent.deb
`
given on the Wazah Manager add agent page. Both give the same output when using the `cat /var/ossec/logs/ossec.log` command.

Any idea on how to correct this problem?

**Comment by davidcr01** [comment]
Hello. It seems that you are having some connectivity issues between the Wazuh stack and the Wazuh agent. Here are some checks that you should perform:

1. Verify Network Connectivity:

    Ensure that both systems can communicate over the network. Check for any firewall or network restrictions that may be blocking communication. You can try pinging from the agent to the server and vice versa to test connectivity or use the `telnet` tool.

2. Check Port 1515:

    Ensure that port 1515 is open and accessible on the server (192.168.32.2), and that the agent (192.168.32.4) can reach that port. The port 1514 should be checked too. Here is some documentation that explains the necessary ports: https://documentation.wazuh.com/current/user-manual/agent-enrollment/index.html#requirements

3. Wazuh Configuration:

    Verify that the Wazuh server's configuration is set to accept connections from agents. Review the `ossec.conf` configuration file on the server to confirm that it is configured to listen on port 1515 and accept agent connections.

4. Verify Server IP and Port:

    Double-check that the IP address and port you are using in the agent's configuration are correct and match the server's configuration.

5. Restart Services:

    Sometimes, simply restarting both the agent and the Wazuh server can resolve connectivity issues. You can achieve this with the `systemctl restart wazuh-manager` and `systemctl restart wazuh-agent` commands.

6. Firewall and SELinux:

    If you are using a Linux system, check if SELinux is enabled and if it is blocking communication. Also, ensure that firewall rules permit communication on port 1515.

7. Wazuh Version:

    Make sure that both the agent and the server are using the same version of Wazuh to avoid potential compatibility issues. In your case, both the manager and agent should be `v4.5.1` Wazuh version. You can use the `/var/ossec/bin/wazuh-control -j info` command to check the manager version and `/var/ossec/bin/agent_control -i <agent_id>` to check the agent version.

8. Wazuh Logs:

    Finally, examine the Wazuh logs on both the agent and the server for more specific error details. Wazuh logs are typically located in the` /var/ossec/logs` directory on Linux, more specifically at `/var/ossec/logs/ossec.log`.

Hope it helps.

**Comment by xemlo** [comment]
I know this topic is closed, but are you running this Ubuntu server in AWS as an EC2 instance?

**Comment by rathorevs** [comment]
Yes, I am

**Comment by xemlo** [comment]
If the servers are in different availability zones you won’t be able to add the agent.
